"""R-7 (IC-5) - emitter for the project-resident SDK gate module.

[SR-11] Deliberate deviation from the single-templates.py convention,
CONFIRMED at implementation (recorded in docs/changelog.md): this module
emits Python-from-Python, and a separate file keeps the emitted source
syntax-checkable (tests ast.parse the rendered output) without entangling
templates.py's shell-heredoc escaping conventions.

The emitted module is contract surface (seam §9, locked): single public
builder `build_hooks(config)`, no I/O at import time, no network I/O ever,
subprocess-only loading, security-critical hand-edit tier. Refusal reason
strings are semantically equivalent to the shell gates' messages (seam
§6.2 obliges consumers to relay them faithfully); tests/test_sdk_gates.py
asserts each reason literal against the emitted shell hook bodies
(AC-7-5), modulo the documented interpolation sites.
"""
from __future__ import annotations

import json

# The seven gates the SDK substrate carries (R-7). ci-mirror and the
# observability hooks stay shell-only; SessionStart/SessionEnd-class events
# have no Python-SDK HookEvent and remain shell (AC-7-3).
SDK_GATES = (
    "secrets-gate", "spec-gate-commit", "dependency-gate", "test-gate",
    "eval-gate", "tdd-gate", "format-lint-gate",
)

_HEADER = '''"""Bootstrap Protocol SDK gate module (seam §9; protocol >= 2.1.0).

Generated by bootstrap-installer. Edit with care - security-relevant.
This file is manifest-tracked at the SECURITY-CRITICAL hand-edit tier: a
digest mismatch refuses dispatch until reverted or explicitly, auditably
overridden (seam §7.2).

Contract (seam §9, locked):
- Exactly one public builder: build_hooks(config) -> {"PreToolUse":
  [HookMatcher, ...], ...}. Everything else here is private.
- No I/O at import time; no network I/O ever.
- Loaded ONLY inside a subprocess dispatch runner (consumer-owned, e.g.
  Tessera's). Importing this module into a consumer's core process
  violates the seam §2 non-import rule.
- A refusal returns the structured PreToolUse deny shape (seam §4.1 /
  §6.2) with a reason string semantically equivalent to the shell
  gate's message; consumers relay it faithfully.

The full shell hook suite remains installed alongside this module as the
SEV-1 manual path (seam §7.5); this module does not replace it.
"""
from __future__ import annotations

import fnmatch
import os
import re
import subprocess
from pathlib import Path

from claude_agent_sdk import HookMatcher

__all__ = ["build_hooks"]

'''

_STATIC_BODY = '''

def _proj() -> Path:
    # Same project-root resolution as the shell suite (F-2 idiom).
    return Path(os.environ.get("CLAUDE_PROJECT_DIR") or ".")


def _deny(reason: str) -> dict:
    return {"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason,
    }}


def _tool_input(input_data) -> dict:
    ti = (input_data or {}).get("tool_input")
    return ti if isinstance(ti, dict) else {}


def _secrets_gate(config):
    patterns = [p for p in config["secrets"]["never_read_paths"] if p]

    async def secrets_gate(input_data, tool_use_id, context):
        # Hard-block never-read paths. Blocks mid-plan by design (secret
        # exposure is catastrophic). Deny-list bias: over-match, never
        # under-match (shell T-1 semantics) - each pattern is tried
        # as-given AND with an implicit leading '*', case-insensitively,
        # against both basename and full path; '**' normalizes to '*'.
        target = _tool_input(input_data).get("file_path") or ""
        if not target:
            return {}
        base = os.path.basename(target).lower()
        full = target.lower()
        for pat in patterns:
            cpat = pat.replace("**", "*").lower()
            if (fnmatch.fnmatchcase(base, cpat)
                    or fnmatch.fnmatchcase(base, "*" + cpat)
                    or fnmatch.fnmatchcase(full, cpat)
                    or fnmatch.fnmatchcase(full, "*/" + cpat)
                    or fnmatch.fnmatchcase(full, "*" + cpat)):
                return _deny(f"BLOCKED: {target} matches never-read "
                             f"pattern {pat}")
        return {}
    return secrets_gate


def _spec_gate_commit(config):
    async def spec_gate_commit(input_data, tool_use_id, context):
        # Block `git commit` of staged files not referenced by an active
        # spec. Word-boundary match on path or basename (shell S-3
        # semantics), never a loose substring.
        cmd = _tool_input(input_data).get("command") or ""
        if "git commit" not in cmd:
            return {}
        proj = _proj()
        try:
            staged_raw = subprocess.run(
                ["git", "diff", "--cached", "--name-only"],
                capture_output=True, text=True, cwd=proj).stdout
        except OSError:
            staged_raw = ""            # mirrors shell `2>/dev/null || true`
        staged = [f for f in staged_raw.splitlines() if f.strip()]
        if not staged:
            return {}
        corpus_files = []
        index = proj / ".claude" / "specs" / "INDEX.md"
        if index.is_file():
            corpus_files.append(index)
        specs_dir = proj / ".claude" / "specs"
        for tasks_dir in sorted(specs_dir.glob("*/tasks")):
            if tasks_dir.is_dir():
                corpus_files.extend(
                    p for p in sorted(tasks_dir.iterdir()) if p.is_file())
        if not corpus_files:
            return _deny("Commit blocked: no active spec/task files exist "
                         "yet.\\nRun /spec-new before committing.")
        corpus = "\\n".join(
            p.read_text(errors="replace") for p in corpus_files)
        miss = ""
        for f in staged:
            b = os.path.basename(f)
            # [^\\w./-] mirrors the shell class [^[:alnum:]_./-].
            pat = re.compile(
                r"(^|[^\\w./-])(" + re.escape(f) + "|" + re.escape(b)
                + r")([^\\w-]|$)", re.M)
            if not pat.search(corpus):
                miss += " " + f
        if miss:
            return _deny("Commit blocked: files not referenced by any "
                         "active spec:" + miss
                         + "\\nRun /spec-new or add them to a tasks/*.md "
                           "file.")
        return {}
    return spec_gate_commit


_INSTALL_VERBS = re.compile(
    r" (?:npm install|npm i|pip install|pip3 install|yarn add|pnpm add) ")
_VALUE_FLAGS = frozenset({
    "-r", "--requirement", "-e", "--editable", "-c", "--constraint",
    "-t", "--target", "--prefix", "--root", "-d", "--dest",
})


def _dependency_gate(config):
    approved = set(config["deps"]["approved"])

    async def dependency_gate(input_data, tool_use_id, context):
        # Block package installs not on the approved list. Every token
        # after the install/add verb is inspected (shell S-2 semantics);
        # value-taking flags consume the next token.
        cmd = _tool_input(input_data).get("command") or ""
        m = _INSTALL_VERBS.search(f" {cmd} ")
        if not m:
            return {}
        rest = f" {cmd} "[m.end():]
        blocked = ""
        skip_next = False
        for tok in rest.split():
            if skip_next:
                skip_next = False
                continue
            if tok in _VALUE_FLAGS:
                skip_next = True
                continue
            if tok.startswith("-"):
                continue
            name_only = re.split(r"[<>=@~ ]", tok, maxsplit=1)[0]
            if name_only and name_only not in approved:
                blocked += " " + name_only
        if blocked:
            return _deny("Dependency gate: not in deps.md approved list:"
                         + blocked
                         + "\\nApprove in-session and update "
                           ".claude/steering/deps.md.")
        return {}
    return dependency_gate


def _test_gate(config):
    test_cmd = (config["commands"].get("test") or "").strip()

    async def test_gate(input_data, tool_use_id, context):
        # Block `git commit` unless tests passed since the last source
        # edit (mark file .claude/.last-test-pass, as in the shell gate).
        cmd = _tool_input(input_data).get("command") or ""
        if "git commit" not in cmd:
            return {}
        proj = _proj()
        mark = proj / ".claude" / ".last-test-pass"
        stale = True
        if mark.is_file():
            m_mtime = mark.stat().st_mtime
            src = proj / "src"
            stale = src.is_dir() and any(
                p.is_file() and p.stat().st_mtime > m_mtime
                for p in src.rglob("*"))
        if not stale:
            return {}
        if not test_cmd:
            # fail-loud-on-empty-commands: parity with the shell
            # interpolation site "echo 'TODO: commands.test unset' &&
            # exit 1" (AC-7-2) - deny, never allow-by-omission.
            return _deny("TODO: commands.test unset\\n"
                         "Commit blocked: tests failing.")
        r = subprocess.run(test_cmd, shell=True, cwd=proj,
                           capture_output=True, text=True)
        if r.returncode == 0:
            mark.parent.mkdir(parents=True, exist_ok=True)
            mark.touch()
            return {}
        return _deny("Commit blocked: tests failing.")
    return test_gate


def _eval_gate(config):
    async def eval_gate(input_data, tool_use_id, context):
        # Block `git push` touching prompt files unless an eval passed
        # (mark file .claude/.last-eval-pass, as in the shell gate).
        cmd = _tool_input(input_data).get("command") or ""
        if "git push" not in cmd:
            return {}
        proj = _proj()
        try:
            diff = subprocess.run(
                ["git", "diff", "--name-only", "HEAD~1"],
                capture_output=True, text=True, cwd=proj).stdout
        except OSError:
            diff = ""                  # mirrors shell `2>/dev/null`
        if not re.search(r"prompt|\\.md$", diff, re.M):
            return {}
        if (proj / ".claude" / ".last-eval-pass").is_file():
            return {}
        return _deny("Eval gate: run evals before pushing prompt "
                     "changes.")
    return eval_gate


def _tdd_gate(config):
    async def tdd_gate(input_data, tool_use_id, context):
        # Block a Write to source unless a matching test was edited more
        # recently than the target. A nonexistent target denies (parity
        # with the shell `find -newer` failing on a missing reference):
        # the gate's contract is test-first even for new source files.
        target = _tool_input(input_data).get("file_path") or ""
        if not re.match(r"(src|lib)/", target):
            return {}
        stem = os.path.basename(target)
        stem = stem.rsplit(".", 1)[0] if "." in stem else stem
        proj = _proj()
        tpath = proj / target
        newer = False
        if tpath.is_file():
            t_mtime = tpath.stat().st_mtime
            tests_dir = proj / "tests"
            if tests_dir.is_dir():
                newer = any(
                    p.is_file() and p.stat().st_mtime > t_mtime
                    for p in tests_dir.rglob(f"*{stem}*"))
        if not newer:
            return _deny(f"TDD gate: write a failing test for {stem} "
                         f"before {target}.")
        return {}
    return tdd_gate


def _format_lint_gate(config):
    fmt = (config["commands"].get("format") or "").strip()
    lint = (config["commands"].get("lint") or "").strip()

    async def format_lint_gate(input_data, tool_use_id, context):
        # PostToolUse: non-blocking format + lint feedback, exactly like
        # the shell gate (it never denies; empty commands are no-ops,
        # mirroring the shell's interpolated `true`).
        proj = _proj()
        msgs = []
        if fmt:
            r = subprocess.run(fmt, shell=True, cwd=proj,
                               capture_output=True, text=True)
            if r.returncode != 0:
                msgs.append("format reported issues")
        if lint:
            r = subprocess.run(lint, shell=True, cwd=proj,
                               capture_output=True, text=True)
            tail = "\\n".join(
                (r.stdout + r.stderr).splitlines()[-20:]).strip()
            if tail:
                msgs.append(tail)
        if msgs:
            return {"systemMessage": "\\n".join(msgs)}
        return {}
    return format_lint_gate


_GATE_FACTORIES = {
    "secrets-gate": _secrets_gate,
    "spec-gate-commit": _spec_gate_commit,
    "dependency-gate": _dependency_gate,
    "test-gate": _test_gate,
    "eval-gate": _eval_gate,
    "tdd-gate": _tdd_gate,
    "format-lint-gate": _format_lint_gate,
}
# Event/matcher per gate - mirrors the shell suite's settings.json wiring
# (templates.HOOK_EVENT_MAP); tests assert the two stay in sync.
_GATE_MATCHERS = {
    "secrets-gate": ("PreToolUse", "Read|Write|Edit"),
    "spec-gate-commit": ("PreToolUse", "Bash"),
    "dependency-gate": ("PreToolUse", "Bash"),
    "test-gate": ("PreToolUse", "Bash"),
    "eval-gate": ("PreToolUse", "Bash"),
    "tdd-gate": ("PreToolUse", "Write"),
    "format-lint-gate": ("PostToolUse", "Write|Edit"),
}
# Command-running gates get explicit generous timeouts. At the seam
# runtime floor (Claude Code >= 2.1.210) a PreToolUse hook timeout fails
# CLOSED - the tool call is blocked - so a timeout is a refusal, never a
# silent allow.
_GATE_TIMEOUTS = {"test-gate": 600.0, "format-lint-gate": 120.0}


def build_hooks(config: dict) -> dict:
    """The single public builder (seam §9): resolved project config in,
    Agent SDK hooks mapping out. Fail-loud: a malformed config raises,
    it never degrades to a smaller gate set."""
    if not isinstance(config, dict):
        raise TypeError("build_hooks: config must be the resolved "
                        "project config dict")
    missing = [k for k in ("secrets", "deps", "commands")
               if k not in config]
    if missing:
        raise KeyError(f"build_hooks: resolved config missing {missing}")
    out: dict = {}
    for name in GATES:
        event, matcher = _GATE_MATCHERS[name]
        kwargs = {}
        if name in _GATE_TIMEOUTS:
            kwargs["timeout"] = _GATE_TIMEOUTS[name]
        out.setdefault(event, []).append(HookMatcher(
            matcher=matcher,
            hooks=[_GATE_FACTORIES[name](config)],
            **kwargs))
    return out
'''


def sdk_gates_module(cfg: dict) -> str:
    """Render .claude/sdk_gates/gates.py for this resolved config.

    Only the two literals below are config-derived; the gate logic is
    static (and therefore syntax-checkable in isolation). json.dumps
    output for pure str/list/dict data is valid Python literal syntax.
    """
    gates = [h for h in cfg["_resolved_hooks"] if h in SDK_GATES]
    resolved = {
        "secrets": {"never_read_paths":
                    list(cfg["secrets"]["never_read_paths"])},
        "deps": {"approved": list(cfg["deps"]["approved"])},
        "commands": {k: (cfg["commands"].get(k) or "")
                     for k in ("test", "lint", "format")},
    }
    dynamic = (
        "# The gates enabled for THIS project (emission-time subset of the\n"
        "# resolved hook set; parity with the installed shell suite).\n"
        f"GATES = {json.dumps(gates)}\n\n"
        "# Emission-time snapshot of the gate-relevant resolved config.\n"
        "# build_hooks(config) uses the config the CALLER passes (per the\n"
        "# seam-locked signature); this snapshot records what the installer\n"
        "# resolved at emission - digest-protected so drift between the two\n"
        "# is detectable - and serves SEV-1 use: build_hooks(RESOLVED_CONFIG).\n"
        f"RESOLVED_CONFIG = {json.dumps(resolved, indent=4)}\n"
    )
    return _HEADER + dynamic + _STATIC_BODY
