"""R-7 (IC-5) - emitter for the project-resident SDK gate module.

[SR-11] Deliberate deviation from the single-templates.py convention,
CONFIRMED at implementation (recorded in docs/changelog.md): this module
emits Python-from-Python, and a separate file keeps the emitted source
syntax-checkable (tests ast.parse the rendered output) without entangling
templates.py's shell-heredoc escaping conventions.

The emitted module is contract surface (seam §9, locked): single public
builder `build_hooks(config)`, no I/O at import time, no network I/O ever,
subprocess-only loading, security-critical hand-edit tier. Refusal reason
strings are semantically equivalent to the shell gates' messages (seam
§6.2 obliges consumers to relay them faithfully); tests/test_sdk_gates.py
asserts each reason literal against the emitted shell hook bodies
(AC-7-5), modulo the documented interpolation sites.
"""
from __future__ import annotations

import json

# The seven gates the SDK substrate carries (R-7). ci-mirror and the
# observability hooks stay shell-only; SessionStart/SessionEnd-class events
# have no Python-SDK HookEvent and remain shell (AC-7-3).
#
# [upstream P2-2] This is a SUBSET, not parity. `git push` has no gate here
# at all. Do not describe this module as equivalent to the shell suite.
#
# [upstream P2-3] WHEN THIS MODULE IS LIVE: only when the install resolved
# `gate_substrate: "sdk-callable"` AND the consumer runtime calls
# build_hooks(). On a `gate_substrate: "shell"` install the file is still
# emitted but NOTHING references it - `grep -c sdk_gates .claude/settings.json`
# returns 0 - so it enforces nothing. That is intended, but it was never
# stated, and a reader reasonably assumes an emitted gate module is active.
SDK_GATES = (
    "secrets-gate", "spec-gate-commit", "dependency-gate", "test-gate",
    "eval-gate", "tdd-gate", "format-lint-gate",
)

_HEADER = '''"""Bootstrap Protocol SDK gate module (seam §9; protocol >= 2.1.0).

Generated by bootstrap-installer. Edit with care - security-relevant.
This file is manifest-tracked at the SECURITY-CRITICAL hand-edit tier: a
digest mismatch refuses dispatch until reverted or explicitly, auditably
overridden (seam §7.2).

Contract (seam §9, locked):
- Exactly one public builder: build_hooks(config) -> {"PreToolUse":
  [HookMatcher, ...], ...}. Everything else here is private.
- No I/O at import time; no network I/O ever.
- Loaded ONLY inside a subprocess dispatch runner (consumer-owned, e.g.
  Tessera's). Importing this module into a consumer's core process
  violates the seam §2 non-import rule.
- A refusal returns the structured PreToolUse deny shape (seam §4.1 /
  §6.2) with a reason string semantically equivalent to the shell
  gate's message; consumers relay it faithfully.

The full shell hook suite remains installed alongside this module as the
SEV-1 manual path (seam §7.5); this module does not replace it.
"""
from __future__ import annotations

import asyncio
import fnmatch
import os
import re
from pathlib import Path

from claude_agent_sdk import HookMatcher

__all__ = ["build_hooks"]


async def _run(cmd, *, cwd, shell, merge=False):
    """Run a subprocess WITHOUT blocking the SDK event loop. Hook
    callbacks are awaited directly on the consumer's single-threaded
    asyncio loop (no executor), so a synchronous subprocess.run would
    freeze every other task - stream pumping, other hooks, the very
    cancellation the HookMatcher timeout relies on - for the whole child
    lifetime. Returns (returncode, stdout, stderr) as decoded text; when
    merge=True, stderr is folded into stdout in chronological order (as
    the shell gate's `2>&1` does) and the returned stderr is empty."""
    err_dst = (asyncio.subprocess.STDOUT if merge
               else asyncio.subprocess.PIPE)
    if shell:
        proc = await asyncio.create_subprocess_shell(
            cmd, cwd=str(cwd),
            stdout=asyncio.subprocess.PIPE, stderr=err_dst)
    else:
        proc = await asyncio.create_subprocess_exec(
            *cmd, cwd=str(cwd),
            stdout=asyncio.subprocess.PIPE, stderr=err_dst)
    out, err = await proc.communicate()
    return (proc.returncode,
            (out or b"").decode(errors="replace"),
            (err or b"").decode(errors="replace"))

'''

_STATIC_BODY = '''

def _proj() -> Path:
    # Same project-root resolution as the shell suite (F-2 idiom).
    # Resolved to an ABSOLUTE path so path-relative logic (tdd-gate) is
    # computed against a stable root rather than the runner's cwd. The
    # consumer's subprocess runner is expected to set CLAUDE_PROJECT_DIR
    # (seam §9); absent it, this falls back to the resolved cwd.
    return Path(os.environ.get("CLAUDE_PROJECT_DIR") or ".").resolve()


def _deny(reason: str) -> dict:
    return {"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason,
    }}


def _tool_input(input_data) -> dict:
    ti = (input_data or {}).get("tool_input")
    return ti if isinstance(ti, dict) else {}


def _norm_pat(pat):
    # Normalize a shell-case deny-list glob into an fnmatch pattern that
    # preserves DENY-LIST BIAS (over-match, never under-match): '**'->'*'
    # (fnmatch has no '**'), and bash negated classes '[^...]' -> fnmatch
    # '[!...]' (fnmatch reads '[^' as a POSITIVE class containing '^',
    # which under-matches - the T-1 fail-open this closes). Lowercased for
    # case-insensitive matching.
    return pat.replace("**", "*").replace("[^", "[!").lower()


def _secrets_gate(config):
    # Precompute the normalized pattern once (config-constant) rather than
    # per PreToolUse event - this is the hottest matcher in a session.
    patterns = [(p, _norm_pat(p))
                for p in config["secrets"]["never_read_paths"] if p]

    async def secrets_gate(input_data, tool_use_id, context):
        # Hard-block never-read paths. Blocks mid-plan by design (secret
        # exposure is catastrophic). Deny-list bias: over-match, never
        # under-match (shell T-1 semantics) - each pattern is tried
        # as-given AND with an implicit leading '*', case-insensitively,
        # against both basename and full path.
        # [upstream P0-2/P2-4] Every tool surface that can reach a file,
        # not just file_path. NotebookEdit supplies notebook_path and was
        # already matched by the old matcher substring while the path key
        # went unread - the gate reported success while checking nothing.
        ti = _tool_input(input_data)
        targets = [ti.get(k) or ""
                   for k in ("file_path", "notebook_path", "path", "pattern")]
        targets = [t for t in targets if t]
        if not targets:
            return {}
        for target in targets:
            deny = _match_secret(target, patterns)
            if deny:
                return deny
        return {}

    return secrets_gate


def _match_secret(target, patterns):
    # [upstream P2-4] Mirrors the shell's three-form matching exactly.
    # '*.pem'-style patterns keep the implicit leading '*' (free). The
    # '.env*' dotenv family is matched on a DOT-SEGMENT boundary so
    # config.env / prod.env still block (shell T-1) while my.envelope.gleam
    # and dev.environment.md no longer false-block mid-plan. Everything else
    # ('secrets/*') is path-segment anchored.
    base = os.path.basename(target).lower()
    full = target.lower()
    for pat, cpat in patterns:
        stem = cpat[:-1] if cpat.endswith("*") else cpat
        if cpat.startswith("*"):
            hit = (fnmatch.fnmatchcase(base, cpat)
                   or fnmatch.fnmatchcase(base, "*" + cpat)
                   or fnmatch.fnmatchcase(full, cpat)
                   or fnmatch.fnmatchcase(full, "*/" + cpat)
                   or fnmatch.fnmatchcase(full, "*" + cpat))
        elif cpat.startswith("."):
            hit = (fnmatch.fnmatchcase(base, cpat)
                   or fnmatch.fnmatchcase(base, "*" + stem)
                   or fnmatch.fnmatchcase(base, "*" + stem + ".*")
                   or fnmatch.fnmatchcase(full, cpat)
                   or fnmatch.fnmatchcase(full, "*/" + cpat))
        else:
            hit = (fnmatch.fnmatchcase(base, cpat)
                   or fnmatch.fnmatchcase(full, cpat)
                   or fnmatch.fnmatchcase(full, "*/" + cpat))
        if hit:
            return _deny(f"BLOCKED: {target} matches never-read "
                         f"pattern {pat}")
    return {}


def _spec_gate_commit(config):
    async def spec_gate_commit(input_data, tool_use_id, context):
        # Block `git commit` of staged files not referenced by an active
        # spec. Word-boundary match on path or basename (shell S-3
        # semantics), never a loose substring.
        cmd = _tool_input(input_data).get("command") or ""
        if not _git_verb(cmd, "commit"):
            return {}
        proj = _proj()
        try:
            _, staged_raw, _ = await _run(
                ["git", "diff", "--cached", "--name-only"],
                cwd=proj, shell=False)
        except OSError:
            staged_raw = ""            # mirrors shell `2>/dev/null || true`
        staged = [f for f in staged_raw.splitlines() if f.strip()]
        if not staged:
            return {}
        corpus_files = []
        index = proj / ".claude" / "specs" / "INDEX.md"
        if index.is_file():
            corpus_files.append(index)
        specs_dir = proj / ".claude" / "specs"
        # Skip dot-dirs/dotfiles so the corpus matches the shell globs
        # `specs/*/tasks/` and `"$d"*` (which never expand dot-entries) -
        # a Python glob superset would let commits pass the shell blocks.
        for tasks_dir in sorted(specs_dir.glob("*/tasks")):
            if tasks_dir.is_dir() and not tasks_dir.parent.name.startswith("."):
                corpus_files.extend(
                    p for p in sorted(tasks_dir.iterdir())
                    if p.is_file() and not p.name.startswith("."))
        if not corpus_files:
            return _deny("Commit blocked: no active spec/task files exist "
                         "yet.\\nRun /spec-new before committing.")
        corpus = "\\n".join(
            p.read_text(errors="replace") for p in corpus_files)
        miss = ""
        for f in staged:
            b = os.path.basename(f)
            # [^\\w./-] mirrors the shell class [^[:alnum:]_./-].
            pat = re.compile(
                r"(^|[^\\w./-])(" + re.escape(f) + "|" + re.escape(b)
                + r")([^\\w-]|$)", re.M)
            if not pat.search(corpus):
                miss += " " + f
        if miss:
            return _deny("Commit blocked: files not referenced by any "
                         "active spec:" + miss
                         + "\\nRun /spec-new or add them to a tasks/*.md "
                           "file.")
        return {}
    return spec_gate_commit


# [upstream P2-1, decision recorded] CANONICAL SUBSTRATE = THE SHELL SUITE.
# The shell is the default gate_substrate, ships on every install, and
# carries 11 gates to this module's 7. The binding rule is therefore: this
# module MUST NOT allow what the shell blocks, and MUST NOT block what the
# shell allows. Where the two disagreed, five dependency cases the shell
# allowed this module denied, and the reverse held on commits - so whichever
# substrate was live changed project behavior completely.
#
# [upstream P1-4 port] Matching is anchored to COMMAND POSITION, not a bare
# substring. `"git commit" not in cmd` had the identical weakness as the
# shell's `case *"git commit"*`: it missed `git  commit`, a tab,
# `git --no-pager commit` and `git -C /repo commit`, and it fired on the
# string appearing in a comment, a quoted argument or a grep pattern.
_GIT_VERB_TMPL = (r"(?:^|[;&|(])\\s*(?:env\\s+)?git"
                  r"(?:\\s+-[Cc]\\s+\\S+|\\s+-\\S+)*\\s+%s(?:\\s|$)")


def _git_verb(cmd, verb):
    """True if `cmd` invokes `git <verb>` at a command position."""
    return re.search(_GIT_VERB_TMPL % verb, cmd) is not None


_TOOLS = (r"npm|pnpm|yarn|bun|pip[0-9.]*|pipx|poetry|uv|pipenv|cargo|gem"
          r"|composer|mix|rebar3|gleam|go|deno")
_VERBS = r"install|i|add|get|require|get-deps|deps\\.get"
_INSTALL_VERBS = re.compile(
    r"(?:^|[;&|(])\\s*(?:env\\s+)?"
    r"(?:python[0-9.]*\\s+-m\\s+pip\\s+install|(?:" + _TOOLS + r")\\s+(?:"
    + _VERBS + r"))(?:\\s|$)")
# Remote-script execution: same "unapproved software arrives" class, with no
# inspectable package name, so it is always denied (shell parity).
_PIPE_TO_SHELL = re.compile(
    r"(?:curl|wget)[^;&|]*\\|\\s*(?:sudo\\s+)?"
    r"(?:sh|bash|zsh|python3?|perl|ruby)(?:\\s|$)")
_VALUE_FLAGS = frozenset({
    "-r", "--requirement", "-e", "--editable", "-c", "--constraint",
    "-t", "--target", "--prefix", "--root", "-d", "--dest",
})


def _pkg_name(tok):
    # Package name minus version/spec. npm SCOPED packages start with '@'
    # (@scope/pkg[@ver]); splitting on '@' first would blank the whole
    # token and fail open, so the leading scope '@' is preserved and only
    # a LATER version separator is stripped.
    if tok.startswith("@"):
        return "@" + re.split(r"[<>=@~ ]", tok[1:], maxsplit=1)[0]
    return re.split(r"[<>=@~ ]", tok, maxsplit=1)[0]


def _dependency_gate(config):
    approved = set(config["deps"]["approved"])

    async def dependency_gate(input_data, tool_use_id, context):
        # Block package installs not on the approved list. Every token
        # after the install/add verb is inspected (shell S-2 semantics);
        # value-taking flags consume the next token. Spaces/tabs are
        # collapsed so tab-separated or multi-space invocations (and
        # `python -m pip install`) cannot slip past the verb match -
        # but NEWLINES are preserved (collapsing them would merge a
        # multi-line command whose message merely mentions an install
        # verb across a line break, false-blocking a legitimate commit).
        cmd = _tool_input(input_data).get("command") or ""
        blocked = ""
        for line in cmd.splitlines() or [cmd]:
            blocked += _scan_install_line(line, approved)
        if blocked:
            return _deny("Dependency gate: not in deps.md approved list:"
                         + blocked
                         + "\\nApprove in-session and update "
                           ".claude/steering/deps.md.")
        return {}
    return dependency_gate


def _scan_install_line(line, approved):
    # Returns a space-prefixed string of unapproved package names on this
    # single command line (empty if none / not an install command).
    norm = " " + re.sub(r"[ \\t]+", " ", line).strip() + " "
    if _PIPE_TO_SHELL.search(norm):
        return " <piped-remote-script>"
    m = _INSTALL_VERBS.search(norm)
    if not m:
        return ""
    # Stop at the next command separator: a following `&& something` is not
    # a package list. A verb with no arguments is a lockfile restore
    # (`npm install`), not an install of anything to approve. Shell parity.
    rest = re.split(r"[;&|]", norm[m.end():], maxsplit=1)[0]
    if not rest.strip():
        return ""
    blocked = ""
    skip_next = False
    for tok in rest.split():
        if skip_next:
            skip_next = False
            continue
        if tok in ("-r", "--requirement", "-c", "--constraint"):
            # Packages listed in a FILE are invisible to the gate; allowing
            # them would defeat it entirely. Shell parity.
            return " <unverifiable-requirements-file>"
        if tok in _VALUE_FLAGS:
            skip_next = True
            continue
        if tok == "." or tok.startswith(("./", "/", "../")):
            continue                      # local path install, not a registry
        if tok.startswith("-"):
            continue
        name_only = _pkg_name(tok)
        if name_only and name_only not in approved:
            blocked += " " + name_only
    return blocked


def _test_gate(config):
    test_cmd = (config["commands"].get("test") or "").strip()

    async def test_gate(input_data, tool_use_id, context):
        # Block `git commit` unless tests passed since the last source
        # edit (mark file .claude/.last-test-pass, as in the shell gate).
        cmd = _tool_input(input_data).get("command") or ""
        if not _git_verb(cmd, "commit"):
            return {}
        proj = _proj()
        mark = proj / ".claude" / ".last-test-pass"
        stale = True
        if mark.is_file():
            m_mtime = mark.stat().st_mtime
            # Source lives under src/ OR lib/ (parity with tdd_gate's
            # source definition); a lib/-only project must still
            # invalidate the mark on edits.
            stale = False
            for sub in ("src", "lib"):
                d = proj / sub
                if d.is_dir() and any(
                        p.is_file() and p.stat().st_mtime > m_mtime
                        for p in d.rglob("*")):
                    stale = True
                    break
        if not stale:
            return {}
        if not test_cmd:
            # fail-loud-on-empty-commands: parity with the shell
            # interpolation site "echo 'TODO: commands.test unset' &&
            # exit 1" (AC-7-2) - deny, never allow-by-omission.
            return _deny("TODO: commands.test unset\\n"
                         "Commit blocked: test command not found (exit 127)")
        rc, _, _ = await _run(test_cmd, cwd=proj, shell=True)
        if rc == 0:
            mark.parent.mkdir(parents=True, exist_ok=True)
            mark.touch()
            return {}
        return _deny("Commit blocked: tests failing (exit %d)." % rc)
    return test_gate


def _eval_gate(config):
    async def eval_gate(input_data, tool_use_id, context):
        # Block `git push` touching prompt files unless an eval passed
        # (mark file .claude/.last-eval-pass, as in the shell gate).
        cmd = _tool_input(input_data).get("command") or ""
        if not _git_verb(cmd, "push"):
            return {}
        proj = _proj()
        # Inspect the WHOLE outgoing range, not just the newest commit:
        # a push can carry many commits, and a prompt change two commits
        # back must still gate. Prefer @{u}..HEAD (what will actually be
        # pushed); fall back to HEAD~1 when no upstream is configured.
        diff = ""
        for rng in ("@{u}..HEAD", "HEAD~1"):
            try:
                rc, out, _ = await _run(
                    ["git", "diff", "--name-only", rng],
                    cwd=proj, shell=False)
            except OSError:
                rc, out = 1, ""        # mirrors shell `2>/dev/null`
            if rc == 0:
                diff = out
                break
        if not re.search(r"prompt|\\.md$", diff, re.M):
            return {}
        if (proj / ".claude" / ".last-eval-pass").is_file():
            return {}
        return _deny("Eval gate: run evals before pushing prompt "
                     "changes.")
    return eval_gate


def _tdd_gate(config):
    async def tdd_gate(input_data, tool_use_id, context):
        # Block a Write to source unless a matching test was edited more
        # recently than the target. A nonexistent target denies (parity
        # with the shell `find -newer` failing on a missing reference):
        # the gate's contract is test-first even for new source files.
        raw = _tool_input(input_data).get("file_path") or ""
        if not raw:
            return {}
        proj = _proj()
        # Claude Code passes ABSOLUTE file paths; normalize to project-
        # relative before the src/|lib/ test (a bare re.match on an
        # absolute path never matches, silently disabling the gate).
        if os.path.isabs(raw):
            try:
                rel = os.path.relpath(raw, proj)
            except ValueError:         # different drive (Windows) - give up
                return {}
        else:
            rel = raw
        if not re.match(r"(src|lib)/", rel):
            return {}
        stem = os.path.basename(rel)
        stem = stem.rsplit(".", 1)[0] if "." in stem else stem
        tpath = proj / rel
        newer = False
        if tpath.is_file():
            t_mtime = tpath.stat().st_mtime
            tests_dir = proj / "tests"
            if tests_dir.is_dir():
                newer = any(
                    p.is_file() and p.stat().st_mtime > t_mtime
                    for p in tests_dir.rglob(f"*{stem}*"))
        if not newer:
            return _deny(f"TDD gate: write a failing test for {stem} "
                         f"before {rel}.")
        return {}
    return tdd_gate


def _format_lint_gate(config):
    # [upstream P2-6] commands.format is deliberately NOT read here.
    lint = (config["commands"].get("lint") or "").strip()

    async def format_lint_gate(input_data, tool_use_id, context):
        # PostToolUse: non-blocking format + lint feedback, exactly like
        # the shell gate (it never denies; empty commands are no-ops,
        # mirroring the shell's interpolated `true`).
        # [upstream P2-6] The FORMAT command is no longer run here. It is
        # a mutating command with no file-type filter, so it reformatted
        # files the agent never touched, project-wide, on every edit - a
        # PostToolUse hook must not rewrite the tree behind the operator.
        # Lint only; it reports and never mutates. Shell parity.
        proj = _proj()
        msgs = []
        if lint:
            # merge=True mirrors the shell's `2>&1 | tail -20`: the last 20
            # lines of the CHRONOLOGICALLY interleaved stream, not stdout-
            # then-stderr (which would reorder an interleaved summary).
            _, out, _ = await _run(lint, cwd=proj, shell=True, merge=True)
            tail = "\\n".join(out.splitlines()[-20:]).strip()
            if tail:
                msgs.append(tail)
        if msgs:
            return {"systemMessage": "\\n".join(msgs)}
        return {}
    return format_lint_gate


_GATE_FACTORIES = {
    "secrets-gate": _secrets_gate,
    "spec-gate-commit": _spec_gate_commit,
    "dependency-gate": _dependency_gate,
    "test-gate": _test_gate,
    "eval-gate": _eval_gate,
    "tdd-gate": _tdd_gate,
    "format-lint-gate": _format_lint_gate,
}
# Event/matcher per gate - mirrors the shell suite's settings.json wiring
# (templates.HOOK_EVENT_MAP); tests assert the two stay in sync.
_GATE_MATCHERS = {
    "secrets-gate": ("PreToolUse", "Read|Write|Edit|NotebookEdit|Grep|Glob"),
    "spec-gate-commit": ("PreToolUse", "Bash"),
    "dependency-gate": ("PreToolUse", "Bash"),
    "test-gate": ("PreToolUse", "Bash"),
    "eval-gate": ("PreToolUse", "Bash"),
    "tdd-gate": ("PreToolUse", "Write"),
    "format-lint-gate": ("PostToolUse", "Write|Edit"),
}
# Command-running gates get explicit generous timeouts. At the seam
# runtime floor (Claude Code >= 2.1.210) a PreToolUse hook timeout fails
# CLOSED - the tool call is blocked - so a timeout is a refusal, never a
# silent allow.
_GATE_TIMEOUTS = {"test-gate": 600.0, "format-lint-gate": 120.0}


# Canonical order of the SDK-carried gate universe (insertion order of
# the factory table). build_hooks derives MEMBERSHIP from the caller's
# config in this order, never from a stale frozen list.
_GATE_ORDER = tuple(_GATE_FACTORIES)


def _enabled_gates(config):
    # Membership tracks the CALLER's config, not the emission-time GATES
    # snapshot: a config that now warrants more gates than at emission
    # (tdd_policy flipped to required, eval-gate turned on) gets them. A
    # config carrying a NON-EMPTY `_resolved_hooks` (a full resolved
    # project config, e.g. Tessera's or the emitted RESOLVED_CONFIG) is
    # authoritative. A missing OR EMPTY `_resolved_hooks` falls back to
    # the emission-time GATES - never to the empty set: a security
    # substrate silently building ZERO gates from a stray `[]` would be
    # the opposite of fail-loud. (When the project genuinely enables no
    # SDK gates, GATES itself is empty, so the result is still empty.)
    hooks = config.get("_resolved_hooks")
    if hooks:
        active = set(hooks)
        return [g for g in _GATE_ORDER if g in active]
    return [g for g in _GATE_ORDER if g in set(GATES)]


def build_hooks(config: dict) -> dict:
    """The single public builder (seam §9): resolved project config in,
    Agent SDK hooks mapping out. Fail-loud: a malformed config raises,
    and gate membership follows the passed config (never a stale
    emission-time set)."""
    if not isinstance(config, dict):
        raise TypeError("build_hooks: config must be the resolved "
                        "project config dict")
    missing = [k for k in ("secrets", "deps", "commands")
               if k not in config]
    if missing:
        raise KeyError(f"build_hooks: resolved config missing {missing}")
    out: dict = {}
    for name in _enabled_gates(config):
        event, matcher = _GATE_MATCHERS[name]
        kwargs = {}
        if name in _GATE_TIMEOUTS:
            kwargs["timeout"] = _GATE_TIMEOUTS[name]
        out.setdefault(event, []).append(HookMatcher(
            matcher=matcher,
            hooks=[_GATE_FACTORIES[name](config)],
            **kwargs))
    return out
'''


def sdk_gates_module(cfg: dict) -> str:
    """Render .claude/sdk_gates/gates.py for this resolved config.

    Only the two literals below are config-derived; the gate logic is
    static (and therefore syntax-checkable in isolation). Leaf scalars are
    coerced to str so the json.dumps output is ALWAYS valid Python: a
    YAML-typed bool/None (minyaml turns unquoted true/false/null into
    Python bool/None, and resolve_config never type-checks these leaves)
    would otherwise render as `true`/`null` - valid JSON but undefined
    Python names, NameError-ing the whole module at import.
    """
    gates = [h for h in cfg["_resolved_hooks"] if h in SDK_GATES]
    resolved = {
        "secrets": {"never_read_paths":
                    [str(p) for p in cfg["secrets"]["never_read_paths"]]},
        "deps": {"approved": [str(x) for x in cfg["deps"]["approved"]]},
        "commands": {k: str(cfg["commands"].get(k) or "")
                     for k in ("test", "lint", "format")},
        # Carried so build_hooks(RESOLVED_CONFIG) derives the same gate
        # membership on the SEV-1 path that a live resolved config would.
        "_resolved_hooks": list(gates),
    }
    dynamic = (
        "# The gates enabled for THIS project at emission.\n"
        "#\n"
        "# [upstream P2-2] NOT parity with the shell suite - the\n"
        "# earlier claim of parity was false. 7 gates here; 11 in the\n"
        "# shell suite. Shell-only, ABSENT here: ci-mirror (so\n"
        "# `git push` is UNGATED under SDK dispatch), drift-detector,\n"
        "# cost-log, task-done-alarm, decision-required-alarm,\n"
        "# spec-gate-entry. The shell suite is canonical; this module\n"
        "# is a consistent SUBSET of it.\n"
        f"GATES = {json.dumps(gates)}\n\n"
        "# Emission-time snapshot of the gate-relevant resolved config.\n"
        "# build_hooks(config) uses the config the CALLER passes (per the\n"
        "# seam-locked signature); this snapshot records what the installer\n"
        "# resolved at emission - digest-protected so drift between the two\n"
        "# is detectable - and serves SEV-1 use: build_hooks(RESOLVED_CONFIG).\n"
        f"RESOLVED_CONFIG = {json.dumps(resolved, indent=4)}\n"
    )
    return _HEADER + dynamic + _STATIC_BODY
