"""R-7 (IC-5) - emitter for the project-resident SDK gate module.

[SR-11] Deliberate deviation from the single-templates.py convention,
CONFIRMED at implementation (recorded in docs/changelog.md): this module
emits Python-from-Python, and a separate file keeps the emitted source
syntax-checkable (tests ast.parse the rendered output) without entangling
templates.py's shell-heredoc escaping conventions.

The emitted module is contract surface (seam §9, locked): single public
builder `build_hooks(config)`, no I/O at import time, no network I/O ever,
subprocess-only loading, security-critical hand-edit tier. Refusal reason
strings are semantically equivalent to the shell gates' messages (seam
§6.2 obliges consumers to relay them faithfully); tests/test_sdk_gates.py
asserts each reason literal against the emitted shell hook bodies
(AC-7-5), modulo the documented interpolation sites.
"""
from __future__ import annotations

import json

# The seven gates the SDK substrate carries (R-7). ci-mirror and the
# observability hooks stay shell-only; SessionStart/SessionEnd-class events
# have no Python-SDK HookEvent and remain shell (AC-7-3).
#
# [upstream P2-2] This is a SUBSET, not parity. `git push` has no gate here
# at all. Do not describe this module as equivalent to the shell suite.
#
# [upstream P2-3] WHEN THIS MODULE IS LIVE: only when the install resolved
# `gate_substrate: "sdk-callable"` AND the consumer runtime calls
# build_hooks(). On a `gate_substrate: "shell"` install the file is still
# emitted but NOTHING references it - `grep -c sdk_gates .claude/settings.json`
# returns 0 - so it enforces nothing. That is intended, but it was never
# stated, and a reader reasonably assumes an emitted gate module is active.
SDK_GATES = (
    "secrets-gate", "spec-gate-commit", "dependency-gate", "test-gate",
    "eval-gate", "tdd-gate", "format-lint-gate",
)

_HEADER = '''"""Bootstrap Protocol SDK gate module (seam §9; protocol >= 2.1.0).

Generated by bootstrap-installer. Edit with care - security-relevant.
This file is manifest-tracked at the SECURITY-CRITICAL hand-edit tier: a
digest mismatch refuses dispatch until reverted or explicitly, auditably
overridden (seam §7.2).

Contract (seam §9, locked):
- Exactly one public builder: build_hooks(config) -> {"PreToolUse":
  [HookMatcher, ...], ...}. Everything else here is private.
- No I/O at import time; no network I/O ever.
- Loaded ONLY inside a subprocess dispatch runner (consumer-owned, e.g.
  Tessera's). Importing this module into a consumer's core process
  violates the seam §2 non-import rule.
- A refusal returns the structured PreToolUse deny shape (seam §4.1 /
  §6.2) with a reason string semantically equivalent to the shell
  gate's message; consumers relay it faithfully.

The full shell hook suite remains installed alongside this module as the
SEV-1 manual path (seam §7.5); this module does not replace it.
"""
from __future__ import annotations

import asyncio
import fnmatch
import os
import re
import shlex
from pathlib import Path

from claude_agent_sdk import HookMatcher

__all__ = ["build_hooks"]


async def _run(cmd, *, cwd, shell, merge=False):
    """Run a subprocess WITHOUT blocking the SDK event loop. Hook
    callbacks are awaited directly on the consumer's single-threaded
    asyncio loop (no executor), so a synchronous subprocess.run would
    freeze every other task - stream pumping, other hooks, the very
    cancellation the HookMatcher timeout relies on - for the whole child
    lifetime. Returns (returncode, stdout, stderr) as decoded text; when
    merge=True, stderr is folded into stdout in chronological order (as
    the shell gate's `2>&1` does) and the returned stderr is empty."""
    err_dst = (asyncio.subprocess.STDOUT if merge
               else asyncio.subprocess.PIPE)
    if shell:
        proc = await asyncio.create_subprocess_shell(
            cmd, cwd=str(cwd),
            stdout=asyncio.subprocess.PIPE, stderr=err_dst)
    else:
        proc = await asyncio.create_subprocess_exec(
            *cmd, cwd=str(cwd),
            stdout=asyncio.subprocess.PIPE, stderr=err_dst)
    out, err = await proc.communicate()
    return (proc.returncode,
            (out or b"").decode(errors="replace"),
            (err or b"").decode(errors="replace"))

'''

_STATIC_BODY = '''

def _proj() -> Path:
    # Same project-root resolution as the shell suite (F-2 idiom).
    # Resolved to an ABSOLUTE path so path-relative logic (tdd-gate) is
    # computed against a stable root rather than the runner's cwd. The
    # consumer's subprocess runner is expected to set CLAUDE_PROJECT_DIR
    # (seam §9); absent it, this falls back to the resolved cwd.
    return Path(os.environ.get("CLAUDE_PROJECT_DIR") or ".").resolve()


def _deny(reason: str) -> dict:
    return {"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason,
    }}


def _tool_input(input_data) -> dict:
    ti = (input_data or {}).get("tool_input")
    return ti if isinstance(ti, dict) else {}


def _norm_pat(pat):
    # Normalize a shell-case deny-list glob into an fnmatch pattern that
    # preserves DENY-LIST BIAS (over-match, never under-match): '**'->'*'
    # (fnmatch has no '**'), and bash negated classes '[^...]' -> fnmatch
    # '[!...]' (fnmatch reads '[^' as a POSITIVE class containing '^',
    # which under-matches - the T-1 fail-open this closes). Lowercased for
    # case-insensitive matching.
    return pat.replace("**", "*").replace("[^", "[!").lower()


# Shell operators are not part of a word when unquoted, so they delimit
# path candidates: `cd secrets; cat prod.yaml` must yield `secrets`, not
# `secrets;`. shlex keeps them attached (it is not a shell parser), so they
# are split out here. Shell parity (the gate's _sg_raw).
_SH_OPS = re.compile(r"[;&|()<>]")
# A strictly-shaped assignment hides a path behind an expansion the gate
# cannot perform: `F=.env; cat $F`. The assignment itself is in plain sight.
_ASSIGN = re.compile(r"^[A-Za-z_]\\w*=(.*)$", re.S)
# [lens B finding 4] The ONE deliberate relaxation: dotenv TEMPLATE names are
# conventionally secret-free and committed, so `.env*` blocking
# `cat .env.example` blocks a file whose whole purpose is to be read. Exact
# basenames only, so `.env.production` and `.env.example.real` are untouched.
_DOTENV_TEMPLATES = frozenset({
    ".env.example", ".env.sample", ".env.template", ".env.dist",
    ".env.defaults", "env.example", "env.sample", "env.template",
})
# [round-2 review F-870] Shell parity: the gate's _sg_push carries the same
# two sets. A shell invoker's argument is a COMMAND LINE, not prose, so its
# quoted run is re-tokenized; every other command's quoted run stays one
# opaque candidate. Deciding this on WHO THE COMMAND IS - rather than on
# what the run looks like - is what lets `sh -c 'cat secrets/prod.yaml'`
# block while `git commit -m "fix the .env loader"` stays allowed.
_SHELL_INVOKERS = frozenset({
    "sh", "bash", "zsh", "dash", "ksh", "ash", "busybox", "ssh", "eval",
    "xargs",
})
# Transparent prefixes: they do not change WHICH program runs, so the next
# token is still the command word. Mirrors CMD_PFX in the shell header.
_CMD_PREFIXES = frozenset({
    "env", "sudo", "nohup", "time", "watch", "command", "exec", "builtin",
})


def _shell_segments(cmd):
    """Split on UNQUOTED operators and newlines -> the units at which a new
    command can begin.

    Quote-aware, so a `;` or a newline INSIDE a quoted argument does not
    start a new command. Two things depend on that:

      * command position, which the invoker rule keys on. shlex.split
        discards newlines along with every other whitespace run, so an
        `sh -c` on the second LINE of a command reached its token with the
        tracker already past command position, the invoker rule never
        fired, and the SDK would have allowed what the shell blocks - the
        exact direction this module's binding rule forbids.
      * not splitting quoted tokens on operators. The previous version ran
        _SH_OPS.split over every shlex token, so `git commit -m "refactor
        (parse .env) handling"` was torn into parts and denied while the
        shell allowed it. Operators are handled HERE, before quotes are
        removed, so a token that still contains one was quoted and is left
        whole.

    An unterminated quote takes the rest of the string as one segment,
    which is what the shell gate does.
    """
    segs, cur, quote = [], [], None
    for ch in cmd:
        if quote:
            cur.append(ch)
            if ch == quote:
                quote = None
        elif ch in ("'", '"'):
            quote = ch
            cur.append(ch)
        elif ch in ";&|()<>\\n":
            segs.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    segs.append("".join(cur))
    return [s for s in segs if s.strip()]


def _bash_candidates(cmd):
    # [lens A F1 / lens B finding 4] Tokenize the way the SHELL does: split
    # on UNQUOTED whitespace only, joining adjacent quoted and unquoted runs
    # into one token. A quoted argument is then ONE candidate (the words
    # inside a commit message are not paths), while `cat ".env"` still
    # yields `.env` and `cat .en''v` reassembles to `.env`. shlex.split in
    # POSIX mode is exactly that tokenizer, including backslash escapes and
    # multi-line input - the shell gate's hand-rolled equivalent exists only
    # because bash has no shlex.
    out = []
    for _seg in _shell_segments(cmd):
        out.extend(_segment_candidates(_seg))
    return out


def _segment_candidates(cmd):
    # One SEGMENT - operators and unquoted newlines already removed, so
    # every token here belongs to the same command and the first one is at
    # command position.
    try:
        toks = shlex.split(cmd, posix=True)
    except ValueError:
        # Unbalanced quote. shlex refuses; the shell gate takes the rest of
        # the line as the quoted run. Fall back to a whitespace split rather
        # than returning nothing - a parse failure must not become an allow.
        #
        # [v2.6.2] ...which is exactly what it DID become. A bare split
        # leaves the quote glued to the token, so `cat "secrets/prod.yaml`
        # yielded `"secrets/prod.yaml`, matched no pattern, and this
        # substrate ALLOWED what the shell blocked - the direction the
        # module's own binding rule forbids, in the fallback whose comment
        # promises the opposite. Emit the quote-stripped form as well; on a
        # parse failure the deny-list bias has to be over-match.
        toks = []
        for raw in cmd.split():
            toks.append(raw)
            stripped = raw.replace('"', "").replace("'", "")
            if stripped and stripped != raw:
                toks.append(stripped)
        # The fallback path did NOT go through _shell_segments' quote
        # tracking, so its tokens can still carry operators; those are the
        # only ones _SH_OPS is applied to now.
        toks = [p for raw in toks for p in _SH_OPS.split(raw) if p]
    out = []
    at_cmdpos = True
    invoker = False
    for tok in toks:
        out.append(tok)
        m = _ASSIGN.match(tok)
        if m and m.group(1):
            out.append(m.group(1))
        if at_cmdpos:
            base = tok.rsplit("/", 1)[-1]
            if base in _CMD_PREFIXES:
                pass                    # next token is still the command
            elif base in _SHELL_INVOKERS:
                invoker, at_cmdpos = True, False
            else:
                invoker, at_cmdpos = False, False
        # shlex splits on UNQUOTED whitespace, so a token that still
        # contains whitespace came from a quoted run - which is exactly the
        # set the invoker rule is about, with no extra bookkeeping. Additive:
        # the run stays a candidate too, because deny-list bias is
        # over-match. Shell parity: the gate's _sg_push, same condition.
        if invoker and any(c.isspace() for c in tok):
            out.extend(w for w in tok.split() if w)
    return out


def _secrets_gate(config):
    # Precompute the normalized pattern once (config-constant) rather than
    # per PreToolUse event - this is the hottest matcher in a session.
    patterns = [(p, _norm_pat(p))
                for p in config["secrets"]["never_read_paths"] if p]

    async def secrets_gate(input_data, tool_use_id, context):
        # Hard-block never-read paths. Blocks mid-plan by design (secret
        # exposure is catastrophic). Deny-list bias: over-match, never
        # under-match (shell T-1 semantics) - each pattern is tried
        # as-given AND with an implicit leading '*', case-insensitively,
        # against both basename and full path.
        # [upstream P0-2/P2-4] Every tool surface that can reach a file,
        # not just file_path. NotebookEdit supplies notebook_path and was
        # already matched by the old matcher substring while the path key
        # went unread - the gate reported success while checking nothing.
        # [lens A F7] ...and the Bash surface, which this module never
        # received. settings.json wired the shell gate to BOTH `Bash` and
        # the file matchers; _GATE_MATCHERS carried only the second, so
        # under `gate_substrate: "sdk-callable"` `cat .env`,
        # `grep -r . secrets/` and `cat deploy.pem` were entirely unguarded.
        # That is the original P0-2 finding, unfixed on this substrate,
        # while the table above claimed the two wirings were in sync.
        ti = _tool_input(input_data)
        # Structured path parameters and Bash-derived tokens are judged
        # apart: `dir_ok` says whether a bare directory NAME counts as
        # naming the directory, and that is true of a `path` parameter and
        # not of a word in a shell command. See _match_secret. Shell parity
        # (the gate's two-phase $_dir_ok loop).
        path_targets = [ti.get(k) or ""
                        for k in ("file_path", "notebook_path", "path",
                                  "pattern")]
        path_targets = [t for t in path_targets if t]
        cmd_targets = _bash_candidates(ti.get("command") or "")
        if not path_targets and not cmd_targets:
            return {}
        for targets, dir_ok in ((path_targets, True), (cmd_targets, False)):
            for target in targets:
                if os.path.basename(target).lower() in _DOTENV_TEMPLATES:
                    continue
                deny = _match_secret(target, patterns, dir_ok)
                if deny:
                    return deny
        return {}

    return secrets_gate


def _match_secret(target, patterns, dir_ok=True):
    # [upstream P2-4] Mirrors the shell's three-form matching exactly.
    # '*.pem'-style patterns keep the implicit leading '*' (free). The
    # '.env*' dotenv family is matched on a DOT-SEGMENT boundary so
    # config.env / prod.env still block (shell T-1) while my.envelope.gleam
    # and dev.environment.md no longer false-block mid-plan. Everything else
    # ('secrets/*') is path-segment anchored.
    base = os.path.basename(target).lower()
    full = target.lower()
    for pat, cpat in patterns:
        stem = cpat[:-1] if cpat.endswith("*") else cpat
        # [lens A F6, both substrates] 'secrets/**' normalizes to 'secrets/*',
        # which the anchored form matched only WITH the slash present, so
        # Grep{"path": "secrets"} allowed - and a Grep whose path is the
        # directory returns the matching file CONTENTS. Naming the directory
        # reaches everything under it. Empty for non-directory patterns.
        # [v2.6.2] Gated on dir_ok: applied to every candidate it made
        # `grep secrets README.md` and `git commit -m secrets` block, which
        # is lens B finding 4's failure mode reintroduced. Shell parity.
        dstem = cpat[:-2] if (dir_ok and cpat.endswith("/*")) else ""
        if cpat.startswith("*"):
            hit = (fnmatch.fnmatchcase(base, cpat)
                   or fnmatch.fnmatchcase(base, "*" + cpat)
                   or fnmatch.fnmatchcase(full, cpat)
                   or fnmatch.fnmatchcase(full, "*/" + cpat)
                   or fnmatch.fnmatchcase(full, "*" + cpat))
        elif cpat.startswith("."):
            hit = (fnmatch.fnmatchcase(base, cpat)
                   or fnmatch.fnmatchcase(base, "*" + stem)
                   or fnmatch.fnmatchcase(base, "*" + stem + ".*")
                   or fnmatch.fnmatchcase(full, cpat)
                   or fnmatch.fnmatchcase(full, "*/" + cpat))
        else:
            hit = (fnmatch.fnmatchcase(base, cpat)
                   or fnmatch.fnmatchcase(full, cpat)
                   or fnmatch.fnmatchcase(full, "*/" + cpat)
                   or bool(dstem) and (fnmatch.fnmatchcase(base, dstem)
                                       or fnmatch.fnmatchcase(full, dstem)
                                       or fnmatch.fnmatchcase(
                                           full, "*/" + dstem)))
        if hit:
            return _deny(f"BLOCKED: {target} matches never-read "
                         f"pattern {pat}")
    return {}


# [upstream P1-2, lens B finding 8] Enforcement is scoped to IMPLEMENTATION
# paths. The shell gate got this at v2.6.0 and this module did NOT - it still
# iterated every staged file - so under `gate_substrate: "sdk-callable"` the
# bootstrap commit was still impossible (the gate blocked its own
# `.claude/specs/INDEX.md`), which is the half of P1-2 the changelog reported
# as fixed. Same constant, same order, so the two substrates cannot drift.
_ENFORCED_PREFIXES = ("src/", "lib/", "app/", "test/", "tests/")


def _spec_gate_commit(config):
    async def spec_gate_commit(input_data, tool_use_id, context):
        # Block `git commit` of staged files not referenced by an active
        # spec. Word-boundary match on path or basename (shell S-3
        # semantics), never a loose substring.
        cmd = _tool_input(input_data).get("command") or ""
        if not _git_verb(cmd, "commit"):
            return {}
        proj = _proj()
        try:
            _, staged_raw, _ = await _run(
                ["git", "diff", "--cached", "--name-only"],
                cwd=proj, shell=False)
        except OSError:
            staged_raw = ""            # mirrors shell `2>/dev/null || true`
        staged = [f for f in staged_raw.splitlines() if f.strip()]
        if not staged:
            return {}
        staged = [f for f in staged
                  if f.startswith(_ENFORCED_PREFIXES)]
        if not staged:
            return {}
        corpus_files = []
        index = proj / ".claude" / "specs" / "INDEX.md"
        if index.is_file():
            corpus_files.append(index)
        specs_dir = proj / ".claude" / "specs"
        # Skip dot-dirs/dotfiles so the corpus matches the shell globs
        # `specs/*/tasks/` and `"$d"*` (which never expand dot-entries) -
        # a Python glob superset would let commits pass the shell blocks.
        for tasks_dir in sorted(specs_dir.glob("*/tasks")):
            if tasks_dir.is_dir() and not tasks_dir.parent.name.startswith("."):
                corpus_files.extend(
                    p for p in sorted(tasks_dir.iterdir())
                    if p.is_file() and not p.name.startswith("."))
        if not corpus_files:
            return _deny("Commit blocked: no active spec/task files exist "
                         "yet.\\nRun /spec-new before committing.")
        corpus = "\\n".join(
            p.read_text(errors="replace") for p in corpus_files)
        miss = ""
        for f in staged:
            b = os.path.basename(f)
            # [^\\w./-] mirrors the shell class [^[:alnum:]_./-].
            pat = re.compile(
                r"(^|[^\\w./-])(" + re.escape(f) + "|" + re.escape(b)
                + r")([^\\w-]|$)", re.M)
            if not pat.search(corpus):
                miss += " " + f
        if miss:
            return _deny("Commit blocked: files not referenced by any "
                         "active spec:" + miss
                         + "\\nRun /spec-new or add them to a tasks/*.md "
                           "file.")
        return {}
    return spec_gate_commit


# [upstream P2-1, decision recorded] CANONICAL SUBSTRATE = THE SHELL SUITE.
# The shell is the default gate_substrate, ships on every install, and
# carries 11 gates to this module's 7. The binding rule is therefore: this
# module MUST NOT allow what the shell blocks, and MUST NOT block what the
# shell allows. Where the two disagreed, five dependency cases the shell
# allowed this module denied, and the reverse held on commits - so whichever
# substrate was live changed project behavior completely.
#
# [lens A F7 / lens B finding 8] THAT RULE WAS ASSERTED AND NOT TRUE. At
# v2.6.0 it was violated in BOTH directions at once: this module allowed
# `cat .env` on the Bash surface (which the shell blocked, because
# _GATE_MATCHERS carried no Bash entry for secrets-gate), and it denied
# `python3 -m pip install evil` and a docs-only `git commit` (which the shell
# allowed, because ENFORCED_PREFIXES was never ported). Seven confirmed
# disagreements survived a commit message claiming "all 13 disputed cases now
# agree". The rule is now enforced by a TEST rather than by this comment:
# tests/test_substrate_differential.py pushes one payload corpus through the
# emitted shell hooks AND build_hooks(RESOLVED_CONFIG) and fails on any
# verdict that differs. Note what "canonical" means in the two cases where
# the SHELL was the weaker substrate (the chained-install fail-open, the
# unanchored eval-gate): reconcile to the shell's INTENT, never copy its bug.
#
# [upstream P1-4 port] Matching is anchored to COMMAND POSITION, not a bare
# substring. `"git commit" not in cmd` had the identical weakness as the
# shell's `case *"git commit"*`: it missed `git  commit`, a tab,
# `git --no-pager commit` and `git -C /repo commit`, and it fired on the
# string appearing in a comment, a quoted argument or a grep pattern.
_GIT_VERB_TMPL = (r"(?:^|[;&|(])\\s*(?:env\\s+)?git"
                  r"(?:\\s+-[Cc]\\s+\\S+|\\s+-\\S+)*\\s+%s(?:\\s|$)")


def _git_verb(cmd, verb):
    """True if `cmd` invokes `git <verb>` at a command position."""
    return re.search(_GIT_VERB_TMPL % verb, cmd) is not None


_TOOLS = (r"npm|pnpm|yarn|bun|pip[0-9.]*|pipx|poetry|uv|pipenv|cargo|gem"
          r"|composer|mix|rebar3|gleam|go|deno")
_VERBS = r"install|i|add|get|require|get-deps|deps\\.get"
# Command-position prefixes that do not change WHICH program runs, so the
# install verb is still the verb: `env`/`sudo` with their own flags, and one
# or more VAR=value assignment runs. Shell parity (the shell gate's PFX).
_PREFIX = r"(?:(?:env|sudo)(?:\\s+-\\S+)*\\s+|[A-Za-z_]\\w*=\\S*\\s+)*"
# An install invocation at the START of a segment - not merely present
# somewhere in it. The tool may carry a path (`/usr/bin/pip install`);
# `python -m pip install` and `uv pip install` are spelled out because the
# token at command position is not the installer. Shell parity (HEAD).
# [lens A F3 residue] Run-without-installing channels: `npx evil`, `uvx
# evil`, `pnpm dlx evil`, `bunx evil`, `npm exec evil`, `yarn dlx evil` all
# fetch and EXECUTE an unapproved package. Not installing it first is not a
# mitigation. NEWLY BLOCKED on both substrates. Shell parity (RUNNERS).
_RUNNERS = (r"(?:\\S*/)?(?:npx|uvx|bunx)"
            r"|(?:\\S*/)?(?:npm|pnpm|yarn|bun)\\s+(?:dlx|exec)")
_INSTALL_HEAD = re.compile(
    r"^\\s*" + _PREFIX
    + r"(?:python[0-9.]*\\s+-m\\s+pip\\s+install"
      r"|(?:\\S*/)?uv\\s+pip\\s+install"
      r"|" + _RUNNERS
    + r"|(?:\\S*/)?(?:" + _TOOLS + r")\\s+(?:" + _VERBS + r"))(?:\\s|$)")
# [lens A F3 residue] A package-index override redirects even an APPROVED
# package to another server, which no package-name check can see. Tested
# against the matched HEAD only - an assignment that is genuinely a
# command-position prefix of an install - so prose naming the variable does
# not block. Shell parity (_IDX_RE).
_INDEX_OVERRIDE = re.compile(
    r"(?:^|\\s)(?:PIP_INDEX_URL|PIP_EXTRA_INDEX_URL|PIP_FIND_LINKS"
    r"|UV_INDEX_URL|UV_EXTRA_INDEX_URL|NPM_CONFIG_REGISTRY"
    r"|npm_config_registry|YARN_REGISTRY|YARN_NPM_REGISTRY_SERVER"
    r"|COMPOSER_REPOSITORIES|GOPROXY|GEM_SOURCE)=")
# Shell separators. A line is split into segments and each is judged on its
# own; see _scan_install_line. Parens included so `(cd sub && pip install
# evil)` segments the same way the shell's cmd_segments does.
_SEGMENT = re.compile(r"[;&|()]")
# Remote-script execution: same "unapproved software arrives" class, with no
# inspectable package name, so it is always denied (shell parity).
_PIPE_TO_SHELL = re.compile(
    r"(?:curl|wget)[^;&|]*\\|\\s*(?:sudo\\s+)?"
    r"(?:sh|bash|zsh|python3?|perl|ruby)(?:\\s|$)")
# [lens A F9] Value-taking flags. The v2.6.0 list was seven entries long, so
# every other value-taking flag left its argument to be read as a package
# name and the gate blocked - naming the wrong token:
#   pip install --index-url <url> requests
#     -> "not in deps.md approved list: https://..."
# The list is long but the safety does not rest on its completeness: a flag
# consumes the following token ONLY IF that token is value-SHAPED. That
# inversion is what makes it safe to include short flags whose meaning
# differs by ecosystem - `npm install -f evil` and `npm install -d evil`
# must still block `evil`, and they do, because `evil` is package-shaped.
# Shell parity.
_VALUE_FLAGS = frozenset({
    "-i", "--index-url", "--extra-index-url", "--find-links", "--no-binary",
    "--only-binary", "--platform", "--python-version", "--implementation",
    "--abi", "--progress-bar", "--cache-dir", "--log", "--proxy", "--cert",
    "--client-cert", "--trusted-host", "--config-settings", "--report",
    "--timeout", "--retries", "--exists-action", "--upgrade-strategy",
    "--src", "-e", "--editable", "-t", "--target", "--prefix", "--root",
    "-d", "--dest", "--registry", "--userconfig", "--globalconfig",
    "--cache", "--workspace", "-w", "--omit", "--include",
    "--install-strategy", "--before", "--tag", "--scope", "--access",
    "--store-dir", "--virtual-store-dir", "--modules-folder", "--reporter",
    "--filter", "--dir", "-C", "--manifest-path", "--features", "--index",
    "--git", "--branch", "--rev", "--path", "-p", "--package", "--profile",
    "--bin", "--example", "--vers", "-f",
})
# [v2.6.2] See the shell gate's is_flag_value for the full account. The
# first version matched `=` and `^[0-9]` and therefore swallowed real
# package names - `7zip-bin`, `0x`, `2to3`, `evil==1.0` - as if they were
# flag values, installing them unapproved on BOTH substrates.
_FLAG_VALUE_SHAPE = re.compile(r"^$|://|^:|^\\.$|^\\./|^\\.\\./|^/|^~")
# `==` `>=` `<=` `~=` `!=` `<` `>` are pip/npm PACKAGE syntax, not flag
# values, and every one of them contains or implies `=`, so they are tested
# first.
_VERSION_SPEC = re.compile(r"==|>=|<=|~=|!=|<|>")
_BARE_VERSION = re.compile(r"^[0-9.]+$")


def _is_flag_value(tok):
    """True if `tok` could NOT be a package name and is therefore the
    preceding flag's value. Shell parity (is_flag_value)."""
    if _FLAG_VALUE_SHAPE.search(tok):
        return True
    if _VERSION_SPEC.search(tok):
        return False
    if "=" in tok:
        return True
    return bool(_BARE_VERSION.match(tok))


def _pkg_name(tok):
    # Package name minus version/spec. npm SCOPED packages start with '@'
    # (@scope/pkg[@ver]); splitting on '@' first would blank the whole
    # token and fail open, so the leading scope '@' is preserved and only
    # a LATER version separator is stripped.
    if tok.startswith("@"):
        return "@" + re.split(r"[<>=@~ ]", tok[1:], maxsplit=1)[0]
    return re.split(r"[<>=@~ ]", tok, maxsplit=1)[0]


def _dependency_gate(config):
    approved = set(config["deps"]["approved"])

    async def dependency_gate(input_data, tool_use_id, context):
        # Block package installs not on the approved list. Every token
        # after the install/add verb is inspected (shell S-2 semantics);
        # value-taking flags consume the next token. Spaces/tabs are
        # collapsed so tab-separated or multi-space invocations (and
        # `python -m pip install`) cannot slip past the verb match -
        # but NEWLINES are preserved (collapsing them would merge a
        # multi-line command whose message merely mentions an install
        # verb across a line break, false-blocking a legitimate commit).
        cmd = _tool_input(input_data).get("command") or ""
        blocked = ""
        for line in cmd.splitlines() or [cmd]:
            # [v2.6.2] _scan_install_line returns (reason, names). It used
            # to fold its three non-package refusals into the package-name
            # string, so a piped remote script, an unverifiable requirements
            # file and a package-index override all denied with
            # "not in deps.md approved list: <package-index-override>" and
            # told the operator to add that literal to deps.md - advice that
            # cannot work, for a refusal that has nothing to do with the
            # approved list. SEAM-CONTRACT §3.3 requires reason strings
            # "semantically equivalent to the shell gates'", and the shell
            # emits a distinct explanation for each of the three.
            reason, names = _scan_install_line(line, approved)
            if reason:
                return _deny(reason)
            blocked += names
        if blocked:
            return _deny("Dependency gate: not in deps.md approved list:"
                         + blocked
                         + "\\nApprove in-session and update "
                           ".claude/steering/deps.md.")
        return {}
    return dependency_gate


def _scan_install_line(line, approved):
    # Returns (reason, names): `reason` is a complete refusal message for
    # the three cases that are NOT about the approved list (and stops the
    # scan), `names` is a space-prefixed string of unapproved package names
    # on this single command line. Shell parity: the shell gate prints a
    # distinct two-line explanation for each of the three.
    norm = " " + re.sub(r"[ \\t]+", " ", line).strip() + " "
    # Checked on the WHOLE line and BEFORE segmenting: the pattern
    # deliberately reads across a pipe. Shell parity.
    if _PIPE_TO_SHELL.search(norm):
        return ("Dependency gate: piping a downloaded script into a shell "
                "is blocked.\\nVendor the installer, review it, then run it "
                "explicitly.", "")
    # SEGMENT FIRST, then judge each segment on its own. Searching the line
    # for ONE install invocation failed in both directions: `.search()` found
    # the FIRST, so `npm install requests && npm install evil` inspected only
    # `requests` and allowed - while the shell's greedy sed found the LAST and
    # allowed the mirror case. Neither substrate was safe on `A && B`. Making
    # the verdict the OR over segments fixes both and is what a deny-list
    # wants. Shell parity.
    blocked = ""
    for seg in _SEGMENT.split(norm):
        seg = seg.split(" #", 1)[0]       # a trailing comment is not a command
        m = _INSTALL_HEAD.match(seg)
        if not m:
            continue
        rest = seg[m.end():]
        if _INDEX_OVERRIDE.search(m.group(0)):
            return ("Dependency gate: a package-index override is not "
                    "verifiable.\\nIt redirects even an APPROVED package to "
                    "another server. Remove it,\\nor set the index in the "
                    "project's own package-manager config.", "")
        # A verb with no arguments is a lockfile restore (`npm install`), not
        # an install of anything to approve - but that is a fact about THIS
        # invocation, never about the line. Shell parity.
        if not rest.strip():
            continue
        skip_next = False
        for tok in rest.split():
            if skip_next:
                skip_next = False
                if _is_flag_value(tok):
                    continue
            if tok in ("-r", "--requirement", "-c", "--constraint"):
                # Packages listed in a FILE are invisible to the gate;
                # allowing them would defeat it entirely. Shell parity.
                return ("Dependency gate: cannot verify packages listed in "
                        "a file.\\nInstall them explicitly, or approve in "
                        ".claude/steering/deps.md.", "")
            if tok in _VALUE_FLAGS:
                skip_next = True
                continue
            if tok == "." or tok.startswith(("./", "/", "../")):
                continue                  # local path install, not a registry
            if tok.startswith("-"):
                continue
            name_only = _pkg_name(tok)
            if name_only and name_only not in approved:
                blocked += " " + name_only
    return (None, blocked)


def _test_gate(config):
    test_cmd = (config["commands"].get("test") or "").strip()

    async def test_gate(input_data, tool_use_id, context):
        # Block `git commit` unless the configured test command passes.
        #
        # [lens A F4] THE PASS MARKER IS GONE, on this substrate too. The
        # gate used to skip the run when `.claude/.last-test-pass` existed
        # and no source file was newer. That file is gitignored and
        # agent-writable and no gate protects it, so `touch
        # .claude/.last-test-pass` disabled the gate for the next commit.
        # Verifying its CONTENT is not a repair: whatever the gate can
        # compute from the tree, an agent holding a Write tool can compute
        # and write too. The only honest fix is to have no trusted input.
        # Removed with it: the src/-vs-lib/ staleness walk (and with it
        # backlog I-5, which was a divergence between two caches that no
        # longer exist).
        cmd = _tool_input(input_data).get("command") or ""
        if not _git_verb(cmd, "commit"):
            return {}
        proj = _proj()
        if not test_cmd:
            # fail-loud-on-empty-commands: parity with the shell
            # interpolation site "echo 'TODO: commands.test unset' >&2 &&
            # exit 127" (AC-7-2) - deny, never allow-by-omission.
            return _deny("TODO: commands.test unset\\n"
                         "Commit blocked: test command not found (exit 127)")
        rc, _, _ = await _run(test_cmd, cwd=proj, shell=True)
        if rc == 0:
            return {}
        if rc == 127:
            # Parity with the shell's P2-5 branch: the toolchain being
            # absent is not a red suite, and saying so sends the operator
            # to debug the wrong thing.
            return _deny("Commit blocked: test command not found (exit 127): "
                         + test_cmd)
        return _deny("Commit blocked: tests failing (exit %d)." % rc)
    return test_gate


def _eval_gate(config):
    async def eval_gate(input_data, tool_use_id, context):
        # Block `git push` touching prompt files unless an eval passed
        # (mark file .claude/.last-eval-pass, as in the shell gate).
        cmd = _tool_input(input_data).get("command") or ""
        if not _git_verb(cmd, "push"):
            return {}
        proj = _proj()
        # Inspect the WHOLE outgoing range, not just the newest commit:
        # a push can carry many commits, and a prompt change two commits
        # back must still gate. Prefer @{u}..HEAD (what will actually be
        # pushed); fall back to HEAD~1 when no upstream is configured.
        diff = ""
        for rng in ("@{u}..HEAD", "HEAD~1"):
            try:
                rc, out, _ = await _run(
                    ["git", "diff", "--name-only", rng],
                    cwd=proj, shell=False)
            except OSError:
                rc, out = 1, ""        # mirrors shell `2>/dev/null`
            if rc == 0:
                diff = out
                break
        if not re.search(r"prompt|\\.md$", diff, re.M):
            return {}
        if (proj / ".claude" / ".last-eval-pass").is_file():
            return {}
        return _deny("Eval gate: run evals before pushing prompt "
                     "changes.")
    return eval_gate


def _tdd_gate(config):
    async def tdd_gate(input_data, tool_use_id, context):
        # Block a Write to source unless a matching test was edited more
        # recently than the target. A nonexistent target denies (parity
        # with the shell `find -newer` failing on a missing reference):
        # the gate's contract is test-first even for new source files.
        raw = _tool_input(input_data).get("file_path") or ""
        if not raw:
            return {}
        proj = _proj()
        # Claude Code passes ABSOLUTE file paths; normalize to project-
        # relative before the src/|lib/ test (a bare re.match on an
        # absolute path never matches, silently disabling the gate).
        if os.path.isabs(raw):
            try:
                rel = os.path.relpath(raw, proj)
            except ValueError:         # different drive (Windows) - give up
                return {}
        else:
            rel = raw
        if not re.match(r"(src|lib)/", rel):
            return {}
        stem = os.path.basename(rel)
        stem = stem.rsplit(".", 1)[0] if "." in stem else stem
        tpath = proj / rel
        newer = False
        if tpath.is_file():
            t_mtime = tpath.stat().st_mtime
            tests_dir = proj / "tests"
            if tests_dir.is_dir():
                newer = any(
                    p.is_file() and p.stat().st_mtime > t_mtime
                    for p in tests_dir.rglob(f"*{stem}*"))
        if not newer:
            return _deny(f"TDD gate: write a failing test for {stem} "
                         f"before {rel}.")
        return {}
    return tdd_gate


def _format_lint_gate(config):
    # [upstream P2-6] commands.format is deliberately NOT read here.
    lint = (config["commands"].get("lint") or "").strip()

    async def format_lint_gate(input_data, tool_use_id, context):
        # PostToolUse: non-blocking format + lint feedback, exactly like
        # the shell gate (it never denies; empty commands are no-ops,
        # mirroring the shell's interpolated `true`).
        # [upstream P2-6] The FORMAT command is no longer run here. It is
        # a mutating command with no file-type filter, so it reformatted
        # files the agent never touched, project-wide, on every edit - a
        # PostToolUse hook must not rewrite the tree behind the operator.
        # Lint only; it reports and never mutates. Shell parity.
        proj = _proj()
        msgs = []
        if lint:
            # merge=True mirrors the shell's `2>&1 | tail -20`: the last 20
            # lines of the CHRONOLOGICALLY interleaved stream, not stdout-
            # then-stderr (which would reorder an interleaved summary).
            _, out, _ = await _run(lint, cwd=proj, shell=True, merge=True)
            tail = "\\n".join(out.splitlines()[-20:]).strip()
            if tail:
                msgs.append(tail)
        if msgs:
            return {"systemMessage": "\\n".join(msgs)}
        return {}
    return format_lint_gate


_GATE_FACTORIES = {
    "secrets-gate": _secrets_gate,
    "spec-gate-commit": _spec_gate_commit,
    "dependency-gate": _dependency_gate,
    "test-gate": _test_gate,
    "eval-gate": _eval_gate,
    "tdd-gate": _tdd_gate,
    "format-lint-gate": _format_lint_gate,
}
# PRIMARY event/matcher per gate - mirrors templates.HOOK_EVENT_MAP, which is
# the shell suite's settings.json wiring. One entry per gate, exactly as the
# shell table has, so the two can be compared for equality.
_GATE_MATCHERS = {
    "secrets-gate": ("PreToolUse", "Read|Write|Edit|NotebookEdit|Grep|Glob"),
    "spec-gate-commit": ("PreToolUse", "Bash"),
    "dependency-gate": ("PreToolUse", "Bash"),
    "test-gate": ("PreToolUse", "Bash"),
    "eval-gate": ("PreToolUse", "Bash"),
    "tdd-gate": ("PreToolUse", "Write"),
    "format-lint-gate": ("PostToolUse", "Write|Edit"),
}
# ADDITIONAL registrations for a gate that must guard more than one tool
# surface - the mirror of templates.HOOK_EXTRA_EVENTS, kept separate for the
# same reason: the seam §7.2 tier partition is keyed on gate NAME, one entry
# per gate, and must not be perturbed by a second matcher.
#
# [lens A F7] This table did not exist. settings.json registered the shell
# secrets-gate on BOTH `Bash` and the file matchers at v2.6.0 (P0-2), while
# the comment above claimed _GATE_MATCHERS "mirrors the shell suite's
# settings.json wiring; tests assert the two stay in sync" - it carried only
# the primary matcher, and the test that was supposed to assert the
# divergence checked a symbol (`_BASH_GATES`) that has never existed in this
# repo, so `getattr(..., {})` made it unconditionally true. Both the claim
# and its guard were empty. tests/test_sdk_gates.py now asserts this table
# against templates.HOOK_EXTRA_EVENTS by equality.
_GATE_EXTRA_MATCHERS = {
    "secrets-gate": [("PreToolUse", "Bash")],
}
# Command-running gates get explicit generous timeouts. At the seam
# runtime floor (Claude Code >= 2.1.210) a PreToolUse hook timeout fails
# CLOSED - the tool call is blocked - so a timeout is a refusal, never a
# silent allow.
_GATE_TIMEOUTS = {"test-gate": 600.0, "format-lint-gate": 120.0}


# Canonical order of the SDK-carried gate universe (insertion order of
# the factory table). build_hooks derives MEMBERSHIP from the caller's
# config in this order, never from a stale frozen list.
_GATE_ORDER = tuple(_GATE_FACTORIES)


def _enabled_gates(config):
    # Membership tracks the CALLER's config, not the emission-time GATES
    # snapshot: a config that now warrants more gates than at emission
    # (tdd_policy flipped to required, eval-gate turned on) gets them. A
    # config carrying a NON-EMPTY `_resolved_hooks` (a full resolved
    # project config, e.g. Tessera's or the emitted RESOLVED_CONFIG) is
    # authoritative. A missing OR EMPTY `_resolved_hooks` falls back to
    # the emission-time GATES - never to the empty set: a security
    # substrate silently building ZERO gates from a stray `[]` would be
    # the opposite of fail-loud. (When the project genuinely enables no
    # SDK gates, GATES itself is empty, so the result is still empty.)
    hooks = config.get("_resolved_hooks")
    if hooks:
        active = set(hooks)
        return [g for g in _GATE_ORDER if g in active]
    return [g for g in _GATE_ORDER if g in set(GATES)]


def build_hooks(config: dict) -> dict:
    """The single public builder (seam §9): resolved project config in,
    Agent SDK hooks mapping out. Fail-loud: a malformed config raises,
    and gate membership follows the passed config (never a stale
    emission-time set)."""
    if not isinstance(config, dict):
        raise TypeError("build_hooks: config must be the resolved "
                        "project config dict")
    missing = [k for k in ("secrets", "deps", "commands")
               if k not in config]
    if missing:
        raise KeyError(f"build_hooks: resolved config missing {missing}")
    out: dict = {}
    for name in _enabled_gates(config):
        registrations = ([_GATE_MATCHERS[name]]
                         + _GATE_EXTRA_MATCHERS.get(name, []))
        for event, matcher in registrations:
            kwargs = {}
            if name in _GATE_TIMEOUTS:
                kwargs["timeout"] = _GATE_TIMEOUTS[name]
            out.setdefault(event, []).append(HookMatcher(
                matcher=matcher,
                hooks=[_GATE_FACTORIES[name](config)],
                **kwargs))
    return out
'''


def sdk_gates_module(cfg: dict) -> str:
    """Render .claude/sdk_gates/gates.py for this resolved config.

    Only the two literals below are config-derived; the gate logic is
    static (and therefore syntax-checkable in isolation). Leaf scalars are
    coerced to str so the json.dumps output is ALWAYS valid Python: a
    YAML-typed bool/None (minyaml turns unquoted true/false/null into
    Python bool/None, and resolve_config never type-checks these leaves)
    would otherwise render as `true`/`null` - valid JSON but undefined
    Python names, NameError-ing the whole module at import.
    """
    gates = [h for h in cfg["_resolved_hooks"] if h in SDK_GATES]
    resolved = {
        "secrets": {"never_read_paths":
                    [str(p) for p in cfg["secrets"]["never_read_paths"]]},
        "deps": {"approved": [str(x) for x in cfg["deps"]["approved"]]},
        "commands": {k: str(cfg["commands"].get(k) or "")
                     for k in ("test", "lint", "format")},
        # Carried so build_hooks(RESOLVED_CONFIG) derives the same gate
        # membership on the SEV-1 path that a live resolved config would.
        "_resolved_hooks": list(gates),
    }
    dynamic = (
        "# The gates enabled for THIS project at emission.\n"
        "#\n"
        "# [upstream P2-2] NOT parity with the shell suite - the\n"
        "# earlier claim of parity was false. 7 gates here; 11 in the\n"
        "# shell suite. Shell-only, ABSENT here: ci-mirror (so\n"
        "# `git push` is UNGATED under SDK dispatch), drift-detector,\n"
        "# cost-log, task-done-alarm, decision-required-alarm,\n"
        "# spec-gate-entry. The shell suite is canonical; this module\n"
        "# is a consistent SUBSET of it.\n"
        f"GATES = {json.dumps(gates)}\n\n"
        "# Emission-time snapshot of the gate-relevant resolved config.\n"
        "# build_hooks(config) uses the config the CALLER passes (per the\n"
        "# seam-locked signature); this snapshot records what the installer\n"
        "# resolved at emission - digest-protected so drift between the two\n"
        "# is detectable - and serves SEV-1 use: build_hooks(RESOLVED_CONFIG).\n"
        f"RESOLVED_CONFIG = {json.dumps(resolved, indent=4)}\n"
    )
    return _HEADER + dynamic + _STATIC_BODY
