"""
File-body templates.

Every entry in TEMPLATES is a pure function of the resolved config, which is
what makes the installer deterministic: same cfg in => same bytes out. No
timestamps, no randomness, no environment reads in any body.
"""

from __future__ import annotations

import json

PROTOCOL_VERSION = "1.9.0"


# --------------------------------------------------------------------------- #
# Steering docs
# --------------------------------------------------------------------------- #
def _product(cfg):
    p = cfg["project"]
    return f"""# Product Steering

> Generated by bootstrap-installer from bootstrap.config.yaml.
> Edit freely; the installer will not overwrite local edits without --force.

**Project:** {p['name']}
**Archetype:** {p['archetype']}
**PRD tier:** {p['prd_tier']}
**PRD:** `{p['prd_path']}`

## Why this exists

(Filled from the PRD during the wizard's product phase. This stub records the
classification so downstream agents have stable steering even before the PRD
section is expanded.)

## Primary user & success criterion

See `{p['prd_path']}`. Update this file when the product thesis changes.
"""


def _tech(cfg):
    p = cfg["project"]
    c = cfg["commands"]
    return f"""# Technical Steering

**Shell:** {p['shell']}
**Archetype:** {p['archetype']}

## Project commands

| Purpose   | Command |
|-----------|---------|
| Test      | `{c['test'] or 'TODO: set commands.test in bootstrap.config.yaml'}` |
| Lint      | `{c['lint'] or 'TODO: set commands.lint'}` |
| Format    | `{c['format'] or 'TODO: set commands.format'}` |
| Typecheck | `{c['typecheck'] or '(none)'}` |
| CI local  | `{c['ci_local'] or '(none)'}` |

These commands are the contract the hooks enforce. If a cell says TODO the
corresponding gate will fail loudly until it is filled.
"""


def _deps(cfg):
    approved = cfg["deps"]["approved"]
    lines = "\n".join(f"- `{d}`" for d in approved) or "_(none yet)_"
    return f"""# Dependency Policy

New runtime/build dependencies must be on this list or explicitly approved
in-session (which then updates this file). The dependency gate hook enforces
this at install-command time.

## Approved

{lines}

## Adding a dependency

1. Justify the dependency against `principles.md`.
2. Add it here in the same change.
3. The dependency gate stops blocking once the package appears above.
"""


def _secrets(cfg):
    s = cfg["secrets"]
    paths = "\n".join(f"- `{p}`" for p in s["never_read_paths"])
    return f"""# Secrets & Sensitive-Data Policy

## Files the AI must never read

{paths}

The secrets gate hook blocks Read/Write/Edit on these paths. Unlike other
gates this one blocks mid-plan by design - secret exposure is catastrophic.

## On encountering a secret in code

Stop, alert the operator, do not echo the secret into any output, recommend
rotation.

## Rotation

{s['rotation_policy']}
"""


def _structure(cfg):
    return """# Structure Steering

Where things live so agents stop inventing file locations.

```
.claude/          harness: steering, hooks, skills, commands, agents, specs
docs/prd/         product requirements
src/              application code
tests/            tests, mirroring src/ layout
```

## Spec slug naming

Slugs for `specs/INDEX.md` rows and `/spec-new` invocations are derived
deterministically. Apply rules in order; first match wins:

1. **Primary output file.** If the deliverable names a primary output file,
   the slug is the kebab-cased stem of that filename
   (`docs/doc-grammar.md` -> `doc-grammar`).
2. **Noun phrase.** Otherwise kebab-case the deliverable's PRD name, drop
   articles/connectives, preserve numbers.
3. **Collision.** Append the PRD section number (`grammar-86`).
"""


def _principles(cfg):
    pr = cfg["principles"]
    ranked = "\n".join(f"{i+1}. {x}" for i, x in enumerate(pr["ranked"]))
    tb = "\n".join(f"- {x}" for x in pr["tiebreakers"]) or \
        "- _(add explicit tiebreakers for principles in tension)_"
    return f"""# Principles Steering

Ranked, project-specific. Generic acronyms (DRY/SOLID) are noise without
ranking and project rules.

## Ranked principles

{ranked}

## Tiebreakers

{tb}

## TDD policy

**{pr['tdd_policy']}**
""" + ("\nThe TDD gate hook enforces tests-before-source.\n"
        if pr["tdd_policy"] == "required" else "")


def _cicd(cfg):
    c = cfg["commands"]
    return f"""# CI/CD Steering

## Pipeline

Branch model and provider are project decisions; record them here.

PR checks must at minimum run:
- `{c['test'] or 'TODO: commands.test'}`
- `{c['lint'] or 'TODO: commands.lint'}`

## Agent stopping point

The agent's last action is **PR open** (or PR merge). The agent never deploys.
The CI-mirror hook runs these same checks locally before push.
"""


def _cicd_optout(cfg):
    c = cfg["commands"]
    return f"""# CI/CD Steering

**No CI/CD** (operator opted out in Phase 0).

The agent still runs the test command locally:
`{c['test'] or 'TODO: set commands.test'}`

Placeholder for future CI addition. Re-run the wizard's CI setup to populate.
"""


def _tools(cfg):
    m = cfg["mcp"]
    inst = "\n".join(
        f"- **{s.get('name','?')}** - `{s.get('command','?')}`"
        for s in m["servers"]) or "_(none - minimal start, by design)_"
    rej = "\n".join(
        f"- {r.get('name','?')}: {r.get('reason','')}"
        for r in m["rejected"]) or "_(none recorded)_"
    return f"""# Tools & MCP Steering

Principle: subagents and worktrees prevent drift; MCP tools are for capability
gaps, not drift gaps. Every server costs context budget.

## Built-ins relied upon

- Worktree-isolated subagents
- Tool search (deferred MCP tool loading)
- Hooks (Phase 6)
- Auto memory (native, on by default)

## Installed MCP servers

{inst}

## Considered & rejected

{rej}

## Don't add (guardrail)

Multiple overlapping memory MCPs; a memory MCP before auto-memory tried;
MCPs wrapping shell tools you already have; sequential-thinking MCPs.
"""


# --------------------------------------------------------------------------- #
# Hooks
# --------------------------------------------------------------------------- #
_HOOK_HEADER = """#!/usr/bin/env bash
# Generated by bootstrap-installer. Edit with care - security-relevant.
# Exit codes: 0 allow | 1 hook-internal error (tool proceeds) | 2 block.
#
# Security/correctness (BOOTSTRAP.md 6.D checklist):
#  * No eval/dynamic execution: the Python fallback walks keys explicitly.
#  * stdin is consumed exactly once into $INPUT; the fallback receives it via
#    the environment, NOT by re-reading already-consumed stdin (the bug that
#    silently disabled every parsing hook when jq was absent).
set -euo pipefail
LOG="${CLAUDE_PROJECT_DIR:-.}/.claude/logs/hooks.log"
mkdir -p "$(dirname "$LOG")"
log(){ printf '%s %s\\n' "$(date -u +%FT%TZ)" "$*" >>"$LOG"; }
INPUT="$(cat || true)"
have_jq(){ command -v jq >/dev/null 2>&1; }
# jget '.a.b' -> value at path or empty. Safe with or without jq.
jget(){
  local jqpath="$1"
  if have_jq; then
    printf '%s' "$INPUT" | jq -r "$jqpath // empty" 2>/dev/null || true
  else
    INPUT="$INPUT" python3 - "${jqpath#.}" <<'PYEOF' 2>/dev/null || true
import json, os, sys
raw = os.environ.get("INPUT", "")
try:
    d = json.loads(raw) if raw.strip() else {}
except Exception:
    sys.exit(0)
cur = d
for k in sys.argv[1].split("."):
    if isinstance(cur, dict) and k in cur:
        cur = cur[k]
    else:
        sys.exit(0)
if cur is not None and not isinstance(cur, (dict, list)):
    sys.stdout.write(str(cur))
PYEOF
  fi
}
"""


def _hook_body(name: str, cfg: dict):
    c = cfg["commands"]
    sec_paths = cfg["secrets"]["never_read_paths"]
    th = cfg["hooks"]

    if name == "spec-gate-entry":
        return _HOOK_HEADER + '''
# UserPromptSubmit: warn (do not block) if writing files with no active spec.
PROMPT="$(jget '.prompt')"
case "$PROMPT" in
  *write*|*edit*|*create*|*implement*)
    if [ ! -s "${CLAUDE_PROJECT_DIR:-.}/.claude/specs/INDEX.md" ]; then
      echo "No active spec detected. Consider /spec-new before writing." >&2
    fi ;;
esac
log "spec-gate-entry ok"
exit 0
'''

    if name == "spec-gate-commit":
        return _HOOK_HEADER + '''
# PreToolUse Bash(git commit): block files not referenced by an active spec.
CMD="$(jget '.tool_input.command')"
case "$CMD" in
  *"git commit"*)
    PROJ="${CLAUDE_PROJECT_DIR:-.}"
    INDEX="$PROJ/.claude/specs/INDEX.md"
    staged="$(git diff --cached --name-only 2>/dev/null || true)"
    [ -z "$staged" ] && { log "spec-gate-commit: no staged files"; exit 0; }
    # Collect the corpus of spec/task files once. nullglob-safe.
    corpus=""
    [ -f "$INDEX" ] && corpus="$INDEX"
    for d in "$PROJ"/.claude/specs/*/tasks/; do
      [ -d "$d" ] || continue
      for tf in "$d"*; do [ -f "$tf" ] && corpus="$corpus $tf"; done
    done
    if [ -z "$corpus" ]; then
      echo "Commit blocked: no active spec/task files exist yet." >&2
      echo "Run /spec-new before committing." >&2
      exit 2
    fi
    miss=""
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      # Word-boundary match on the path or its basename, not a loose
      # substring (S-3: 'a.py' must not be "referenced" by 'data.py').
      b="$(basename "$f")"
      if ! grep -rqE "(^|[^[:alnum:]_./-])($f|$b)([^[:alnum:]_-]|$)" \
             $corpus 2>/dev/null; then
        miss="$miss $f"
      fi
    done <<< "$staged"
    if [ -n "$miss" ]; then
      echo "Commit blocked: files not referenced by any active spec:$miss" >&2
      echo "Run /spec-new or add them to a tasks/*.md file." >&2
      exit 2
    fi ;;
esac
log "spec-gate-commit ok"
exit 0
'''

    if name == "secrets-gate":
        # S-5 fix: patterns emitted as a quoted heredoc list, never
        # interpolated into shell. Each pattern is matched against both the
        # basename and the full path; '**' is normalized to '*' so a
        # directory glob like 'secrets/**' actually matches under `case`.
        #
        # T-1 fix: a deny-list pattern like '.env*' was previously matched
        # ONLY as a prefix glob, so realistic dotenv names that do not START
        # with the pattern - 'config.env', 'prod.env', 'staging.env' - were
        # NOT blocked and the agent could read them (a fail-open in the one
        # hook BOOTSTRAP.md 6.D requires to fail loudly). For a security
        # deny-list the correct bias is to over-match, never under-match, so
        # each pattern is now also tried with an implicit leading '*' (suffix
        # form) and the comparison is case-insensitive (so '.PEM'/'.ENV'
        # variants are caught too). This only ever WIDENS the block set; no
        # path that was blocked before becomes allowed.
        pat_body = "\n".join(sec_paths)
        return _HOOK_HEADER + f'''
# PreToolUse Read/Write/Edit: hard-block never-read paths. Blocks mid-plan
# by design (secret exposure is catastrophic).
TARGET="$(jget '.tool_input.file_path')"
[ -z "$TARGET" ] && {{ log "secrets-gate: no path"; exit 0; }}
base="$(basename "$TARGET")"
# Case-insensitive matching ('.PEM'/'.ENV' are just as sensitive) done with
# bash's built-in `nocasematch` - NO external binary (T-1 follow-up: an
# earlier `tr`-based version exited 127 when `tr` was off PATH, which under
# the exit-code convention would let the secret read proceed; a pure-bash
# `shopt` cannot fail open that way).
shopt -s nocasematch
PAT_FILE="$(mktemp)"
trap 'rm -f "$PAT_FILE"' EXIT
cat >"$PAT_FILE" <<'PAT_EOF'
{pat_body}
PAT_EOF
while IFS= read -r pat; do
  [ -z "$pat" ] && continue
  cpat="$(printf '%s' "$pat" | sed 's/\\*\\*/*/g')"   # ** -> * for `case`
  # Match the pattern as-given (prefix/exact) AND with an implicit leading
  # '*' (suffix form) so 'config.env' is caught by '.env*'. Deny-list =>
  # over-match is safe; under-match is the catastrophic failure.
  case "$base" in
    $cpat|*$cpat)
      echo "BLOCKED: $TARGET matches never-read pattern $pat" >&2
      log "secrets-gate BLOCK $TARGET"; exit 2 ;;
  esac
  case "$TARGET" in
    $cpat|*/$cpat|*$cpat)
      echo "BLOCKED: $TARGET matches never-read pattern $pat" >&2
      log "secrets-gate BLOCK $TARGET"; exit 2 ;;
  esac
done <"$PAT_FILE"
log "secrets-gate ok $TARGET"
exit 0
'''

    if name == "test-gate":
        cmd = c["test"] or "echo 'TODO: commands.test unset' && exit 1"
        return _HOOK_HEADER + f'''
# PreToolUse git commit: block unless tests passed since last source edit.
CMD="$(jget '.tool_input.command')"
case "$CMD" in
  *"git commit"*)
    MARK="${{CLAUDE_PROJECT_DIR:-.}}/.claude/.last-test-pass"
    newest_src="$(find src -type f -newer "$MARK" 2>/dev/null | head -1 || true)"
    if [ ! -f "$MARK" ] || [ -n "$newest_src" ]; then
      echo "Running test gate: {cmd}" >&2
      if ( {cmd} ); then touch "$MARK"; else
        echo "Commit blocked: tests failing." >&2; exit 2; fi
    fi ;;
esac
log "test-gate ok"
exit 0
'''

    if name == "format-lint-gate":
        fmt = c["format"] or "true"
        lint = c["lint"] or "true"
        return _HOOK_HEADER + f'''
# PostToolUse Write/Edit: non-blocking format + lint feedback.
( {fmt} ) >/dev/null 2>&1 || echo "format reported issues" >&2
( {lint} ) 2>&1 | tail -20 >&2 || true
log "format-lint-gate ran"
exit 0
'''

    if name == "ci-mirror":
        ci = c["ci_local"] or c["test"] or "true"
        return _HOOK_HEADER + f'''
# PreToolUse git push: run the same checks CI runs, locally.
CMD="$(jget '.tool_input.command')"
case "$CMD" in
  *"git push"*)
    echo "CI mirror: {ci}" >&2
    if ! ( {ci} ); then echo "Push blocked: CI mirror failed." >&2; exit 2; fi
  ;;
esac
log "ci-mirror ok"
exit 0
'''

    if name == "cost-log":
        return _HOOK_HEADER + '''
# Stop hook: session-end cost summary. Guards against infinite loop.
if [ "$(jget '.stop_hook_active')" = "true" ]; then
  exit 0
fi
OUT="${CLAUDE_PROJECT_DIR:-.}/.claude/logs/cost.jsonl"
mkdir -p "$(dirname "$OUT")"
printf '{"event":"session_end","ts":"%s"}\\n' "$(date -u +%FT%TZ)" >>"$OUT"
log "cost-log appended"
exit 0
'''

    if name == "dependency-gate":
        # S-5 fix: approved names are emitted as a quoted, newline-delimited
        # heredoc body - never interpolated into a shell `case` pattern, so a
        # name containing shell metacharacters cannot corrupt the script.
        # S-2 fix: every token after the install/add verb is checked (handles
        # multiple packages and skips flags), not just the first via a fragile
        # single sed.
        approved = cfg["deps"]["approved"]
        approved_body = "\n".join(approved)
        return _HOOK_HEADER + f'''
# PreToolUse Bash: block package installs not on the approved list.
CMD="$(jget '.tool_input.command')"
APPROVED_FILE="$(mktemp)"
trap 'rm -f "$APPROVED_FILE"' EXIT
cat >"$APPROVED_FILE" <<'APPROVED_EOF'
{approved_body}
APPROVED_EOF
is_approved(){{ grep -qxF -- "$1" "$APPROVED_FILE"; }}
case " $CMD " in
  *" npm install "*|*" npm i "*|*" pip install "*|*" pip3 install "*\
|*" yarn add "*|*" pnpm add "*)
    # Strip everything up to and including the verb, then inspect each token.
    rest="${{CMD#*install }}"; rest="${{rest#*add }}"; rest="${{rest#*i }}"
    blocked=""
    skip_next=0
    for tok in $rest; do
      if [ "$skip_next" = "1" ]; then skip_next=0; continue; fi
      case "$tok" in
        # Value-taking flags consume the NEXT token (a file/path, not a pkg):
        -r|--requirement|-e|--editable|-c|--constraint|-t|--target\
|--prefix|--root|-d|--dest)
          skip_next=1; continue ;;
        -*) continue ;;                       # valueless flags (--upgrade...)
        *) ;;                                 # candidate package token
      esac
      name_only="${{tok%%[<>=@~ ]*}}"          # drop version specifiers
      [ -z "$name_only" ] && continue
      if ! is_approved "$name_only"; then
        blocked="$blocked $name_only"
      fi
    done
    if [ -n "$blocked" ]; then
      echo "Dependency gate: not in deps.md approved list:$blocked" >&2
      echo "Approve in-session and update .claude/steering/deps.md." >&2
      exit 2
    fi ;;
esac
log "dependency-gate ok"
exit 0
'''

    if name == "tdd-gate":
        return _HOOK_HEADER + '''
# PreToolUse Write to source: block unless a matching test was edited newer.
TARGET="$(jget '.tool_input.file_path')"
case "$TARGET" in
  src/*|lib/*)
    base="$(basename "$TARGET")"; stem="${base%.*}"
    if ! find tests -name "*${stem}*" -newer "$TARGET" 2>/dev/null \
         | grep -q .; then
      echo "TDD gate: write a failing test for $stem before $TARGET." >&2
      exit 2
    fi ;;
esac
log "tdd-gate ok"
exit 0
'''

    if name == "eval-gate":
        return _HOOK_HEADER + '''
# PreToolUse git push touching prompt files: require a passed eval.
CMD="$(jget '.tool_input.command')"
case "$CMD" in
  *"git push"*)
    if git diff --name-only HEAD~1 2>/dev/null | grep -qE 'prompt|\\.md$'; then
      MARK="${CLAUDE_PROJECT_DIR:-.}/.claude/.last-eval-pass"
      [ -f "$MARK" ] || { echo "Eval gate: run evals before pushing prompt \
changes." >&2; exit 2; }
    fi ;;
esac
log "eval-gate ok"
exit 0
'''

    if name == "drift-detector":
        tc = th["drift_tool_call_threshold"]
        dm = th["drift_session_duration_minutes"]
        fr = th["drift_file_read_threshold"]
        return _HOOK_HEADER + f'''
# PostToolUse: soft drift notice (tiers 1-2). Tier-3 enforcement is wired
# via settings.json + the loop-cooperation hook when enabled.
CFG="${{CLAUDE_PROJECT_DIR:-.}}/.claude/hooks/audio-alerts.config"
SID="${{CLAUDE_SESSION_ID:-default}}"
ST="${{CLAUDE_PROJECT_DIR:-.}}/.claude/sessions/.drift-state-$SID"
mkdir -p "$(dirname "$ST")"
n=$(( $(cat "$ST" 2>/dev/null || echo 0) + 1 )); echo "$n" >"$ST"
if [ "$n" -ge {tc} ]; then
  echo "DRIFT: $n tool calls (threshold {tc}). Consider /checkpoint." >&2
fi
log "drift-detector n=$n th={tc}/{dm}m/{fr}"
exit 0
'''

    if name == "task-done-alarm":
        return _HOOK_HEADER + '''
# SubagentStop: informational completion cue. Never blocks.
if [ "$(jget '.stop_hook_active')" = "true" ]; then
  exit 0
fi
echo "Task complete. Ready for review." >&2
log "task-done-alarm"
exit 0
'''

    if name == "decision-required-alarm":
        return _HOOK_HEADER + '''
# Notification: persistent cue when the AI hits an urgent escalation.
SID="${CLAUDE_SESSION_ID:-default}"
P="${CLAUDE_PROJECT_DIR:-.}/.claude/sessions/.decision-pending-$SID"
mkdir -p "$(dirname "$P")"; : >"$P"
echo "DECISION REQUIRED: operator action needed (see chat)." >&2
log "decision-required-alarm fired"
exit 0
'''

    if name == "drift-detector-loop-cooperation":
        return _HOOK_HEADER + '''
# Augments tier-3: inside loop.sh/goal-loop.sh, tier-3 fire => checkpoint and
# end turn instead of hard-block-until-/clear. No-ops outside loop/goal mode.
SID="${CLAUDE_SESSION_ID:-default}"
S="${CLAUDE_PROJECT_DIR:-.}/.claude/sessions"
if ls "$S"/.loop-active-* "$S"/.goal-active-* >/dev/null 2>&1; then
  if ls "$S"/.drift-tier3-* >/dev/null 2>&1; then
    echo "tier3-in-loop: write checkpoint and end turn." >&2
  fi
fi
log "drift-loop-cooperation ok"
exit 0
'''

    if name == "iteration-summary-enforcement":
        return _HOOK_HEADER + '''
# goal-loop.sh post-iteration: require a well-formed iteration summary file.
SID="${CLAUDE_SESSION_ID:-default}"
S="${CLAUDE_PROJECT_DIR:-.}/.claude/sessions"
latest="$(ls -t "$S"/.iteration-summary-* 2>/dev/null | head -1 || true)"
if [ -z "$latest" ] || [ ! -s "$latest" ]; then
  echo "iteration-summary missing/empty - feeding error to next iteration." >&2
  exit 1
fi
log "iteration-summary-enforcement ok"
exit 0
'''
    return None


# --------------------------------------------------------------------------- #
# settings.json (Phase 6 wiring)
# --------------------------------------------------------------------------- #
def _settings_json(cfg):
    hooks = cfg["_resolved_hooks"]
    event_map = {
        "spec-gate-entry": ("UserPromptSubmit", None),
        "spec-gate-commit": ("PreToolUse", "Bash"),
        "secrets-gate": ("PreToolUse", "Read|Write|Edit"),
        "test-gate": ("PreToolUse", "Bash"),
        "format-lint-gate": ("PostToolUse", "Write|Edit"),
        "ci-mirror": ("PreToolUse", "Bash"),
        "cost-log": ("Stop", None),
        "dependency-gate": ("PreToolUse", "Bash"),
        "tdd-gate": ("PreToolUse", "Write"),
        "eval-gate": ("PreToolUse", "Bash"),
        "drift-detector": ("PostToolUse", None),
        "task-done-alarm": ("SubagentStop", None),
        "decision-required-alarm": ("Notification", None),
        "drift-detector-loop-cooperation": ("PostToolUse", None),
        "iteration-summary-enforcement": ("Stop", None),
    }
    slow = {"ci-mirror", "test-gate", "format-lint-gate"}
    by_event: dict = {}
    for hk in hooks:
        ev, matcher = event_map[hk]
        entry = {
            "type": "command",
            "command": f"$CLAUDE_PROJECT_DIR/.claude/hooks/{hk}.sh",
        }
        if hk in slow:
            entry["async"] = True
        bucket = by_event.setdefault(ev, [])
        if matcher:
            grp = next((g for g in bucket if g.get("matcher") == matcher), None)
            if grp is None:
                grp = {"matcher": matcher, "hooks": []}
                bucket.append(grp)
            grp["hooks"].append(entry)
        else:
            grp = next((g for g in bucket if "matcher" not in g), None)
            if grp is None:
                grp = {"hooks": []}
                bucket.append(grp)
            grp["hooks"].append(entry)

    settings = {
        "$schema": "https://json.schemastore.org/claude-code-settings.json",
        "_generatedBy": f"bootstrap-installer (protocol {PROTOCOL_VERSION})",
        "hooks": by_event,
    }
    if cfg["mcp"]["servers"]:
        settings["_note_mcp"] = ("MCP servers are added via `claude mcp add`; "
                                 "see .claude/steering/tools.md")
    return json.dumps(settings, indent=2) + "\n"


def _audio_config(cfg):
    th = cfg["hooks"]
    return f"""# === Drift detector ===
drift_enabled=true
drift_tool_call_threshold={th['drift_tool_call_threshold']}
drift_session_duration_minutes={th['drift_session_duration_minutes']}
drift_file_read_threshold={th['drift_file_read_threshold']}
drift_alert_1_delay_minutes=0
drift_alert_2_delay_minutes=10
drift_alert_3_delay_minutes=15
drift_tier3_enforced=true
quiet_mode_overridden_by_drift_tier3=true

# === Task done ===
task_done_enabled=true
task_done_batch_window_seconds=30

# === Decision required ===
decision_required_enabled=true
decision_required_persistent_notification=true

# === Audio ===
audio_enabled=true
audio_file_drift_gentle=~/.claude/sounds/drift-gentle.wav
audio_file_drift_insistent=~/.claude/sounds/drift-insistent.wav
audio_file_drift_firm=~/.claude/sounds/drift-firm.wav
audio_file_task_done=~/.claude/sounds/task-done.wav
audio_file_decision_required=~/.claude/sounds/decision-required.wav

# === Notifications ===
notification_enabled=true
notification_daemon=auto

# === Quiet mode ===
quiet_mode_overridden_by_decision_required=true

# === State retention ===
purge_old_state_after_days=7
"""


# --------------------------------------------------------------------------- #
# Skills / commands / agents (Phase 7)
# --------------------------------------------------------------------------- #
_SKILL_LIST = [
    ("spec-new", "Convert a PRD section into requirements.md (EARS where it "
     "fits). Initializes decisions.md and changelog.md."),
    ("spec-review", "Find contradictions in a spec."),
    ("spec-decompose", "Turn a spec into atomic vertical-slice tasks with a "
     "parallelism map."),
    ("plan-review", "Review decomposition before implementation begins."),
    ("spec-validate", "Check implementation against requirements.md at the "
     "spec version active when implementation began."),
    ("code-review", "Review a diff against spec and principles.md."),
    ("decision-log", "Append non-obvious choices to the spec's decisions.md."),
    ("pr-author", "Generate a PR description: spec link, version, validation "
     "report, decision-log summary."),
    ("checkpoint", "Write a structured session synopsis to "
     ".claude/sessions/<timestamp>-checkpoint.md."),
    ("resume", "Load the most recent checkpoint (or a chosen one)."),
    ("ack-drift", "Acknowledge a drift alert for the session."),
    ("quiet", "Mute audio alerts (session or duration)."),
    ("quiet-task-done", "Mute only the task-done audio."),
]


def _skills(cfg):
    tdd = cfg["principles"]["tdd_policy"]
    out = {}
    for name, desc in _SKILL_LIST:
        rec = ""
        if name in ("spec-review", "code-review"):
            rec = "\n> Recommended: invoke from an Opus session.\n"
        out[name] = (f"---\nname: {name}\n"
                     f"description: {desc}\n---\n\n# {name}\n{rec}\n{desc}\n")
    if tdd != "off":
        out["test-author"] = ("---\nname: test-author\n"
                              "description: Tests-first workflow per task.\n"
                              "---\n\n# test-author\n\nWrite failing tests "
                              "before source, per principles.md TDD policy "
                              f"({tdd}).\n")
    return out


def _commands(cfg):
    out = {}
    for name, desc in _SKILL_LIST:
        explicit = name in ("checkpoint", "resume", "ack-drift")
        note = ("\n_Explicit-only: never auto-invoked by hooks or "
                "subagents._\n" if explicit else "")
        out[name] = (f"---\ndescription: {desc}\n---\n\n"
                     f"Invoke the `{name}` skill.{note}\n")
    return out


def _agents(cfg):
    w = cfg["workflow"]
    return {
        "implementer": (
            f"---\nname: implementer\nmodel: {w['implementer_model']}\n"
            f"isolation: worktree\n"
            f"description: Use when an approved spec task is ready for "
            f"implementation. Reads .claude/specs/<slug>/tasks/<id>.md.\n"
            f"---\n\n# implementer\n\nSelf-contained: subagents do not "
            f"inherit the default system prompt. Read steering + spec + task, "
            f"implement, run gates, commit, log decisions via decision-log.\n"),
        "reviewer": (
            f"---\nname: reviewer\nmodel: {w['reviewer_model']}\n"
            f"effort: high\ntools: Read, Grep, Glob, Bash\n"
            f"description: Use after implementer commits a task. Reviews diff "
            f"against the spec's acceptance criteria and principles.md.\n"
            f"---\n\n# reviewer\n\nRead-only by construction (no Edit/Write). "
            f"Return issues or approval.\n"),
        "integrator": (
            f"---\nname: integrator\nmodel: {w['integrator_model']}\n"
            f"description: Use when two implementer worktrees produced "
            f"conflicting changes to overlapping files.\n"
            f"---\n\n# integrator\n\nResolve merge conflicts between parallel "
            f"task worktrees.\n"),
    }


# --------------------------------------------------------------------------- #
# Queue scaffolding (Phase 9.7)
# --------------------------------------------------------------------------- #
def _backlog(cfg):
    return """# Project backlog

<!-- Ready to run / Operator-only / Deferred are populated by spec-decompose.
     In flight / Completed / Halted are populated and reset by the runner. -->

## Queue policy

max_concurrent_tasks: 2
consecutive_halt_threshold: 3
pause_on_max_iterations: false
pause_on_goal_condition_suspect: true

## Ready to run

## Operator-only (skipped by runner)

## In flight

## Completed this run

## Halted this run (needs review)

## Deferred
"""


def _auto_config(cfg):
    return """# auto-config.md

# --- Non-configurable invariants (stated, not set) ---
#  * Operator-only tasks are always skipped by the runner.
#  * The runner pauses (never terminates) when only operator action can
#    unblock remaining work.
#  * Urgent escalations always halt the queue.

max_concurrent_tasks: 2
consecutive_halt_threshold: 3
time_budget_minutes: 0          # 0 = unlimited
token_budget: 0                 # 0 = unlimited
task_budget: 0                  # 0 = unlimited
pause_on_max_iterations: false
pause_on_goal_condition_suspect: true
"""


def _auto_sh(cfg):
    # F-2 fix: auto.sh is a terminal-invoked runner, NOT a stdin-fed hook.
    # It must not inherit `INPUT="$(cat)"` (which blocks waiting for EOF) or
    # the jget machinery. The trap records a BOOTSTRAP.md exit_reason rather
    # than blanket `exit 0`, and only the EXIT arm cleans the sentinel.
    return '''#!/usr/bin/env bash
# Generated by bootstrap-installer. Autonomous queue runner (Phase 9.7).
# SKELETON: the dispatch loop is intentionally unimplemented - see README and
# BOOTSTRAP.md Phase 9.7. Do not use unattended until the loop and the
# exit_reason accounting below are completed and smoke-tested.
set -euo pipefail
# Self-locate: this script lives at <project>/.claude/auto.sh, so the project
# root is two levels up. Honour CLAUDE_PROJECT_DIR if set, else derive it -
# never assume the invocation cwd is the project root (F-2 follow-up).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
PROJ="${CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
LOG="$PROJ/.claude/logs/hooks.log"
mkdir -p "$(dirname "$LOG")"
log(){ printf '%s %s\\n' "$(date -u +%FT%TZ)" "$*" >>"$LOG"; }

RUN="$PROJ/.claude/queue/.run-active"
mkdir -p "$(dirname "$RUN")"            # queue dir may not exist yet
EXIT_REASON="infrastructure-failure"   # pessimistic default; set on clean paths

cleanup(){
  rc=$?
  rm -f "$RUN"
  log "auto.sh exit reason=$EXIT_REASON rc=$rc"
  # NOTE: a complete implementation updates the dangling queue_runs_history
  # entry here with end_timestamp and exit_reason before exiting.
  exit "$rc"
}
on_signal(){ EXIT_REASON="signal-interrupt"; exit 130; }
trap cleanup EXIT
trap on_signal INT TERM

if [ -e "$RUN" ]; then
  echo "A queue run is already active ($RUN). Refusing to start." >&2
  EXIT_REASON="manual-halt-sentinel"
  exit 1
fi
printf 'pid=%s start=%s\\n' "$$" "$(date -u +%FT%TZ)" >"$RUN"
log "auto.sh started (skeleton)."

echo "Queue runner skeleton installed. Implement the dispatch loop per" \\
     "BOOTSTRAP.md Phase 9.7 before any unattended use." >&2
EXIT_REASON="queue-empty"   # skeleton: nothing dispatched, treated as no-op
exit 0
'''


def _per_task_wrapper(kind: str) -> str:
    """Shared skeleton for the two per-task wrappers (loop.sh, goal-loop.sh).

    `kind` is "loop" or "goal". These are GUARDED SKELETONS, exactly like
    auto.sh: they perform the race-safe claim sequence BOOTSTRAP.md Phase 9.5
    step 2 mandates (O_CREAT|O_EXCL active sentinel, flock on the state file,
    tmpfile-then-rename state write) and the eligibility/`.halt` guards, then
    refuse to run the unattended `claude -p` loop, which is the part the
    operator must complete and smoke-test per the trust ramp. Failing safe
    here means: never start the agent loop, never hang from a terminal,
    always release the lock and remove the just-written sentinel on abort.
    """
    if kind == "loop":
        title = "Autonomous loop wrapper (Phase 9.5)"
        active = ".loop-active"
        sibling = ".goal-active"
        sib_list = "goal_in_flight"
        my_list = "loop_in_flight"
        phase = "9.5"
    else:
        title = "Goal-supervised wrapper (Phase 9.6)"
        active = ".goal-active"
        sibling = ".loop-active"
        sib_list = "loop_in_flight"
        my_list = "goal_in_flight"
        phase = "9.6"
    elig = "loop_eligible" if kind == "loop" else "goal_supervised_eligible"
    # NB: doubled braces are literal shell; {placeholders} are substituted.
    return '''#!/usr/bin/env bash
# Generated by bootstrap-installer. {title}.
# SKELETON: the claude -p iteration loop is intentionally unimplemented -
# see README and BOOTSTRAP.md Phase {phase}. The race-safe claim sequence and
# all fail-safe guards below ARE implemented; the agent loop is the part the
# operator completes and smoke-tests per the trust ramp. Until then this
# script refuses to dispatch any unattended work.
#
# Usage: {self} <task-id> [spec-id]
set -euo pipefail
# Self-locate: this script lives at <project>/.claude/{self}, so the project
# root is two levels up. Honour CLAUDE_PROJECT_DIR if set, else derive it -
# never assume the invocation cwd is the project root (F-2 idiom).
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]:-$0}}")" && pwd)"
PROJ="${{CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}}"
LOG="$PROJ/.claude/logs/hooks.log"
mkdir -p "$(dirname "$LOG")"
log(){{ printf '%s %s\\\\n' "$(date -u +%FT%TZ)" "$*" >>"$LOG"; }}

TASK_ID="${{1:-}}"
if [ -z "$TASK_ID" ]; then
  echo "usage: {self} <task-id> [spec-id]" >&2
  exit 2
fi
SESS="$PROJ/.claude/sessions"
mkdir -p "$SESS"
ACTIVE="$SESS/{active}-$TASK_ID"
STATE="$PROJ/.claude/.bootstrap-state.json"
HALT="$PROJ/.claude/queue/.halt"

CLAIMED=0
EXIT_REASON="infrastructure-failure"   # pessimistic; set on clean paths
cleanup(){{
  rc=$?
  # Only remove the sentinel if WE claimed it (never yank another wrapper's).
  [ "$CLAIMED" = 1 ] && rm -f "$ACTIVE"
  log "{self} task=$TASK_ID exit reason=$EXIT_REASON rc=$rc"
  # NOTE: a complete implementation removes this task's entry from
  # {my_list} (flock + tmpfile-rename) and writes loop-final-$TASK_ID.md here.
  exit "$rc"
}}
on_signal(){{ EXIT_REASON="signal-interrupt"; exit 130; }}
trap cleanup EXIT
trap on_signal INT TERM

# Honour the manual-halt sentinel before doing anything expensive.
if [ -e "$HALT" ]; then
  echo "Halt sentinel present ($HALT). Refusing to start." >&2
  EXIT_REASON="manual-halt-sentinel"
  exit 1
fi

# 1. Eligibility: the task definition must declare {elig}: true. Absent a
#    task file we refuse rather than assume eligibility (fail safe).
TASKFILE=""
for d in "$PROJ"/.claude/specs/*/tasks/; do
  [ -f "$d$TASK_ID.md" ] && TASKFILE="$d$TASK_ID.md" && break
done
if [ -z "$TASKFILE" ]; then
  echo "No task file for '$TASK_ID' under .claude/specs/*/tasks/." >&2
  EXIT_REASON="goal-condition-suspect"
  exit 1
fi
if ! grep -qE '^[[:space:]]*{elig}:[[:space:]]*true[[:space:]]*$' "$TASKFILE"
then
  echo "Task '$TASK_ID' is not {elig}: true. Refusing." >&2
  EXIT_REASON="goal-condition-suspect"
  exit 1
fi

# 2. Race-safe claim (BOOTSTRAP.md Phase {phase} step 2):
#    2.1 O_CREAT|O_EXCL active sentinel.
if ! ( set -C; printf '%s\\\\n' "$$" >"$ACTIVE" ) 2>/dev/null; then
  echo "Another {kind} run already owns '$TASK_ID' ($ACTIVE)." >&2
  EXIT_REASON="manual-halt-sentinel"
  exit 1
fi
CLAIMED=1
#    2.2-2.4 flock the state file, cross-mode mutual-exclusion check, append
#    to {my_list}, tmpfile-then-rename. flock is required; if it is missing
#    we fail safe (release sentinel via trap) rather than racing.
if ! command -v flock >/dev/null 2>&1; then
  echo "flock unavailable - cannot guarantee race-safe state update." >&2
  EXIT_REASON="infrastructure-failure"
  exit 1
fi
exec 9>"$STATE.lock"
flock 9
if ls "$SESS"/{sibling}-"$TASK_ID" >/dev/null 2>&1; then
  flock -u 9
  echo "Task '$TASK_ID' is already in the other autonomous mode. Aborting." >&2
  EXIT_REASON="goal-condition-suspect"
  exit 1
fi
# Append-to-{my_list} + tmpfile-then-rename is the operator-completed step;
# the lock/sentinel scaffolding around it is done. Skeleton stops here.
flock -u 9
log "{self} claimed task=$TASK_ID (skeleton: agent loop not implemented)"
echo "{title} skeleton: task '$TASK_ID' claimed and guarded. Implement the" >&2
echo "claude -p iteration loop per BOOTSTRAP.md Phase {phase} before any" >&2
echo "unattended use. No agent work was dispatched." >&2
EXIT_REASON="max-iterations"   # skeleton no-op: nothing iterated
exit 0
'''.format(title=title, phase=phase, self=("loop.sh" if kind == "loop"
                                            else "goal-loop.sh"),
           active=active, sibling=sibling, my_list=my_list,
           elig=elig, kind=kind)


def _loop_sh(cfg):
    return _per_task_wrapper("loop")


def _goal_loop_sh(cfg):
    return _per_task_wrapper("goal")


def _loop_config(cfg):
    return """# loop-config.md

# Operator-tunable loop-mode settings (BOOTSTRAP.md Phase 9.5).
# Format mirrors audio-alerts.config. Committed to the repo.

max_iterations: 10
infra_retry_seconds: 30
infra_max_consecutive_failures: 2
# Completion-criteria checks the wrapper trusts the agent's self-attestation
# on in loop mode (goal-supervised mode re-checks them independently):
require_completion_sentinel: true
"""


def _goal_config(cfg):
    return """# goal-config.md

# Operator-tunable goal-supervised settings (BOOTSTRAP.md Phase 9.6).
# Format mirrors audio-alerts.config. Committed to the repo.

max_iterations: 10
infra_retry_seconds: 30
infra_max_consecutive_failures: 2
judge_model: haiku
# Three consecutive malformed/missing iteration summaries => goal-condition
# -suspect-class halt (parallels persistent-evaluator-disagreement).
summary_failure_halt_threshold: 3
require_completion_sentinel: true
investigate_disagreement: false
"""


# --------------------------------------------------------------------------- #
# CLAUDE.md + specs index + gitignore
# --------------------------------------------------------------------------- #
def _claude_md(cfg):
    flags = cfg["autonomous_modes"]
    queue_section = ""
    if flags["queue_mode_enabled"]:
        queue_section = (
            "\n## Queue mode coordination layer\n\n"
            "`.claude/auto.sh` dispatches per-task wrappers from "
            "`.claude/queue/backlog.md`. The runner does not load this file; "
            "the queue is the coordination surface.\n")
    return f"""# CLAUDE.md

Thin by design. Steering lives in `.claude/steering/`. This file is the
escalation contract, not a knowledge dump.

## Workflow

Per-task lifecycle: spec-review -> spec-decompose -> plan-review -> implement
(decisions logged continuously) -> local gates -> code-review ->
spec-validate -> pr-author.

## Urgent escalations (AI stops and asks)

1. A do-not-touch / never-read path needs access or modification.
2. A secret or credential is encountered.
3. A hook blocks and the fix is not obvious within one attempt.
4. A dependency not on the `deps.md` approved list is needed.
5. Implementation reveals the spec was wrong.

Non-urgent (in-chat only): ambiguous acceptance criteria, two reasonable
approaches with material tradeoffs, spec version drift mid-task.

The escalation list is the contract. If the agent escalates outside it, fix
steering - do not override in-session.
{queue_section}"""


def _specs_index(cfg):
    return """# Specs Index

| slug | status | active version | in-flight against superseded? |
|------|--------|----------------|-------------------------------|
| _placeholder_ | planned | - | - |

Rows derived from the PRD (Phase 7.6) or invented by /spec-new at call time.
"""


def _gitignore(cfg):
    # BOOTSTRAP.md Recovery & State: bootstrap-internal state files use the
    # dotfile convention precisely so they are gitignored as a group; line
    # 825 additionally gitignores the per-iteration scratch sentinels while
    # keeping operator-facing audit records (loop-final-*, decisions-log-*,
    # backlog.md, run-summary-*) committed.
    base = [
        "logs/", ".last-test-pass", ".last-eval-pass",
        "sessions/.session-*", "sessions/.drift-*",
        "sessions/.decision-pending-*", "sessions/.quiet-*",
        "sessions/.loop-active-*", "sessions/.goal-active-*",
        "sessions/.loop-complete-*", "sessions/.loop-halt-*",
        "sessions/.iteration-summary-*", "sessions/.evaluator-feedback-*",
        ".installer-manifest.json", ".bootstrap-state.json",
        ".bootstrap-state.json.lock", ".bootstrap-incomplete",
    ]
    if cfg["autonomous_modes"]["queue_mode_enabled"]:
        base += ["queue/.run-active", "queue/.halt", "queue/.resume"]
        # NOTE: backlog.md and run-summary-*.md are intentionally NOT ignored.
    return "# bootstrap-installer generated\n" + "\n".join(base) + "\n"


# --------------------------------------------------------------------------- #
# Retrofit-mode templates (additive; greenfield path is byte-identical).
#
# Per OD-1 (bundled freeze exception) + C1, every function above this
# block is AST-unmodified. The retrofit additions live below as new
# top-level functions and new TEMPLATES entries; build_plan's single
# retrofit-overlay branch (in installer.py) calls them when
# cfg["mode"] == "retrofit". Greenfield cfgs never reach any of this
# code (D2 golden test confirms byte-identical content tree).
# --------------------------------------------------------------------------- #
def _retrofit_inventory_readme(cfg):
    """Static pointer to the codebase-derived inventory snapshot. Per OD-5
    + non-blocking note: zero codebase-derived content (only references
    paths). The other 10 inventory files are written by the decision layer
    (lib/inventory_scan.py); this README is the installer's responsibility."""
    return """# .claude/inventory/ — codebase audit (R0)

One-time snapshot of pre-retrofit state, written by
`bin/retrofit-interview scan` (the decision layer). **Frozen at retrofit
time** — not maintained going forward. Steering docs supersede the
inventory; consult inventory for historical context only.

## Files in this directory

| File | Phase | What it captures |
|---|---|---|
| `structure.md` | R0 step 3 | Top-level dir tree, file counts |
| `languages.md` | R0 step 3 | File-extension distribution, manifests |
| `dependencies.md` | R0 step 3 | Per-manifest declared deps |
| `testing.md` | R0 step 3 | Test files, name-match coverage, no-test modules |
| `git-history.md` | R0 step 3 | HEAD SHA, contributors, hotspots, stability cutoff |
| `conventions.md` | R0 step 3 | Lint/format config presence, async hint |
| `product-signals.md` | R0 step 4 | README/docs found, inferred project name |
| `pm-tooling-signals.md` | R0 step 12 | Ticket dirs, CI integrations, commit refs |
| `existing-claude.md` | R0 step 1 | Prior .claude/ state, archived dirs |
| `baseline-metrics.md` | R0 step 8 | DORA placeholders for 30/60/90-day comparison |
| `README.md` | (this file) | Pointer; written by the installer |

## What's NOT here (deferred or optional)

- `tribal-knowledge.md` (R0 step 9) — interactive interview only.
- `regulatory-context.md` (R0 step 10) — interactive 7-question scan.
- `danger-zones.md` (R2 step 8) — requires complexity proxy + operator
  review; produced during R2 conversation, not at scan time.
- `equivalence-validation.md` (R7) — produced at handoff, not scan.

## How to refresh

The inventory is a frozen historical snapshot. To re-scan (e.g., months
post-retrofit, to compare against the baseline), run:

    bin/retrofit-interview scan -C .

This OVERWRITES the snapshot files. R7's baseline-metrics review is the
intended re-scan cadence (30/60/90 days).
"""


def _retrofit_debt(cfg):
    entries = cfg["retrofit"]["debt"]["entries"]
    body = ["# Technical debt registry (R3)",
            "",
            "> Generated by retrofit-installer from "
            "bootstrap.config.yaml.",
            "",
            "## How to use this file",
            "",
            "- Add entries as issues are identified during regular work.",
            "- Update `Status` to `in-progress` when work begins, "
            "`resolved` when done.",
            "- Periodically review and re-prioritize.",
            "- This file is project-local; not standardized across the "
            "portfolio.",
            "",
            "## Out of scope statement",
            "",
            "**The retrofit does not fix any of these items.** Resolution "
            "is a separate, ongoing effort tracked here. Do not let this "
            "file's length discourage starting on new feature work.",
            ""]
    if not entries:
        body.append("## Entries")
        body.append("")
        body.append("_(none yet — the retrofit detected no debt-shaped "
                    "signals in the inventory.)_")
    else:
        body.append(f"## Entries ({len(entries)} open)")
        body.append("")
        body.append("| What | Where | Severity | Discovered | Plan | Status |")
        body.append("|---|---|---|---|---|---|")
        for e in entries:
            body.append(
                f"| {e.get('what', '')} | {e.get('where', '')} | "
                f"{e.get('severity', 'low')} | {e.get('discovered', '')} | "
                f"{e.get('plan', '')} | {e.get('status', 'open')} |")
    body.append("")
    return "\n".join(body)


def _retrofit_spec_strategy(cfg):
    """Forward-only / touch-based / bulk decision + legacy allowlist +
    retrofit-active master switch. The allowlist is enclosed in a marker
    block the hooks parse at runtime (per the §3 hook-body contract)."""
    r = cfg["retrofit"]
    strategy = r["spec_strategy"]
    allowlist = r["legacy_allowlist"]
    patterns = r["spec_patterns"]

    pattern_lines = []
    if patterns["change"]:
        pattern_lines.append(
            "- **Change specs** — every modification updates a spec. "
            "Always applicable.")
    if patterns["boundary"]:
        pattern_lines.append(
            "- **Dependency boundary specs** — machine-readable contracts "
            "at integration points (OpenAPI / JSON Schema / Protobuf). "
            "See `contracts.md`.")
    if patterns["migration"]:
        pattern_lines.append(
            "- **Migration specs** — multi-phase architectural change "
            "with target state + incremental steps + integration layer. "
            "See `migration.md`.")

    allowlist_inner = "\n".join(allowlist) if allowlist else ""

    return f"""# Spec backfill strategy (R4)

> Generated by retrofit-installer from bootstrap.config.yaml.

## Chosen strategy

**{strategy}** — chosen at retrofit time.

| Strategy | When applies |
|---|---|
| `forward-only` | New features get specs; legacy untouched until first edit |
| `touch-based` | Legacy files get specs the first time they're modified |
| `bulk` | All legacy files get one-paragraph specs upfront (rarely chosen) |

## Active spec patterns (R4 step 3)

{chr(10).join(pattern_lines) if pattern_lines else "_(only change specs apply for this project)_"}

## Promotion rule

A legacy file becomes spec-covered when first modified after retrofit:
1. If in `inventory/danger-zones.md` or in the allowlist below, run
   `legacy-pin-test` first to capture current behavior (pin-first
   discipline, R2 G6).
2. Run `/spec-new` for the module to create the change spec
   (`legacy-spec` skill).
3. Make the modification; the spec gates now enforce.

## Retrofit-active master switch

`.claude/.retrofit-state.json` carries a `retrofit_active` boolean. While
true, the spec-gate-commit hook permits writes under `.claude/` so the
retrofit itself can land. R7 sets `retrofit_active: false` at handoff
and the gate operates normally from then on.

## Legacy allowlist

Paths in the block below are EXEMPT from the spec gate, test gate, and
TDD gate (where applicable) until they're touch-based-backfilled. The
gate scripts read this list at runtime — edit and re-save to update
without re-running the installer.

To ADD a path: append to the list (broader exemption).
To REMOVE a path: delete the line (subjects it to spec gating
immediately — usually only correct once a spec exists for it).

The list shrinks over the project's lifetime; when empty, retrofit is
fully complete (no special handling for any file).

<!-- LEGACY_ALLOWLIST_BEGIN -->
{allowlist_inner}
<!-- LEGACY_ALLOWLIST_END -->

## Pin-first discipline declaration (R2 G6)

For any modification to a file in `inventory/danger-zones.md` or in the
legacy allowlist above, the **pin → spec → modify** sequence applies:
a `legacy-pin-test` is generated before the modification; the change
spec describes the intended delta; the modification is verifiable
against both. This is enforced by the reviewer agent (`.claude/agents/
reviewer.md` retrofit-flavor body).
"""


def _retrofit_workflow_sot(cfg):
    pm = cfg["retrofit"]["pm"]
    s = pm["strategy"]
    note = {
        "spec_canonical": (
            "Strategy A — specs in `.claude/specs/` are the source of "
            "truth. Existing tickets archive at retrofit; open tickets "
            "convert to specs via `ticket-to-spec`. PM tool MCP not "
            "installed; PM tool, if used at all, is community-facing only."),
        "pm_canonical": (
            "Strategy B — tickets in the existing PM tool remain the entry "
            "point. Specs derive from tickets via `ticket-to-spec`. PM "
            "tool MCP IS installed; specs reference back to ticket IDs. "
            "This is an INTENTIONAL VARIATION from BOOTSTRAP's "
            "specs-are-source-of-truth claim."),
        "hybrid": (
            "Strategy C — new initiatives get specs; in-flight tickets "
            "stay in PM tool until closure; 90-day cutover review. PM "
            "tool MCP installed for transition window."),
    }[s]
    return f"""# Workflow source of truth (R0.7)

> Generated by retrofit-installer from bootstrap.config.yaml.

## Chosen strategy

**Strategy:** `{s}`
**PM tool:** `{pm["tool"]}`
**Future role of PM tool:** `{pm["tool_role_after"]}`

{note}

## Hybrid review checkpoint

{("Scheduled for: " + str(pm["hybrid_review_date"])
  if pm.get("hybrid_review_date") else
  "_(not scheduled — Strategy "
  + s + " does not require a 90-day review.)_")}

## Ticket migration disposition

| Disposition | Tickets |
|---|---|
| Convert now | {", ".join(pm["ticket_migration"]["convert_now"]) or "_(none)_"} |
| Defer | {", ".join(pm["ticket_migration"]["defer"]) or "_(none)_"} |
| Close | {", ".join(pm["ticket_migration"]["close"]) or "_(none)_"} |

Run `ticket-to-spec <id>` for each convert-now ticket post-retrofit
(see R7 handoff). The migration is QUEUED at retrofit, EXECUTED later.
"""


def _retrofit_contracts(cfg):
    """Emitted only when spec_patterns.boundary is true."""
    arche = cfg["project"]["archetype"]
    return f"""# Contracts steering (R4 G5/G8)

> Generated because `retrofit.spec_patterns.boundary` is true.

Boundary specs formalize the implicit contracts at integration points —
where this project meets other services, libraries, or downstream
consumers. Per RETROFIT.md R4 step 3 and the per-archetype patterns:

## For archetype `{arche}`

{("Service/API — OpenAPI YAML per route, plus failure modes / SLOs / "
  "versioning. Validate against `inventory/traffic-sample.json` if "
  "captured (G18)."
  if arche in ("service", "fullstack") else
  "Library/SDK — the public API surface IS the boundary "
  "(`__init__.py`, `index.ts`, `*.pyi`). semver discipline on every "
  "change."
  if arche == "library" else
  "Platform — cross-component contract files; consult per-component "
  "boundary specs."
  if arche == "platform" else
  "Generic — list integration points and capture the contract shape "
  "for each.")}

## Integration points (operator populates)

| # | Integration point | Contract artifact | Spec |
|---|---|---|---|
| 1 | _(name)_ | _(OpenAPI / JSON Schema / .proto)_ | _(path to spec)_ |

## How to add a new boundary spec

1. Run `boundary-spec <integration-point>` (Sonnet skill).
2. Review the generated machine-readable artifact + acceptance criteria
   (EARS notation recommended).
3. Validate against captured traffic if available
   (`inventory/traffic-sample.json`).
4. Ratify in this file; the cross-component contract gate enforces
   integrity going forward.
"""


def _retrofit_migration(cfg):
    """Emitted only when spec_patterns.migration is true."""
    return """# Migration steering (R4 G7/G8)

> Generated because `retrofit.spec_patterns.migration` is true — this
> project has an in-flight strangler-fig modernization or operator
> anticipates one.

## Target state

_(operator populates: what the modernized system looks like)_

## Strangler approach

_(operator populates per the per-archetype table in RETROFIT.md
§"Project Archetypes": proxy/façade for Service; re-export for Library;
prompt-version routing for AI/agent; per-component cutover for Platform.)_

## Incremental steps

| # | Step | Independently deployable? | Rollback path | Success criteria |
|---|---|---|---|---|
| 1 | _(operator populates)_ | yes/no | _(how)_ | _(criteria)_ |

## Anti-corruption layer (G19)

_(operator populates: where the translation layer lives; how it prevents
legacy concepts leaking into the new domain model.)_

## How to add migration step specs

Run `migration-plan <step-name>` (Opus skill — judgment work) to
decompose a deprecated pattern's removal into safe, reversible steps.
"""


def _retrofit_compliance(cfg):
    """Emitted only when regulatory_regimes is non-empty."""
    regimes = cfg["retrofit"]["regulatory_regimes"]
    body = ["# Compliance steering (R5 G20)",
            "",
            "> Generated because `retrofit.regulatory_regimes` is non-"
            "empty:",
            ""]
    for r in regimes:
        body.append(f"- **{r}**")
    body += [
        "",
        "## Applicable controls",
        "",
        "_(operator populates per framework. Reference RETROFIT.md R5 "
        "step 3 + R0 step 10 for the per-framework checklist.)_",
        "",
        "## Where compliance artifacts live",
        "",
        "| Artifact | Path |",
        "|---|---|",
        "| POA&M (FedRAMP) | _(operator populates)_ |",
        "| DHF (medical device) | _(operator populates)_ |",
        "| SSP / System Security Plan | _(operator populates)_ |",
        "| Records of processing (GDPR) | _(operator populates)_ |",
        "",
        "## The retrofit as a change-control event",
        "",
        "Per RETROFIT.md R7 step 9: the retrofit itself is typically a "
        "'significant change' / change-control event. Document it in "
        "the existing change-control system (POA&M update for FedRAMP; "
        "DHF entry for medical device; ROC update for PCI; records of "
        "processing update for GDPR; etc.).",
        "",
        "## Audit-trail continuity rules",
        "",
        "_(operator populates: which actions must be audit-logged; "
        "audit window length; where logs live.)_",
        "",
        "## R8.A.8 hook stubs (documentation only in v1.3 — deferred "
        "enforcement in v1.4)",
        "",
        "- Audit log hook (SOC 2 / HIPAA / FedRAMP)",
        "- PHI redaction hook (HIPAA)",
        "- Cardholder data redaction hook (PCI-DSS)",
        "- EOL dependency block (PCI-DSS Requirement 6)",
        "- Cross-component safeguard uniformity check (HIPAA)",
        "",
        "Rely on operator's existing audit-log infrastructure for v1.3 "
        "scope. Track gaps as `debt.md` entries.",
    ]
    return "\n".join(body) + "\n"


def _retrofit_rollout_schedule(cfg):
    """Default 4-week graduated warn→block schedule per R8.A.6.
    The hooks parse the ROLLOUT_WEEK marker at runtime to know which
    week's behavior to apply. The operator updates this file (changing
    the marker) to advance the rollout."""
    return """# Hook rollout schedule (R8.A.6, G14)

> Generated by retrofit-installer from bootstrap.config.yaml.

Pre-existing developers have ungated commit habits. Per the MLOps
Coding Course + GitGuardian: **graduate the rollout warn → block per
hook over 2-4 weeks**, monitor bypass rates, adjust accordingly.

## Default schedule

| Week | Status | What blocks | What warns |
|---|---|---|---|
| Week 1 | All hooks installed | Nothing (warn-only mode) | Everything that would block in steady state |
| Week 2 | Lint and format hooks block | Lint, format | Spec gate, test gate, TDD gate, eval gate |
| Week 3 | Test gate blocks | Lint, format, test | Spec gate, TDD gate, eval gate |
| Week 4+ | Steady state | All hooks | (none) |

## Operator-controlled current week

The hooks read the marker below at runtime to know which week's
behavior to apply. **To advance the rollout**, edit the integer below
and re-save. No installer re-run needed.

<!-- ROLLOUT_WEEK: 1 -->

(Valid values: 1 | 2 | 3 | 4+; 4+ is steady state — all hooks block.)

## Bypass-rate monitoring (G14)

Track `--no-verify` usage. Reasonable target per DevSecOps Now:
**90%+ pass rate** on each hook. Sustained >10% bypass means the hook
is too strict, buggy, or the rollout schedule needs adjustment.
Don't tune by tightening; tune by understanding why bypasses happen.

## Notes

- Operator can extend the schedule (e.g., for projects with low pre-
  existing test coverage, extend Week 3 longer).
- Operator can compress the schedule (e.g., for projects with high
  spec discipline already, jump from Week 1 to Week 4 directly).
- The fail-safe default is **steady state** (week 4+): if the hooks
  cannot read this file at runtime they assume steady state and
  ENFORCE every gate. Removing this file or making it unreadable
  does NOT degrade to warn-only.
"""


def _retrofit_worktree_budget(cfg):
    """Emitted only when codebase_size_gb >= 1 (RETROFIT.md R8.A.7)."""
    size_gb = cfg["retrofit"]["codebase_size_gb"]
    return f"""# Worktree resource budget (R8.A.7, G16)

> Generated because `retrofit.codebase_size_gb` is {size_gb} (≥ 1).

Per Augment Code 2026: a 2GB codebase consumes ~10GB of disk in a
20-minute multi-worktree session. For this codebase:

## Expected resource use

- **Per-worktree disk usage:** ~{size_gb * 5} GB (5x codebase size).
- **Per-worktree database instance:** name with per-worktree-uuid prefix.
- **Per-worktree Docker volume:** name with per-worktree-uuid prefix.

## Recommended posture

{("Codebase exceeds 5GB — recommend **sequential worktrees over "
  "parallel** unless operator has substantial disk headroom."
  if size_gb > 5 else
  "Codebase between 1GB and 5GB — parallel worktrees acceptable; "
  "monitor disk usage during long sessions.")}

## Implementer subagent

The implementer subagent body references this budget; for sequential
worktrees, the operator configures `implementer` invocations to avoid
parallel dispatch (no spec-decompose parallelism map).
"""


def _retrofit_skill_body(name: str, desc: str, model: str,
                          extra: str = "") -> str:
    """Faithful stub per OD-6 (greenfield standard: frontmatter + intent
    + 2-4 sentence behavior summary). Operator completes deep prompt
    engineering separately from the structural scaffolding."""
    return (f"---\nname: {name}\nmodel: {model}\n"
            f"description: {desc}\n---\n\n# {name}\n\n{desc}\n"
            + (extra + "\n" if extra else ""))


def _retrofit_skills(cfg) -> dict:
    """Retrofit-only skills. Standard greenfield skills come from the
    unmodified _skills() — these are net new files for retrofit. Model
    assignments per RETROFIT-COMPANION's Model Assignment Strategy."""
    arche = cfg["project"]["archetype"]
    out: dict[str, str] = {
        "legacy-spec": _retrofit_skill_body(
            "legacy-spec",
            "Generate a brief change spec for a legacy module being "
            "modified for the first time. Output is "
            ".claude/specs/<slug>/requirements.md documenting current "
            "behavior plus the change being made. Used in touch-based "
            "backfill.",
            "sonnet"),
        "legacy-pin-test": _retrofit_skill_body(
            "legacy-pin-test",
            "Generate a characterization test for a legacy module before "
            "modification. Captures current observable behavior (input/"
            "output, golden output, snapshot) so unintended changes "
            "surface. Per Feathers' pinning-test technique.",
            "sonnet",
            "> Used by R2/R6/R8.A whenever code in `inventory/"
            "danger-zones.md` or in the legacy allowlist is about to be "
            "modified."),
        "boundary-spec": _retrofit_skill_body(
            "boundary-spec",
            "Generate a dependency boundary spec (OpenAPI / JSON Schema "
            "/ Protobuf) for a service contract or public API surface. "
            "Validates against inventory/traffic-sample.json if "
            "available (G18).",
            "sonnet"),
        "migration-plan": _retrofit_skill_body(
            "migration-plan",
            "Decompose a deprecated pattern's removal into safe, "
            "reversible steps. Judgment work — use when R5/R7 generated "
            "concrete migration plans.",
            "opus"),
        "inventory-scan": _retrofit_skill_body(
            "inventory-scan",
            "Walk the repo and produce .claude/inventory/*.md (R0). "
            "Pattern work — file-tree walking, language detection, "
            "dependency parsing.",
            "sonnet"),
        "prior-art-audit": _retrofit_skill_body(
            "prior-art-audit",
            "Read existing .claude/ agents, roles, CLAUDE.md sections, "
            "ad-hoc workflow docs and judge 'what is this trying to do, "
            "what should it become.' Judgment-heavy.",
            "opus"),
        "convention-categorize": _retrofit_skill_body(
            "convention-categorize",
            "The single highest-leverage call in the protocol. Decide "
            "Canonical / Deprecated / Intentional Variation / Modernize "
            "for each observed pattern. A bad call here ships flawed "
            "steering for the lifetime of the project.",
            "opus"),
        "debt-classify": _retrofit_skill_body(
            "debt-classify",
            "Mechanical categorization of debt entries against known "
            "templates (severity by impact, source citation). Operator-"
            "confirmed.",
            "sonnet"),
        "ticket-to-spec": _retrofit_skill_body(
            "ticket-to-spec",
            "Convert an existing ticket (Linear / Jira / GitHub Issues / "
            "in-repo tickets/) into a requirements.md spec stub with "
            "original-ticket frontmatter. Pattern work.",
            "sonnet"),
    }
    # Archetype-specific retrofit skills.
    if arche == "ai-agent":
        out["prompt-pinning-eval"] = _retrofit_skill_body(
            "prompt-pinning-eval",
            "Generate a characterization eval (golden-dataset baseline) "
            "for a prompt before modification. The AI/agent equivalent "
            "of a pinning test.",
            "sonnet")
    if arche == "data-ml":
        out["dataset-pin-test"] = _retrofit_skill_body(
            "dataset-pin-test",
            "Generate reproducibility-validation tests for a data "
            "pipeline stage (dataset version, env, seed, output "
            "checksum). The data-pipeline equivalent of a pinning test.",
            "sonnet")
    return out


def _retrofit_commands(cfg) -> dict:
    """Slash-command pointers for the retrofit skills."""
    out: dict[str, str] = {}
    for name in _retrofit_skills(cfg).keys():
        out[name] = (
            f"---\ndescription: Invoke the `{name}` retrofit skill.\n"
            f"---\n\nInvoke the `{name}` skill.\n")
    return out


def _retrofit_implementer_agent(cfg):
    """Retrofit-flavor implementer (override of greenfield). Adds pin-
    first discipline + danger-zone awareness per RETROFIT R8.C."""
    w = cfg["workflow"]
    return (f"---\nname: implementer\nmodel: {w['implementer_model']}\n"
            f"isolation: worktree\n"
            f"description: Use when an approved spec task is ready for "
            f"implementation. Reads .claude/specs/<slug>/tasks/<id>.md. "
            f"Retrofit-flavor: honors pin-first discipline (G6) on "
            f"danger-zone and legacy-allowlist files.\n---\n\n"
            f"# implementer (retrofit-flavor)\n\n"
            f"Self-contained: subagents do not inherit the default system "
            f"prompt. Read steering + spec + task, implement, run gates, "
            f"commit, log decisions via decision-log.\n\n"
            f"## Retrofit-specific behavior\n\n"
            f"1. **Legacy allowlist (touch-based backfill).** When the "
            f"task touches a file in `.claude/steering/spec-strategy.md`'s "
            f"legacy allowlist:\n"
            f"   - Read the file to understand current state.\n"
            f"   - Run `/spec-new` for the module via the `legacy-spec` "
            f"skill (touch-based backfill).\n"
            f"   - The spec is brief — current behavior + the change.\n"
            f"   - After modification, remove the file from the legacy "
            f"allowlist (it now has a spec).\n\n"
            f"2. **Pin-first discipline (G6).** When the task touches a "
            f"file in `inventory/danger-zones.md` OR in the legacy "
            f"allowlist, run `legacy-pin-test` BEFORE any modification:\n"
            f"   - The pinning test must pass against current unchanged "
            f"code.\n"
            f"   - If not, PAUSE and surface 'current behavior is "
            f"different from what the test captures — operator review "
            f"needed' (decision-required alarm).\n"
            f"   - Per Feathers' pinning-test technique.\n\n"
            f"3. **AI/agent archetype:** when the task modifies a prompt "
            f"file, run `prompt-pinning-eval` first (analogous to "
            f"`legacy-pin-test` for code) to capture current behavior on "
            f"a golden dataset.\n\n"
            f"4. **Worktree budget (G16):** consult "
            f"`.claude/hooks/worktree-budget.md` (if present). For "
            f"codebases over 5GB, prefer sequential to parallel "
            f"worktrees.\n")


def _retrofit_reviewer_agent(cfg):
    """Retrofit-flavor reviewer (override of greenfield). Adds danger-zone
    rule (G10) + pin-first verification (G6) per RETROFIT R8.C."""
    w = cfg["workflow"]
    return (f"---\nname: reviewer\nmodel: {w['reviewer_model']}\n"
            f"effort: high\ntools: Read, Grep, Glob, Bash\n"
            f"description: Use after implementer commits a task. Reviews "
            f"diff against spec's acceptance criteria and principles.md. "
            f"Retrofit-flavor: enforces danger-zone rule (G10) + pin-"
            f"first verification (G6).\n---\n\n# reviewer (retrofit-flavor)\n\n"
            f"Read-only by construction (no Edit/Write). Return issues or "
            f"approval.\n\n"
            f"## Retrofit-specific behavior\n\n"
            f"1. **Legacy file review.** When reviewing a diff against a "
            f"file in the legacy allowlist, check the change against the "
            f"new spec, NOT against all current principles (legacy code "
            f"may not conform — that's tracked in `debt.md`).\n\n"
            f"2. **Danger-zone rule (G10).** When reviewing a diff against "
            f"a file in `inventory/danger-zones.md`, ENFORCE: **no "
            f"architectural change in the same PR as a behavior change**. "
            f"If the diff combines both, REQUEST the operator split the "
            f"PR. Per Tornhill via Fowler 2026: AI-modified unhealthy "
            f"code carries ~30% higher defect risk; combining "
            f"architectural and behavioral changes in unhealthy zones is "
            f"the riskiest pattern.\n\n"
            f"3. **Pin-first verification (G6).** When reviewing a diff "
            f"against a danger-zone or legacy-allowlist file, verify a "
            f"pinning test exists IN THE DIFF. If absent, REQUEST it "
            f"before approval.\n")


def _retrofit_claude_md(cfg):
    """Override of greenfield CLAUDE.md with retrofit-specific escalation
    criteria + retrofit-specific doc refs. Per RETROFIT R8.E.2."""
    flags = cfg["autonomous_modes"]
    queue_section = ""
    if flags["queue_mode_enabled"]:
        queue_section = (
            "\n## Queue mode coordination layer\n\n"
            "`.claude/auto.sh` dispatches per-task wrappers from "
            "`.claude/queue/backlog.md`. The runner does not load this "
            "file; the queue is the coordination surface.\n")
    return f"""# CLAUDE.md (retrofit-flavor)

Thin by design. Steering lives in `.claude/steering/`. Retrofit-specific
context lives in `.claude/debt.md`, `.claude/inventory/`, and
`.claude/steering/spec-strategy.md`.

## Workflow

Per-task lifecycle: spec-review -> spec-decompose -> plan-review -> implement
(decisions logged continuously) -> local gates -> code-review ->
spec-validate -> pr-author.

For LEGACY files (in the allowlist or in danger-zones): pin → spec → modify
(see `spec-strategy.md`).

## Urgent escalations (AI stops and asks)

1. **🔔** A do-not-touch / never-read path needs access or modification.
2. **🔔** A secret or credential is encountered.
3. **🔔** A hook blocks and the fix is not obvious within one attempt.
4. **🔔** A dependency not on the `deps.md` approved list is needed.
5. **🔔** Implementation reveals the spec was wrong.
6. **🔔** Modifying a file in the legacy allowlist WITHOUT first creating
   a spec via touch-based backfill.
7. **🔔** Modifying a file in `inventory/danger-zones.md` WITHOUT first
   generating a `legacy-pin-test` (or for AI/agent prompt files, a
   `prompt-pinning-eval`).

Non-urgent (in-chat only): ambiguous acceptance criteria, two reasonable
approaches with material tradeoffs, spec version drift mid-task, a
categorization in `tech.md` that looks wrong in light of new evidence.

The escalation list is the contract. If the agent escalates outside it,
fix steering — do not override in-session.
{queue_section}
## Retrofit-specific references

- `.claude/debt.md` — known issues registry (R3); retrofit does NOT fix
  these. Add entries as new debt is identified.
- `.claude/steering/spec-strategy.md` — forward-only / touch-based /
  bulk decision + legacy allowlist + retrofit-active master switch.
- `.claude/steering/workflow-source-of-truth.md` — PM artifact strategy
  (A/B/C) and ticket migration disposition.
- `.claude/hooks/rollout-schedule.md` — graduated warn→block schedule.
  Update the `<!-- ROLLOUT_WEEK: N -->` marker to advance the rollout.
- `.claude/inventory/` — codebase audit at retrofit time (frozen).
- `.claude/.retrofit-state.json` — retrofit progress + brownfield
  milestone tracking. **Autonomous modes opted-in here SCAFFOLD but do
  NOT enable**; flip `*_enabled` only after the brownfield milestone
  is green (RETROFIT.md §"Autonomous Modes in Retrofit").

## Retrofit completion (R7)

When `retrofit_active: false` in `.retrofit-state.json`, retrofit is
complete: the spec-gate-commit hook operates normally (no more
allowlisting `.claude/` writes for the retrofit itself); the brownfield
trust milestones for autonomous modes start ticking.
"""


def _retrofit_gitignore(cfg):
    """Override of greenfield .claude/.gitignore with retrofit-specific
    patterns. Per RETROFIT R8.C."""
    base = [
        "logs/", ".last-test-pass", ".last-eval-pass",
        "sessions/.session-*", "sessions/.drift-*",
        "sessions/.decision-pending-*", "sessions/.quiet-*",
        "sessions/.loop-active-*", "sessions/.goal-active-*",
        "sessions/.loop-complete-*", "sessions/.loop-halt-*",
        "sessions/.iteration-summary-*", "sessions/.evaluator-feedback-*",
        ".installer-manifest.json", ".bootstrap-state.json",
        ".bootstrap-state.json.lock", ".bootstrap-incomplete",
        # Retrofit-specific (per RETROFIT R8.C gitignore block):
        ".retrofit-state.json",
        ".bootstrap-state.json.pre-1.7", ".bootstrap-state.json.pre-1.8",
        ".bootstrap-state.json.pre-1.9",
        "inventory/.scan-cache-*",
        "sessions/.bypass-count-*",
    ]
    if cfg["autonomous_modes"]["queue_mode_enabled"]:
        base += ["queue/.run-active", "queue/.halt", "queue/.resume"]
    out = ["# bootstrap-installer generated (retrofit-flavor)"]
    out.extend(base)
    return "\n".join(out) + "\n"


# Append all new retrofit entries to TEMPLATES. The greenfield entries
# above are AST-unmodified (D2 golden test gates this).
TEMPLATES = {
    "product": _product,
    "tech": _tech,
    "deps": _deps,
    "secrets": _secrets,
    "structure": _structure,
    "principles": _principles,
    "cicd": _cicd,
    "cicd_optout": _cicd_optout,
    "tools": _tools,
    "hook": _hook_body,
    "settings_json": _settings_json,
    "audio_config": _audio_config,
    "skills": _skills,
    "commands": _commands,
    "agents": _agents,
    "backlog": _backlog,
    "auto_config": _auto_config,
    "auto_sh": _auto_sh,
    "loop_sh": _loop_sh,
    "loop_config": _loop_config,
    "goal_loop_sh": _goal_loop_sh,
    "goal_config": _goal_config,
    "claude_md": _claude_md,
    "specs_index": _specs_index,
    "gitignore": _gitignore,
    # Retrofit additions (new template fns; greenfield never reaches these).
    "retrofit_inventory_readme": _retrofit_inventory_readme,
    "retrofit_debt": _retrofit_debt,
    "retrofit_spec_strategy": _retrofit_spec_strategy,
    "retrofit_workflow_sot": _retrofit_workflow_sot,
    "retrofit_contracts": _retrofit_contracts,
    "retrofit_migration": _retrofit_migration,
    "retrofit_compliance": _retrofit_compliance,
    "retrofit_rollout_schedule": _retrofit_rollout_schedule,
    "retrofit_worktree_budget": _retrofit_worktree_budget,
    "retrofit_skills": _retrofit_skills,
    "retrofit_commands": _retrofit_commands,
    "retrofit_implementer_agent": _retrofit_implementer_agent,
    "retrofit_reviewer_agent": _retrofit_reviewer_agent,
    "retrofit_claude_md": _retrofit_claude_md,
    "retrofit_gitignore": _retrofit_gitignore,
}
