"""
File-body templates.

Every entry in TEMPLATES is a pure function of the resolved config, which is
what makes the installer deterministic: same cfg in => same bytes out. No
timestamps, no randomness, no environment reads in any body.
"""

from __future__ import annotations

import json

PROTOCOL_VERSION = "1.9.0"


# --------------------------------------------------------------------------- #
# Steering docs
# --------------------------------------------------------------------------- #
def _product(cfg):
    p = cfg["project"]
    return f"""# Product Steering

> Generated by bootstrap-installer from bootstrap.config.yaml.
> Edit freely; the installer will not overwrite local edits without --force.

**Project:** {p['name']}
**Archetype:** {p['archetype']}
**PRD tier:** {p['prd_tier']}
**PRD:** `{p['prd_path']}`

## Why this exists

(Filled from the PRD during the wizard's product phase. This stub records the
classification so downstream agents have stable steering even before the PRD
section is expanded.)

## Primary user & success criterion

See `{p['prd_path']}`. Update this file when the product thesis changes.
"""


def _tech(cfg):
    p = cfg["project"]
    c = cfg["commands"]
    return f"""# Technical Steering

**Shell:** {p['shell']}
**Archetype:** {p['archetype']}

## Project commands

| Purpose   | Command |
|-----------|---------|
| Test      | `{c['test'] or 'TODO: set commands.test in bootstrap.config.yaml'}` |
| Lint      | `{c['lint'] or 'TODO: set commands.lint'}` |
| Format    | `{c['format'] or 'TODO: set commands.format'}` |
| Typecheck | `{c['typecheck'] or '(none)'}` |
| CI local  | `{c['ci_local'] or '(none)'}` |

These commands are the contract the hooks enforce. If a cell says TODO the
corresponding gate will fail loudly until it is filled.
"""


def _deps(cfg):
    approved = cfg["deps"]["approved"]
    lines = "\n".join(f"- `{d}`" for d in approved) or "_(none yet)_"
    return f"""# Dependency Policy

New runtime/build dependencies must be on this list or explicitly approved
in-session (which then updates this file). The dependency gate hook enforces
this at install-command time.

## Approved

{lines}

## Adding a dependency

1. Justify the dependency against `principles.md`.
2. Add it here in the same change.
3. The dependency gate stops blocking once the package appears above.
"""


def _secrets(cfg):
    s = cfg["secrets"]
    paths = "\n".join(f"- `{p}`" for p in s["never_read_paths"])
    return f"""# Secrets & Sensitive-Data Policy

## Files the AI must never read

{paths}

The secrets gate hook blocks Read/Write/Edit on these paths. Unlike other
gates this one blocks mid-plan by design - secret exposure is catastrophic.

## On encountering a secret in code

Stop, alert the operator, do not echo the secret into any output, recommend
rotation.

## Rotation

{s['rotation_policy']}
"""


def _structure(cfg):
    return """# Structure Steering

Where things live so agents stop inventing file locations.

```
.claude/          harness: steering, hooks, skills, commands, agents, specs
docs/prd/         product requirements
src/              application code
tests/            tests, mirroring src/ layout
```

## Spec slug naming

Slugs for `specs/INDEX.md` rows and `/spec-new` invocations are derived
deterministically. Apply rules in order; first match wins:

1. **Primary output file.** If the deliverable names a primary output file,
   the slug is the kebab-cased stem of that filename
   (`docs/doc-grammar.md` -> `doc-grammar`).
2. **Noun phrase.** Otherwise kebab-case the deliverable's PRD name, drop
   articles/connectives, preserve numbers.
3. **Collision.** Append the PRD section number (`grammar-86`).
"""


def _principles(cfg):
    pr = cfg["principles"]
    ranked = "\n".join(f"{i+1}. {x}" for i, x in enumerate(pr["ranked"]))
    tb = "\n".join(f"- {x}" for x in pr["tiebreakers"]) or \
        "- _(add explicit tiebreakers for principles in tension)_"
    return f"""# Principles Steering

Ranked, project-specific. Generic acronyms (DRY/SOLID) are noise without
ranking and project rules.

## Ranked principles

{ranked}

## Tiebreakers

{tb}

## TDD policy

**{pr['tdd_policy']}**
""" + ("\nThe TDD gate hook enforces tests-before-source.\n"
        if pr["tdd_policy"] == "required" else "")


def _cicd(cfg):
    c = cfg["commands"]
    return f"""# CI/CD Steering

## Pipeline

Branch model and provider are project decisions; record them here.

PR checks must at minimum run:
- `{c['test'] or 'TODO: commands.test'}`
- `{c['lint'] or 'TODO: commands.lint'}`

## Agent stopping point

The agent's last action is **PR open** (or PR merge). The agent never deploys.
The CI-mirror hook runs these same checks locally before push.
"""


def _cicd_optout(cfg):
    c = cfg["commands"]
    return f"""# CI/CD Steering

**No CI/CD** (operator opted out in Phase 0).

The agent still runs the test command locally:
`{c['test'] or 'TODO: set commands.test'}`

Placeholder for future CI addition. Re-run the wizard's CI setup to populate.
"""


def _tools(cfg):
    m = cfg["mcp"]
    inst = "\n".join(
        f"- **{s.get('name','?')}** - `{s.get('command','?')}`"
        for s in m["servers"]) or "_(none - minimal start, by design)_"
    rej = "\n".join(
        f"- {r.get('name','?')}: {r.get('reason','')}"
        for r in m["rejected"]) or "_(none recorded)_"
    return f"""# Tools & MCP Steering

Principle: subagents and worktrees prevent drift; MCP tools are for capability
gaps, not drift gaps. Every server costs context budget.

## Built-ins relied upon

- Worktree-isolated subagents
- Tool search (deferred MCP tool loading)
- Hooks (Phase 6)
- Auto memory (native, on by default)

## Installed MCP servers

{inst}

## Considered & rejected

{rej}

## Don't add (guardrail)

Multiple overlapping memory MCPs; a memory MCP before auto-memory tried;
MCPs wrapping shell tools you already have; sequential-thinking MCPs.
"""


# --------------------------------------------------------------------------- #
# Hooks
# --------------------------------------------------------------------------- #
_HOOK_HEADER = """#!/usr/bin/env bash
# Generated by bootstrap-installer. Edit with care - security-relevant.
# Exit codes: 0 allow | 1 hook-internal error (tool proceeds) | 2 block.
#
# Security/correctness (BOOTSTRAP.md 6.D checklist):
#  * No eval/dynamic execution: the Python fallback walks keys explicitly.
#  * stdin is consumed exactly once into $INPUT; the fallback receives it via
#    the environment, NOT by re-reading already-consumed stdin (the bug that
#    silently disabled every parsing hook when jq was absent).
set -euo pipefail
LOG="${CLAUDE_PROJECT_DIR:-.}/.claude/logs/hooks.log"
mkdir -p "$(dirname "$LOG")"
log(){ printf '%s %s\\n' "$(date -u +%FT%TZ)" "$*" >>"$LOG"; }
INPUT="$(cat || true)"
have_jq(){ command -v jq >/dev/null 2>&1; }
# jget '.a.b' -> value at path or empty. Safe with or without jq.
jget(){
  local jqpath="$1"
  if have_jq; then
    printf '%s' "$INPUT" | jq -r "$jqpath // empty" 2>/dev/null || true
  else
    INPUT="$INPUT" python3 - "${jqpath#.}" <<'PYEOF' 2>/dev/null || true
import json, os, sys
raw = os.environ.get("INPUT", "")
try:
    d = json.loads(raw) if raw.strip() else {}
except Exception:
    sys.exit(0)
cur = d
for k in sys.argv[1].split("."):
    if isinstance(cur, dict) and k in cur:
        cur = cur[k]
    else:
        sys.exit(0)
if cur is not None and not isinstance(cur, (dict, list)):
    sys.stdout.write(str(cur))
PYEOF
  fi
}
"""


def _hook_body(name: str, cfg: dict):
    c = cfg["commands"]
    sec_paths = cfg["secrets"]["never_read_paths"]
    th = cfg["hooks"]

    if name == "spec-gate-entry":
        return _HOOK_HEADER + '''
# UserPromptSubmit: warn (do not block) if writing files with no active spec.
PROMPT="$(jget '.prompt')"
case "$PROMPT" in
  *write*|*edit*|*create*|*implement*)
    if [ ! -s "${CLAUDE_PROJECT_DIR:-.}/.claude/specs/INDEX.md" ]; then
      echo "No active spec detected. Consider /spec-new before writing." >&2
    fi ;;
esac
log "spec-gate-entry ok"
exit 0
'''

    if name == "spec-gate-commit":
        return _HOOK_HEADER + '''
# PreToolUse Bash(git commit): block files not referenced by an active spec.
CMD="$(jget '.tool_input.command')"
case "$CMD" in
  *"git commit"*)
    PROJ="${CLAUDE_PROJECT_DIR:-.}"
    INDEX="$PROJ/.claude/specs/INDEX.md"
    staged="$(git diff --cached --name-only 2>/dev/null || true)"
    [ -z "$staged" ] && { log "spec-gate-commit: no staged files"; exit 0; }
    # Collect the corpus of spec/task files once. nullglob-safe.
    corpus=""
    [ -f "$INDEX" ] && corpus="$INDEX"
    for d in "$PROJ"/.claude/specs/*/tasks/; do
      [ -d "$d" ] || continue
      for tf in "$d"*; do [ -f "$tf" ] && corpus="$corpus $tf"; done
    done
    if [ -z "$corpus" ]; then
      echo "Commit blocked: no active spec/task files exist yet." >&2
      echo "Run /spec-new before committing." >&2
      exit 2
    fi
    miss=""
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      # Word-boundary match on the path or its basename, not a loose
      # substring (S-3: 'a.py' must not be "referenced" by 'data.py').
      b="$(basename "$f")"
      if ! grep -rqE "(^|[^[:alnum:]_./-])($f|$b)([^[:alnum:]_-]|$)" \
             $corpus 2>/dev/null; then
        miss="$miss $f"
      fi
    done <<< "$staged"
    if [ -n "$miss" ]; then
      echo "Commit blocked: files not referenced by any active spec:$miss" >&2
      echo "Run /spec-new or add them to a tasks/*.md file." >&2
      exit 2
    fi ;;
esac
log "spec-gate-commit ok"
exit 0
'''

    if name == "secrets-gate":
        # S-5 fix: patterns emitted as a quoted heredoc list, never
        # interpolated into shell. Each pattern is matched against both the
        # basename and the full path; '**' is normalized to '*' so a
        # directory glob like 'secrets/**' actually matches under `case`.
        #
        # T-1 fix: a deny-list pattern like '.env*' was previously matched
        # ONLY as a prefix glob, so realistic dotenv names that do not START
        # with the pattern - 'config.env', 'prod.env', 'staging.env' - were
        # NOT blocked and the agent could read them (a fail-open in the one
        # hook BOOTSTRAP.md 6.D requires to fail loudly). For a security
        # deny-list the correct bias is to over-match, never under-match, so
        # each pattern is now also tried with an implicit leading '*' (suffix
        # form) and the comparison is case-insensitive (so '.PEM'/'.ENV'
        # variants are caught too). This only ever WIDENS the block set; no
        # path that was blocked before becomes allowed.
        pat_body = "\n".join(sec_paths)
        return _HOOK_HEADER + f'''
# PreToolUse Read/Write/Edit: hard-block never-read paths. Blocks mid-plan
# by design (secret exposure is catastrophic).
TARGET="$(jget '.tool_input.file_path')"
[ -z "$TARGET" ] && {{ log "secrets-gate: no path"; exit 0; }}
base="$(basename "$TARGET")"
# Case-insensitive matching ('.PEM'/'.ENV' are just as sensitive) done with
# bash's built-in `nocasematch` - NO external binary (T-1 follow-up: an
# earlier `tr`-based version exited 127 when `tr` was off PATH, which under
# the exit-code convention would let the secret read proceed; a pure-bash
# `shopt` cannot fail open that way).
shopt -s nocasematch
PAT_FILE="$(mktemp)"
trap 'rm -f "$PAT_FILE"' EXIT
cat >"$PAT_FILE" <<'PAT_EOF'
{pat_body}
PAT_EOF
while IFS= read -r pat; do
  [ -z "$pat" ] && continue
  cpat="$(printf '%s' "$pat" | sed 's/\\*\\*/*/g')"   # ** -> * for `case`
  # Match the pattern as-given (prefix/exact) AND with an implicit leading
  # '*' (suffix form) so 'config.env' is caught by '.env*'. Deny-list =>
  # over-match is safe; under-match is the catastrophic failure.
  case "$base" in
    $cpat|*$cpat)
      echo "BLOCKED: $TARGET matches never-read pattern $pat" >&2
      log "secrets-gate BLOCK $TARGET"; exit 2 ;;
  esac
  case "$TARGET" in
    $cpat|*/$cpat|*$cpat)
      echo "BLOCKED: $TARGET matches never-read pattern $pat" >&2
      log "secrets-gate BLOCK $TARGET"; exit 2 ;;
  esac
done <"$PAT_FILE"
log "secrets-gate ok $TARGET"
exit 0
'''

    if name == "test-gate":
        cmd = c["test"] or "echo 'TODO: commands.test unset' && exit 1"
        return _HOOK_HEADER + f'''
# PreToolUse git commit: block unless tests passed since last source edit.
CMD="$(jget '.tool_input.command')"
case "$CMD" in
  *"git commit"*)
    MARK="${{CLAUDE_PROJECT_DIR:-.}}/.claude/.last-test-pass"
    newest_src="$(find src -type f -newer "$MARK" 2>/dev/null | head -1 || true)"
    if [ ! -f "$MARK" ] || [ -n "$newest_src" ]; then
      echo "Running test gate: {cmd}" >&2
      if ( {cmd} ); then touch "$MARK"; else
        echo "Commit blocked: tests failing." >&2; exit 2; fi
    fi ;;
esac
log "test-gate ok"
exit 0
'''

    if name == "format-lint-gate":
        fmt = c["format"] or "true"
        lint = c["lint"] or "true"
        return _HOOK_HEADER + f'''
# PostToolUse Write/Edit: non-blocking format + lint feedback.
( {fmt} ) >/dev/null 2>&1 || echo "format reported issues" >&2
( {lint} ) 2>&1 | tail -20 >&2 || true
log "format-lint-gate ran"
exit 0
'''

    if name == "ci-mirror":
        ci = c["ci_local"] or c["test"] or "true"
        return _HOOK_HEADER + f'''
# PreToolUse git push: run the same checks CI runs, locally.
CMD="$(jget '.tool_input.command')"
case "$CMD" in
  *"git push"*)
    echo "CI mirror: {ci}" >&2
    if ! ( {ci} ); then echo "Push blocked: CI mirror failed." >&2; exit 2; fi
  ;;
esac
log "ci-mirror ok"
exit 0
'''

    if name == "cost-log":
        return _HOOK_HEADER + '''
# Stop hook: session-end cost summary. Guards against infinite loop.
if [ "$(jget '.stop_hook_active')" = "true" ]; then
  exit 0
fi
OUT="${CLAUDE_PROJECT_DIR:-.}/.claude/logs/cost.jsonl"
mkdir -p "$(dirname "$OUT")"
printf '{"event":"session_end","ts":"%s"}\\n' "$(date -u +%FT%TZ)" >>"$OUT"
log "cost-log appended"
exit 0
'''

    if name == "dependency-gate":
        # S-5 fix: approved names are emitted as a quoted, newline-delimited
        # heredoc body - never interpolated into a shell `case` pattern, so a
        # name containing shell metacharacters cannot corrupt the script.
        # S-2 fix: every token after the install/add verb is checked (handles
        # multiple packages and skips flags), not just the first via a fragile
        # single sed.
        approved = cfg["deps"]["approved"]
        approved_body = "\n".join(approved)
        return _HOOK_HEADER + f'''
# PreToolUse Bash: block package installs not on the approved list.
CMD="$(jget '.tool_input.command')"
APPROVED_FILE="$(mktemp)"
trap 'rm -f "$APPROVED_FILE"' EXIT
cat >"$APPROVED_FILE" <<'APPROVED_EOF'
{approved_body}
APPROVED_EOF
is_approved(){{ grep -qxF -- "$1" "$APPROVED_FILE"; }}
case " $CMD " in
  *" npm install "*|*" npm i "*|*" pip install "*|*" pip3 install "*\
|*" yarn add "*|*" pnpm add "*)
    # Strip everything up to and including the verb, then inspect each token.
    rest="${{CMD#*install }}"; rest="${{rest#*add }}"; rest="${{rest#*i }}"
    blocked=""
    skip_next=0
    for tok in $rest; do
      if [ "$skip_next" = "1" ]; then skip_next=0; continue; fi
      case "$tok" in
        # Value-taking flags consume the NEXT token (a file/path, not a pkg):
        -r|--requirement|-e|--editable|-c|--constraint|-t|--target\
|--prefix|--root|-d|--dest)
          skip_next=1; continue ;;
        -*) continue ;;                       # valueless flags (--upgrade...)
        *) ;;                                 # candidate package token
      esac
      name_only="${{tok%%[<>=@~ ]*}}"          # drop version specifiers
      [ -z "$name_only" ] && continue
      if ! is_approved "$name_only"; then
        blocked="$blocked $name_only"
      fi
    done
    if [ -n "$blocked" ]; then
      echo "Dependency gate: not in deps.md approved list:$blocked" >&2
      echo "Approve in-session and update .claude/steering/deps.md." >&2
      exit 2
    fi ;;
esac
log "dependency-gate ok"
exit 0
'''

    if name == "tdd-gate":
        return _HOOK_HEADER + '''
# PreToolUse Write to source: block unless a matching test was edited newer.
TARGET="$(jget '.tool_input.file_path')"
case "$TARGET" in
  src/*|lib/*)
    base="$(basename "$TARGET")"; stem="${base%.*}"
    if ! find tests -name "*${stem}*" -newer "$TARGET" 2>/dev/null \
         | grep -q .; then
      echo "TDD gate: write a failing test for $stem before $TARGET." >&2
      exit 2
    fi ;;
esac
log "tdd-gate ok"
exit 0
'''

    if name == "eval-gate":
        return _HOOK_HEADER + '''
# PreToolUse git push touching prompt files: require a passed eval.
CMD="$(jget '.tool_input.command')"
case "$CMD" in
  *"git push"*)
    if git diff --name-only HEAD~1 2>/dev/null | grep -qE 'prompt|\\.md$'; then
      MARK="${CLAUDE_PROJECT_DIR:-.}/.claude/.last-eval-pass"
      [ -f "$MARK" ] || { echo "Eval gate: run evals before pushing prompt \
changes." >&2; exit 2; }
    fi ;;
esac
log "eval-gate ok"
exit 0
'''

    if name == "drift-detector":
        tc = th["drift_tool_call_threshold"]
        dm = th["drift_session_duration_minutes"]
        fr = th["drift_file_read_threshold"]
        return _HOOK_HEADER + f'''
# PostToolUse: soft drift notice (tiers 1-2). Tier-3 enforcement is wired
# via settings.json + the loop-cooperation hook when enabled.
CFG="${{CLAUDE_PROJECT_DIR:-.}}/.claude/hooks/audio-alerts.config"
SID="${{CLAUDE_SESSION_ID:-default}}"
ST="${{CLAUDE_PROJECT_DIR:-.}}/.claude/sessions/.drift-state-$SID"
mkdir -p "$(dirname "$ST")"
n=$(( $(cat "$ST" 2>/dev/null || echo 0) + 1 )); echo "$n" >"$ST"
if [ "$n" -ge {tc} ]; then
  echo "DRIFT: $n tool calls (threshold {tc}). Consider /checkpoint." >&2
fi
log "drift-detector n=$n th={tc}/{dm}m/{fr}"
exit 0
'''

    if name == "task-done-alarm":
        return _HOOK_HEADER + '''
# SubagentStop: informational completion cue. Never blocks.
if [ "$(jget '.stop_hook_active')" = "true" ]; then
  exit 0
fi
echo "Task complete. Ready for review." >&2
log "task-done-alarm"
exit 0
'''

    if name == "decision-required-alarm":
        return _HOOK_HEADER + '''
# Notification: persistent cue when the AI hits an urgent escalation.
SID="${CLAUDE_SESSION_ID:-default}"
P="${CLAUDE_PROJECT_DIR:-.}/.claude/sessions/.decision-pending-$SID"
mkdir -p "$(dirname "$P")"; : >"$P"
echo "DECISION REQUIRED: operator action needed (see chat)." >&2
log "decision-required-alarm fired"
exit 0
'''

    if name == "drift-detector-loop-cooperation":
        return _HOOK_HEADER + '''
# Augments tier-3: inside loop.sh/goal-loop.sh, tier-3 fire => checkpoint and
# end turn instead of hard-block-until-/clear. No-ops outside loop/goal mode.
SID="${CLAUDE_SESSION_ID:-default}"
S="${CLAUDE_PROJECT_DIR:-.}/.claude/sessions"
if ls "$S"/.loop-active-* "$S"/.goal-active-* >/dev/null 2>&1; then
  if ls "$S"/.drift-tier3-* >/dev/null 2>&1; then
    echo "tier3-in-loop: write checkpoint and end turn." >&2
  fi
fi
log "drift-loop-cooperation ok"
exit 0
'''

    if name == "iteration-summary-enforcement":
        return _HOOK_HEADER + '''
# goal-loop.sh post-iteration: require a well-formed iteration summary file.
SID="${CLAUDE_SESSION_ID:-default}"
S="${CLAUDE_PROJECT_DIR:-.}/.claude/sessions"
latest="$(ls -t "$S"/.iteration-summary-* 2>/dev/null | head -1 || true)"
if [ -z "$latest" ] || [ ! -s "$latest" ]; then
  echo "iteration-summary missing/empty - feeding error to next iteration." >&2
  exit 1
fi
log "iteration-summary-enforcement ok"
exit 0
'''
    return None


# --------------------------------------------------------------------------- #
# settings.json (Phase 6 wiring)
# --------------------------------------------------------------------------- #
def _settings_json(cfg):
    hooks = cfg["_resolved_hooks"]
    event_map = {
        "spec-gate-entry": ("UserPromptSubmit", None),
        "spec-gate-commit": ("PreToolUse", "Bash"),
        "secrets-gate": ("PreToolUse", "Read|Write|Edit"),
        "test-gate": ("PreToolUse", "Bash"),
        "format-lint-gate": ("PostToolUse", "Write|Edit"),
        "ci-mirror": ("PreToolUse", "Bash"),
        "cost-log": ("Stop", None),
        "dependency-gate": ("PreToolUse", "Bash"),
        "tdd-gate": ("PreToolUse", "Write"),
        "eval-gate": ("PreToolUse", "Bash"),
        "drift-detector": ("PostToolUse", None),
        "task-done-alarm": ("SubagentStop", None),
        "decision-required-alarm": ("Notification", None),
        "drift-detector-loop-cooperation": ("PostToolUse", None),
        "iteration-summary-enforcement": ("Stop", None),
    }
    slow = {"ci-mirror", "test-gate", "format-lint-gate"}
    by_event: dict = {}
    for hk in hooks:
        ev, matcher = event_map[hk]
        entry = {
            "type": "command",
            "command": f"$CLAUDE_PROJECT_DIR/.claude/hooks/{hk}.sh",
        }
        if hk in slow:
            entry["async"] = True
        bucket = by_event.setdefault(ev, [])
        if matcher:
            grp = next((g for g in bucket if g.get("matcher") == matcher), None)
            if grp is None:
                grp = {"matcher": matcher, "hooks": []}
                bucket.append(grp)
            grp["hooks"].append(entry)
        else:
            grp = next((g for g in bucket if "matcher" not in g), None)
            if grp is None:
                grp = {"hooks": []}
                bucket.append(grp)
            grp["hooks"].append(entry)

    settings = {
        "$schema": "https://json.schemastore.org/claude-code-settings.json",
        "_generatedBy": f"bootstrap-installer (protocol {PROTOCOL_VERSION})",
        "hooks": by_event,
    }
    if cfg["mcp"]["servers"]:
        settings["_note_mcp"] = ("MCP servers are added via `claude mcp add`; "
                                 "see .claude/steering/tools.md")
    return json.dumps(settings, indent=2) + "\n"


def _audio_config(cfg):
    th = cfg["hooks"]
    return f"""# === Drift detector ===
drift_enabled=true
drift_tool_call_threshold={th['drift_tool_call_threshold']}
drift_session_duration_minutes={th['drift_session_duration_minutes']}
drift_file_read_threshold={th['drift_file_read_threshold']}
drift_alert_1_delay_minutes=0
drift_alert_2_delay_minutes=10
drift_alert_3_delay_minutes=15
drift_tier3_enforced=true
quiet_mode_overridden_by_drift_tier3=true

# === Task done ===
task_done_enabled=true
task_done_batch_window_seconds=30

# === Decision required ===
decision_required_enabled=true
decision_required_persistent_notification=true

# === Audio ===
audio_enabled=true
audio_file_drift_gentle=~/.claude/sounds/drift-gentle.wav
audio_file_drift_insistent=~/.claude/sounds/drift-insistent.wav
audio_file_drift_firm=~/.claude/sounds/drift-firm.wav
audio_file_task_done=~/.claude/sounds/task-done.wav
audio_file_decision_required=~/.claude/sounds/decision-required.wav

# === Notifications ===
notification_enabled=true
notification_daemon=auto

# === Quiet mode ===
quiet_mode_overridden_by_decision_required=true

# === State retention ===
purge_old_state_after_days=7
"""


# --------------------------------------------------------------------------- #
# Skills / commands / agents (Phase 7)
# --------------------------------------------------------------------------- #
_SKILL_LIST = [
    ("spec-new", "Convert a PRD section into requirements.md (EARS where it "
     "fits). Initializes decisions.md and changelog.md."),
    ("spec-review", "Find contradictions in a spec."),
    ("spec-decompose", "Turn a spec into atomic vertical-slice tasks with a "
     "parallelism map."),
    ("plan-review", "Review decomposition before implementation begins."),
    ("spec-validate", "Check implementation against requirements.md at the "
     "spec version active when implementation began."),
    ("code-review", "Review a diff against spec and principles.md."),
    ("decision-log", "Append non-obvious choices to the spec's decisions.md."),
    ("pr-author", "Generate a PR description: spec link, version, validation "
     "report, decision-log summary."),
    ("checkpoint", "Write a structured session synopsis to "
     ".claude/sessions/<timestamp>-checkpoint.md."),
    ("resume", "Load the most recent checkpoint (or a chosen one)."),
    ("ack-drift", "Acknowledge a drift alert for the session."),
    ("quiet", "Mute audio alerts (session or duration)."),
    ("quiet-task-done", "Mute only the task-done audio."),
]


def _skills(cfg):
    tdd = cfg["principles"]["tdd_policy"]
    out = {}
    for name, desc in _SKILL_LIST:
        rec = ""
        if name in ("spec-review", "code-review"):
            rec = "\n> Recommended: invoke from an Opus session.\n"
        out[name] = (f"---\nname: {name}\n"
                     f"description: {desc}\n---\n\n# {name}\n{rec}\n{desc}\n")
    if tdd != "off":
        out["test-author"] = ("---\nname: test-author\n"
                              "description: Tests-first workflow per task.\n"
                              "---\n\n# test-author\n\nWrite failing tests "
                              "before source, per principles.md TDD policy "
                              f"({tdd}).\n")
    return out


def _commands(cfg):
    out = {}
    for name, desc in _SKILL_LIST:
        explicit = name in ("checkpoint", "resume", "ack-drift")
        note = ("\n_Explicit-only: never auto-invoked by hooks or "
                "subagents._\n" if explicit else "")
        out[name] = (f"---\ndescription: {desc}\n---\n\n"
                     f"Invoke the `{name}` skill.{note}\n")
    return out


def _agents(cfg):
    w = cfg["workflow"]
    return {
        "implementer": (
            f"---\nname: implementer\nmodel: {w['implementer_model']}\n"
            f"isolation: worktree\n"
            f"description: Use when an approved spec task is ready for "
            f"implementation. Reads .claude/specs/<slug>/tasks/<id>.md.\n"
            f"---\n\n# implementer\n\nSelf-contained: subagents do not "
            f"inherit the default system prompt. Read steering + spec + task, "
            f"implement, run gates, commit, log decisions via decision-log.\n"),
        "reviewer": (
            f"---\nname: reviewer\nmodel: {w['reviewer_model']}\n"
            f"effort: high\ntools: Read, Grep, Glob, Bash\n"
            f"description: Use after implementer commits a task. Reviews diff "
            f"against the spec's acceptance criteria and principles.md.\n"
            f"---\n\n# reviewer\n\nRead-only by construction (no Edit/Write). "
            f"Return issues or approval.\n"),
        "integrator": (
            f"---\nname: integrator\nmodel: {w['integrator_model']}\n"
            f"description: Use when two implementer worktrees produced "
            f"conflicting changes to overlapping files.\n"
            f"---\n\n# integrator\n\nResolve merge conflicts between parallel "
            f"task worktrees.\n"),
    }


# --------------------------------------------------------------------------- #
# Queue scaffolding (Phase 9.7)
# --------------------------------------------------------------------------- #
def _backlog(cfg):
    return """# Project backlog

<!-- Ready to run / Operator-only / Deferred are populated by spec-decompose.
     In flight / Completed / Halted are populated and reset by the runner. -->

## Queue policy

max_concurrent_tasks: 2
consecutive_halt_threshold: 3
pause_on_max_iterations: false
pause_on_goal_condition_suspect: true

## Ready to run

## Operator-only (skipped by runner)

## In flight

## Completed this run

## Halted this run (needs review)

## Deferred
"""


def _auto_config(cfg):
    return """# auto-config.md

# --- Non-configurable invariants (stated, not set) ---
#  * Operator-only tasks are always skipped by the runner.
#  * The runner pauses (never terminates) when only operator action can
#    unblock remaining work.
#  * Urgent escalations always halt the queue.

max_concurrent_tasks: 2
consecutive_halt_threshold: 3
time_budget_minutes: 0          # 0 = unlimited
token_budget: 0                 # 0 = unlimited
task_budget: 0                  # 0 = unlimited
pause_on_max_iterations: false
pause_on_goal_condition_suspect: true
"""


def _auto_sh(cfg):
    # F-2 fix: auto.sh is a terminal-invoked runner, NOT a stdin-fed hook.
    # It must not inherit `INPUT="$(cat)"` (which blocks waiting for EOF) or
    # the jget machinery. The trap records a BOOTSTRAP.md exit_reason rather
    # than blanket `exit 0`, and only the EXIT arm cleans the sentinel.
    return '''#!/usr/bin/env bash
# Generated by bootstrap-installer. Autonomous queue runner (Phase 9.7).
# SKELETON: the dispatch loop is intentionally unimplemented - see README and
# BOOTSTRAP.md Phase 9.7. Do not use unattended until the loop and the
# exit_reason accounting below are completed and smoke-tested.
set -euo pipefail
# Self-locate: this script lives at <project>/.claude/auto.sh, so the project
# root is two levels up. Honour CLAUDE_PROJECT_DIR if set, else derive it -
# never assume the invocation cwd is the project root (F-2 follow-up).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
PROJ="${CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
LOG="$PROJ/.claude/logs/hooks.log"
mkdir -p "$(dirname "$LOG")"
log(){ printf '%s %s\\n' "$(date -u +%FT%TZ)" "$*" >>"$LOG"; }

RUN="$PROJ/.claude/queue/.run-active"
mkdir -p "$(dirname "$RUN")"            # queue dir may not exist yet
EXIT_REASON="infrastructure-failure"   # pessimistic default; set on clean paths

cleanup(){
  rc=$?
  rm -f "$RUN"
  log "auto.sh exit reason=$EXIT_REASON rc=$rc"
  # NOTE: a complete implementation updates the dangling queue_runs_history
  # entry here with end_timestamp and exit_reason before exiting.
  exit "$rc"
}
on_signal(){ EXIT_REASON="signal-interrupt"; exit 130; }
trap cleanup EXIT
trap on_signal INT TERM

if [ -e "$RUN" ]; then
  echo "A queue run is already active ($RUN). Refusing to start." >&2
  EXIT_REASON="manual-halt-sentinel"
  exit 1
fi
printf 'pid=%s start=%s\\n' "$$" "$(date -u +%FT%TZ)" >"$RUN"
log "auto.sh started (skeleton)."

echo "Queue runner skeleton installed. Implement the dispatch loop per" \\
     "BOOTSTRAP.md Phase 9.7 before any unattended use." >&2
EXIT_REASON="queue-empty"   # skeleton: nothing dispatched, treated as no-op
exit 0
'''


def _per_task_wrapper(kind: str) -> str:
    """Shared skeleton for the two per-task wrappers (loop.sh, goal-loop.sh).

    `kind` is "loop" or "goal". These are GUARDED SKELETONS, exactly like
    auto.sh: they perform the race-safe claim sequence BOOTSTRAP.md Phase 9.5
    step 2 mandates (O_CREAT|O_EXCL active sentinel, flock on the state file,
    tmpfile-then-rename state write) and the eligibility/`.halt` guards, then
    refuse to run the unattended `claude -p` loop, which is the part the
    operator must complete and smoke-test per the trust ramp. Failing safe
    here means: never start the agent loop, never hang from a terminal,
    always release the lock and remove the just-written sentinel on abort.
    """
    if kind == "loop":
        title = "Autonomous loop wrapper (Phase 9.5)"
        active = ".loop-active"
        sibling = ".goal-active"
        sib_list = "goal_in_flight"
        my_list = "loop_in_flight"
        phase = "9.5"
    else:
        title = "Goal-supervised wrapper (Phase 9.6)"
        active = ".goal-active"
        sibling = ".loop-active"
        sib_list = "loop_in_flight"
        my_list = "goal_in_flight"
        phase = "9.6"
    elig = "loop_eligible" if kind == "loop" else "goal_supervised_eligible"
    # NB: doubled braces are literal shell; {placeholders} are substituted.
    return '''#!/usr/bin/env bash
# Generated by bootstrap-installer. {title}.
# SKELETON: the claude -p iteration loop is intentionally unimplemented -
# see README and BOOTSTRAP.md Phase {phase}. The race-safe claim sequence and
# all fail-safe guards below ARE implemented; the agent loop is the part the
# operator completes and smoke-tests per the trust ramp. Until then this
# script refuses to dispatch any unattended work.
#
# Usage: {self} <task-id> [spec-id]
set -euo pipefail
# Self-locate: this script lives at <project>/.claude/{self}, so the project
# root is two levels up. Honour CLAUDE_PROJECT_DIR if set, else derive it -
# never assume the invocation cwd is the project root (F-2 idiom).
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]:-$0}}")" && pwd)"
PROJ="${{CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}}"
LOG="$PROJ/.claude/logs/hooks.log"
mkdir -p "$(dirname "$LOG")"
log(){{ printf '%s %s\\\\n' "$(date -u +%FT%TZ)" "$*" >>"$LOG"; }}

TASK_ID="${{1:-}}"
if [ -z "$TASK_ID" ]; then
  echo "usage: {self} <task-id> [spec-id]" >&2
  exit 2
fi
SESS="$PROJ/.claude/sessions"
mkdir -p "$SESS"
ACTIVE="$SESS/{active}-$TASK_ID"
STATE="$PROJ/.claude/.bootstrap-state.json"
HALT="$PROJ/.claude/queue/.halt"

CLAIMED=0
EXIT_REASON="infrastructure-failure"   # pessimistic; set on clean paths
cleanup(){{
  rc=$?
  # Only remove the sentinel if WE claimed it (never yank another wrapper's).
  [ "$CLAIMED" = 1 ] && rm -f "$ACTIVE"
  log "{self} task=$TASK_ID exit reason=$EXIT_REASON rc=$rc"
  # NOTE: a complete implementation removes this task's entry from
  # {my_list} (flock + tmpfile-rename) and writes loop-final-$TASK_ID.md here.
  exit "$rc"
}}
on_signal(){{ EXIT_REASON="signal-interrupt"; exit 130; }}
trap cleanup EXIT
trap on_signal INT TERM

# Honour the manual-halt sentinel before doing anything expensive.
if [ -e "$HALT" ]; then
  echo "Halt sentinel present ($HALT). Refusing to start." >&2
  EXIT_REASON="manual-halt-sentinel"
  exit 1
fi

# 1. Eligibility: the task definition must declare {elig}: true. Absent a
#    task file we refuse rather than assume eligibility (fail safe).
TASKFILE=""
for d in "$PROJ"/.claude/specs/*/tasks/; do
  [ -f "$d$TASK_ID.md" ] && TASKFILE="$d$TASK_ID.md" && break
done
if [ -z "$TASKFILE" ]; then
  echo "No task file for '$TASK_ID' under .claude/specs/*/tasks/." >&2
  EXIT_REASON="goal-condition-suspect"
  exit 1
fi
if ! grep -qE '^[[:space:]]*{elig}:[[:space:]]*true[[:space:]]*$' "$TASKFILE"
then
  echo "Task '$TASK_ID' is not {elig}: true. Refusing." >&2
  EXIT_REASON="goal-condition-suspect"
  exit 1
fi

# 2. Race-safe claim (BOOTSTRAP.md Phase {phase} step 2):
#    2.1 O_CREAT|O_EXCL active sentinel.
if ! ( set -C; printf '%s\\\\n' "$$" >"$ACTIVE" ) 2>/dev/null; then
  echo "Another {kind} run already owns '$TASK_ID' ($ACTIVE)." >&2
  EXIT_REASON="manual-halt-sentinel"
  exit 1
fi
CLAIMED=1
#    2.2-2.4 flock the state file, cross-mode mutual-exclusion check, append
#    to {my_list}, tmpfile-then-rename. flock is required; if it is missing
#    we fail safe (release sentinel via trap) rather than racing.
if ! command -v flock >/dev/null 2>&1; then
  echo "flock unavailable - cannot guarantee race-safe state update." >&2
  EXIT_REASON="infrastructure-failure"
  exit 1
fi
exec 9>"$STATE.lock"
flock 9
if ls "$SESS"/{sibling}-"$TASK_ID" >/dev/null 2>&1; then
  flock -u 9
  echo "Task '$TASK_ID' is already in the other autonomous mode. Aborting." >&2
  EXIT_REASON="goal-condition-suspect"
  exit 1
fi
# Append-to-{my_list} + tmpfile-then-rename is the operator-completed step;
# the lock/sentinel scaffolding around it is done. Skeleton stops here.
flock -u 9
log "{self} claimed task=$TASK_ID (skeleton: agent loop not implemented)"
echo "{title} skeleton: task '$TASK_ID' claimed and guarded. Implement the" >&2
echo "claude -p iteration loop per BOOTSTRAP.md Phase {phase} before any" >&2
echo "unattended use. No agent work was dispatched." >&2
EXIT_REASON="max-iterations"   # skeleton no-op: nothing iterated
exit 0
'''.format(title=title, phase=phase, self=("loop.sh" if kind == "loop"
                                            else "goal-loop.sh"),
           active=active, sibling=sibling, my_list=my_list,
           elig=elig, kind=kind)


def _loop_sh(cfg):
    return _per_task_wrapper("loop")


def _goal_loop_sh(cfg):
    return _per_task_wrapper("goal")


def _loop_config(cfg):
    return """# loop-config.md

# Operator-tunable loop-mode settings (BOOTSTRAP.md Phase 9.5).
# Format mirrors audio-alerts.config. Committed to the repo.

max_iterations: 10
infra_retry_seconds: 30
infra_max_consecutive_failures: 2
# Completion-criteria checks the wrapper trusts the agent's self-attestation
# on in loop mode (goal-supervised mode re-checks them independently):
require_completion_sentinel: true
"""


def _goal_config(cfg):
    return """# goal-config.md

# Operator-tunable goal-supervised settings (BOOTSTRAP.md Phase 9.6).
# Format mirrors audio-alerts.config. Committed to the repo.

max_iterations: 10
infra_retry_seconds: 30
infra_max_consecutive_failures: 2
judge_model: haiku
# Three consecutive malformed/missing iteration summaries => goal-condition
# -suspect-class halt (parallels persistent-evaluator-disagreement).
summary_failure_halt_threshold: 3
require_completion_sentinel: true
investigate_disagreement: false
"""


# --------------------------------------------------------------------------- #
# CLAUDE.md + specs index + gitignore
# --------------------------------------------------------------------------- #
def _claude_md(cfg):
    flags = cfg["autonomous_modes"]
    queue_section = ""
    if flags["queue_mode_enabled"]:
        queue_section = (
            "\n## Queue mode coordination layer\n\n"
            "`.claude/auto.sh` dispatches per-task wrappers from "
            "`.claude/queue/backlog.md`. The runner does not load this file; "
            "the queue is the coordination surface.\n")
    return f"""# CLAUDE.md

Thin by design. Steering lives in `.claude/steering/`. This file is the
escalation contract, not a knowledge dump.

## Workflow

Per-task lifecycle: spec-review -> spec-decompose -> plan-review -> implement
(decisions logged continuously) -> local gates -> code-review ->
spec-validate -> pr-author.

## Urgent escalations (AI stops and asks)

1. A do-not-touch / never-read path needs access or modification.
2. A secret or credential is encountered.
3. A hook blocks and the fix is not obvious within one attempt.
4. A dependency not on the `deps.md` approved list is needed.
5. Implementation reveals the spec was wrong.

Non-urgent (in-chat only): ambiguous acceptance criteria, two reasonable
approaches with material tradeoffs, spec version drift mid-task.

The escalation list is the contract. If the agent escalates outside it, fix
steering - do not override in-session.
{queue_section}"""


def _specs_index(cfg):
    return """# Specs Index

| slug | status | active version | in-flight against superseded? |
|------|--------|----------------|-------------------------------|
| _placeholder_ | planned | - | - |

Rows derived from the PRD (Phase 7.6) or invented by /spec-new at call time.
"""


def _gitignore(cfg):
    # BOOTSTRAP.md Recovery & State: bootstrap-internal state files use the
    # dotfile convention precisely so they are gitignored as a group; line
    # 825 additionally gitignores the per-iteration scratch sentinels while
    # keeping operator-facing audit records (loop-final-*, decisions-log-*,
    # backlog.md, run-summary-*) committed.
    base = [
        "logs/", ".last-test-pass", ".last-eval-pass",
        "sessions/.session-*", "sessions/.drift-*",
        "sessions/.decision-pending-*", "sessions/.quiet-*",
        "sessions/.loop-active-*", "sessions/.goal-active-*",
        "sessions/.loop-complete-*", "sessions/.loop-halt-*",
        "sessions/.iteration-summary-*", "sessions/.evaluator-feedback-*",
        ".installer-manifest.json", ".bootstrap-state.json",
        ".bootstrap-state.json.lock", ".bootstrap-incomplete",
    ]
    if cfg["autonomous_modes"]["queue_mode_enabled"]:
        base += ["queue/.run-active", "queue/.halt", "queue/.resume"]
        # NOTE: backlog.md and run-summary-*.md are intentionally NOT ignored.
    return "# bootstrap-installer generated\n" + "\n".join(base) + "\n"


# --------------------------------------------------------------------------- #
# Registry
# --------------------------------------------------------------------------- #
TEMPLATES = {
    "product": _product,
    "tech": _tech,
    "deps": _deps,
    "secrets": _secrets,
    "structure": _structure,
    "principles": _principles,
    "cicd": _cicd,
    "cicd_optout": _cicd_optout,
    "tools": _tools,
    "hook": _hook_body,
    "settings_json": _settings_json,
    "audio_config": _audio_config,
    "skills": _skills,
    "commands": _commands,
    "agents": _agents,
    "backlog": _backlog,
    "auto_config": _auto_config,
    "auto_sh": _auto_sh,
    "loop_sh": _loop_sh,
    "loop_config": _loop_config,
    "goal_loop_sh": _goal_loop_sh,
    "goal_config": _goal_config,
    "claude_md": _claude_md,
    "specs_index": _specs_index,
    "gitignore": _gitignore,
}
